### PR TITLE
Broadcaster: Don't pass a nil context into grpc call or it panics

### LINKED ISSUE #2585: panic in EndTranscodingSession
Getting a lot of these overnight:
```
2022/09/13 06:58:35 http: panic serving 10.42.2.174:59040: runtime error: invalid memory address or nil pointer dereference
goroutine 429613 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1802 +0xb9
panic({0x386a00, 0x2728d70})
	/usr/local/go/src/runtime/panic.go:1047 +0x266
google.golang.org/grpc/metadata.FromOutgoingContextRaw({0x0, 0x0})
	/go/pkg/mod/google.golang.org/grpc@v1.47.0/metadata/metadata.go:208 +0x1e
google.golang.org/grpc.newClientStream({0x0, 0x0}, 0x27c4ee0, 0xc011b97180, {0x56a25c, 0x100000000000000}, {0x0, 0x0, 0x0})
	/go/pkg/mod/google.golang.org/grpc@v1.47.0/stream.go:170 +0x96
google.golang.org/grpc.invoke({0x0, 0x0}, {0x56a25c, 0x20}, {0x49eea0, 0xc0009a2f60}, {0x482f60, 0xc002e878c0}, 0x0, {0x0, ...})
	/go/pkg/mod/google.golang.org/grpc@v1.47.0/call.go:66 +0x7d
google.golang.org/grpc.(*ClientConn).Invoke(0x7fc66412bfe8, {0x0, 0x0}, {0x56a25c, 0x0}, {0x49eea0, 0xc0009a2f60}, {0x482f60, 0xc002e878c0}, {0x0, ...})
	/go/pkg/mod/google.golang.org/grpc@v1.47.0/call.go:37 +0x265
github.com/livepeer/go-livepeer/net.(*orchestratorClient).EndTranscodingSession(0xc0014c57d0, {0x0, 0x0}, 0x87d260, {0x0, 0x0, 0x0})
	/src/net/lp_rpc.pb.go:2255 +0xce
github.com/livepeer/go-livepeer/server.EndTranscodingSession({0x0, 0x0}, 0xc0059722c0)
	/src/server/rpc.go:283 +0x125
github.com/livepeer/go-livepeer/server.(*BroadcastSessionsManager).completeSessionUnsafe(0xc002bd4000, {0x0, 0x0}, 0xc0059722c0, 0x80)
	/src/server/broadcast.go:649 +0x49
github.com/livepeer/go-livepeer/server.(*BroadcastSessionsManager).completeSession(0x85dce0, {0x0, 0x0}, 0x39, 0x80)
	/src/server/broadcast.go:664 +0xc9
github.com/livepeer/go-livepeer/server.(*BroadcastSessionsManager).cleanup(0xc002bd4000, {0x0, 0x0})
	/src/server/broadcast.go:482 +0x136
github.com/livepeer/go-livepeer/server.(*LivepeerServer).registerConnection(0xc01239c3f0, {0x87d260, 0xc0139347b0}, {0x898338, 0xc002514150}, 0xc0013870f0, {0x0}, 0xc012600400)
	/src/server/mediaserver.go:553 +0x95a
github.com/livepeer/go-livepeer/server.(*LivepeerServer).HandlePush(0xc01239c3f0, {0x872a98, 0xc0120607e0}, 0xc004317d00)
	/src/server/mediaserver.go:878 +0x1694
net/http.HandlerFunc.ServeHTTP(0x13725a6, {0x872a98, 0xc0120607e0}, 0xc0120607e0)
	/usr/local/go/src/net/http/server.go:2047 +0x2f
net/http.(*ServeMux).ServeHTTP(0x0, {0x872a98, 0xc0120607e0}, 0xc004317d00)
	/usr/local/go/src/net/http/server.go:2425 +0x149
net/http.serverHandler.ServeHTTP({0x870458}, {0x872a98, 0xc0120607e0}, 0xc004317d00)
	/usr/local/go/src/net/http/server.go:2879 +0x43b
net/http.(*conn).serve(0xc011bb4000, {0x87d260, 0xc012cc36b0})
	/usr/local/go/src/net/http/server.go:1930 +0xb08
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3034 +0x4e8
```

### PR DESCRIPTION
**Pull request by thomshutt**
**What does this pull request do? Explain your changes. (required)**
Stops a panic in the case we detect an existing session after creating one

**Specific updates (required)**
- Pass `context.Background()` instead of `nil` into the gRPC call

**How did you test each of these updates (required)**
- Ran unit tests

**Does this pull request close any open issues?**
Fixes #2585

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [x] README and other documentation updated
- [x] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

File: server/mediaserver.go [hunk 1]
```diff
@@ -550,7 +550,7 @@ func (s *LivepeerServer) registerConnection(ctx context.Context, rtmpStrm stream
 	if exists {
 		// We can only have one concurrent stream per ManifestID
 		s.connectionLock.Unlock()
-		cxn.sessManager.cleanup(nil)
+		cxn.sessManager.cleanup(context.Background())
```
Comment (yondonfu) [inline server/mediaserver.go]: Is there a way to update [this test](https://github.com/livepeer/go-livepeer/blob/master/server/mediaserver_test.go#L1157) so that without this change the test would trigger a panic?

Comment (yondonfu) [reply server/mediaserver.go]: Tagging in @cyberj0g as this line was last updated in a1fb76147.

FWIW I took a quick look at the [linked test](https://github.com/livepeer/go-livepeer/blob/master/server/mediaserver_test.go#L1157) and it seems like it'd be pretty tricky to trigger the code path that would result in this cleanup() call since registerConnection() will return `errAlreadyExists` in an [initial connection existence check](https://github.com/livepeer/go-livepeer/blob/3ff79bd7045fc72c1d810736a17af6128b83905b/server/mediaserver.go#L522) prior to the [second existence check](https://github.com/livepeer/go-livepeer/blob/3ff79bd7045fc72c1d810736a17af6128b83905b/server/mediaserver.go#L550) that is used for the clause that contains the cleanup() call. The existing [concurrent HandlePush test](https://github.com/livepeer/go-livepeer/blob/3ff79bd7045fc72c1d810736a17af6128b83905b/server/push_test.go#L1429) might be able to trigger this code path with some tweaking, but seems like that might be potentially flaky as you would still lack a way to deterministically trigger the clause for that second connection existence check...Worth another look, but if it a substantial effort then I think it is fine to merge this as-is (could consider refactoring at some point to make this type of test easier).

**Review by yondonfu — APPROVED** [review]

**Comment by cyberj0g** [comment]
It seems that explicitly marking connection as being initialized will allow to remove that rarely invoked and not covered 'rollback' code path. See my changes.

Edit: looks like there were a number of race conditions in `registerConnection` and elsewhere, we indirectly encountered only one of them. Hope it's better with this fix.

File: server/mediaserver.go [hunk 2]
```diff
@@ -78,6 +78,7 @@ var httpPushResetTimer = func() (context.Context, context.CancelFunc) {
 }
 
 type rtmpConnection struct {
+	initializing    chan error
```
Comment (yondonfu) [inline server/mediaserver.go:81]: Since this channel is just used for signaling and the type of the value doesn't matter we could use a `chan struct{}`.

File: server/mediaserver.go [hunk 3]
```diff
@@ -515,50 +531,66 @@ func (s *LivepeerServer) registerConnection(ctx context.Context, rtmpStrm stream
...
 		return oldCxn, errAlreadyExists
 	}
+	s.rtmpConnections[mid] = cxn
+	// do not obtain this lock again while initializing channel is open, it will cause deadlock if other goroutine already obtained the lock and called getActiveRtmpConnectionUnsafe()
+	s.connectionLock.Unlock()
 
-	playlist := core.NewBasicPlaylistManager(mid, storage, recordStorage)
+	// delete uninitialized connection in case of error
+	defer func() {
+		if <-cxn.initializing != nil {
```
Comment (yondonfu) [inline server/mediaserver.go]: There doesn't seem to be a scenario where an error would actually be passed to `initializing` since it is only closed later on.

File: server/mediaserver.go [hunk 4]
```diff
@@ -515,50 +531,66 @@ func (s *LivepeerServer) registerConnection(ctx context.Context, rtmpStrm stream
...
-	// Check if session exist again - potentially two sessions can be created simultaneously,
-	// so we don't want to overwrite one that was already created
-	if exists {
-		// We can only have one concurrent stream per ManifestID
-		s.connectionLock.Unlock()
-		cxn.sessManager.cleanup(nil)
-		return oldCxn, errAlreadyExists
-	}
-	s.rtmpConnections[mid] = cxn
+	// safe, because other coroutines should be waiting on initializing channel
```
Comment (yondonfu) [inline server/mediaserver.go]:
```suggestion
	// safe, because other goroutines should be waiting on initializing channel
```

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: server/mediaserver.go (hunk 2 above)
Comment (yondonfu) [inline server/mediaserver.go]: Can this be a `chan struct{}` if we are only ever signaling with a close?

**Comment by cyberj0g** [comment]
Thanks for review @yondonfu, all addressed.

**Review by yondonfu — APPROVED** [review]
LGTM. The refactored connection handling code seems cleaner and easier to reason about 👍 .

Before merging please update CHANGELOG_PENDING to reflect that this PR resolves the linked issue in a different way than the original PR title/description.
