### PR TITLE
cmd: fix keystore copy and pricePerUnit flag

### LINKED ISSUE #918: devtool setup does not provide `pricePerUnit` argument
I've been setting up broadcasters and transcoders as follows:
```
docker run -d -p 8545:8545 -p 8546:8546 --name geth-dev darkdragon/geth-with-livepeer-protocol:pm
```
...and each of the following in separate sessions:
```
go run cmd/devtool/devtool.go setup broadcaster | sh 
```
```
go run cmd/devtool/devtool.go setup transcoder | sh
```
The scripts are missing the `pricePerUnit` argument - go-livepeer complains:
```
 livepeer.go:327] Price per unit of pixels must be greater than 0, provided 0 instead
```

### LINKED ISSUE #921: devtool.go - invalid cross device link error on linux.
**Describe the bug**
Linux devices don't seem to like Golang's `os.Rename` , `the cmd/devtool/devtool.go` script is failing here in particular 

```
keystoreDir := filepath.Join(dataDir, "keystore")
	err = os.Rename(tempKeystoreDir, keystoreDir)
	if err != nil {
		glog.Fatal(err)
	}
```

**To Reproduce**
1. Spin up an ubuntu 18.04 vm
2. Build the go-livepeer repo
3. Run the commands described in #918 

```
$ go run cmd/devtool/devtool.go setup transcoder
I0617 19:20:20.041643   23018 devtool.go:330] Using ETH account: 0xf3389080b90AA6C99e824256674f1312b244A077
I0617 19:20:20.041711   23018 devtool.go:110] Using account 0xf3389080b90AA6C99e824256674f1312b244A077
F0617 19:20:20.041784   23018 devtool.go:120] rename /tmp/livepeer053087729/keystore .lpdev2/orchestrator_0xf3389080b90AA6C99e824256674f1312b244A077/keystore: invalid cross-device link
exit status 255
```

**Expected behavior**
Expect tempKeystore to be renamed without errors 

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04 LTS

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**
- Prevents the generated scripts from erroring for `setup transcoder` by supplying `-pricePerUnit 1` flag
- Uses custom function to copy the temporary keystore directory to prevent OS specific restrictions on `os.Rename`

**Specific updates (required)**
- Added `-pricePerUnit 1` flag to `createRunScript`
- Added custom function copyDir, copyFile
- Added generated `.lpdev2` to `.gitignore`

**How did you test each of these updates (required)**
Ran devtools script for both transcoder and broadcaster

**Does this pull request close any open issues?**
Fixes #921 
Fixes #918

**Checklist:**
- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

File: cmd/devtool/devtool.go [hunk 1]
```diff
@@ -412,3 +414,74 @@ func remoteConsole(destAccountAddr string) error {
 
 	return err
 }
+
+func copyDir(src, dst string) error {
```
Comment (darkdarkdragon) [inline cmd/devtool/devtool.go]: This function removes source dir at the end, so probably better be called `moveDir`?

File: cmd/devtool/devtool.go [hunk 2]
```diff
@@ -412,3 +414,74 @@ func remoteConsole(destAccountAddr string) error {
...
+	err = os.Remove(src)
+	if err != nil {
+		return err
+	}
+
+	return nil
+
+}
+
+func copyFile(src, dst string, info os.FileInfo) error {
```
Comment (darkdarkdragon) [inline cmd/devtool/devtool.go]: This function removes file at the end, so probably better be called `moveFile`?

**Review by darkdarkdragon — CHANGES_REQUESTED** [review]

**Comment by darkdarkdragon** [comment]
@kyriediculous 
I've pushed over commit that fixes setting up of broadcaster to be able to do transcoding.
Other from two small comment PR looks good.

**Comment by kyriediculous** [comment]
Made the requested changes and removed some blank lines.
Will clean up commit history before merging.

**Review by darkdarkdragon — APPROVED** [review]
LGTM 🚢
