### PR TITLE
eth: blockwatcher can process multiple blocks in a polling interval

### LINKED ISSUE #1575: Larger than expected number of TicketParams expired errors on orchestrators
**Describe the bug**

Some orchestrator operators have observed a large than expected number of TicketParams expired errors. 

Here is sample log output with a few TicketParams expired errors:

```
0711 15:50:17.582342     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/720p/2670.ts
I0711 15:50:17.604489     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/360p/2670.ts
I0711 15:50:17.882866     730 orchestrator.go:170] Receiving ticket manifestID=7f224d53-7fa1-4b50-ba1b-ba5910bb1e69 faceValue=0.028260869565217391 ETH winProb=0.0000353846 ev=1000000000000.00
E0711 15:50:17.883383     730 orchestrator.go:178] Error receiving ticket manifestID=7f224d53-7fa1-4b50-ba1b-ba5910bb1e69 recipientRandHash=1d49376343988dba637014ebd8849aa88feb8c9eb5f9797ab1f1c3dc01a7c24f senderNonce=1: TicketParams expired
E0711 15:50:17.883435     730 segment_rpc.go:74] error processing payment: TicketParams expired
I0711 15:50:18.298912     730 gaspricemonitor.go:134] Cached gas price: 23000000000
I0711 15:50:18.358074     730 orchestrator.go:433] Starting to transcode segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2671
I0711 15:50:18.358110     730 orchestrator.go:442] Submitted segment to transcode loop manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2671
I0711 15:50:18.459318     730 orchestrator.go:170] Receiving ticket manifestID=7f224d53-7fa1-4b50-ba1b-ba5910bb1e69 faceValue=0.028260869565217391 ETH winProb=0.0000353846 ev=1000000000000.00
E0711 15:50:18.459755     730 orchestrator.go:178] Error receiving ticket manifestID=7f224d53-7fa1-4b50-ba1b-ba5910bb1e69 recipientRandHash=d135bcf14528b5c631c70d298f7495bdcda69fd0dd15f8602fa972db07390be0 senderNonce=1: TicketParams expired
E0711 15:50:18.459793     730 segment_rpc.go:74] error processing payment: TicketParams expired
I0711 15:50:18.485397     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/2671.tempfile
I0711 15:50:18.614787     730 orchestrator.go:702] Successfully received results from remote transcoder=64.79.101.29:6459 segments=3 taskId=63052 fname=https://3.130.191.167:8935/stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/2671.tempfile err=<nil>
I0711 15:50:18.614827     730 orchestrator.go:525] Transcoding of segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2671 took=256.358256ms
I0711 15:50:18.614842     730 orchestrator.go:540] Transcoded segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2671 profile=720p len=240076
I0711 15:50:18.616526     730 orchestrator.go:540] Transcoded segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2671 profile=360p len=159988
I0711 15:50:18.617625     730 orchestrator.go:540] Transcoded segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2671 profile=240p len=84036
I0711 15:50:18.630063     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/240p/2671.ts
I0711 15:50:18.630372     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/360p/2671.ts
I0711 15:50:18.654040     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/720p/2671.ts
I0711 15:50:18.725817     730 orchestrator.go:433] Starting to transcode segment manifestID=41fcf9cc-3cb2-41e5-8181-868ed195ce07 seqNo=333
I0711 15:50:18.725857     730 orchestrator.go:442] Submitted segment to transcode loop manifestID=41fcf9cc-3cb2-41e5-8181-868ed195ce07 seqNo=333
I0711 15:50:18.849322     730 player.go:105] LPMS got HTTP request @ /stream/41fcf9cc-3cb2-41e5-8181-868ed195ce07/333.tempfile
I0711 15:50:18.987307     730 orchestrator.go:702] Successfully received results from remote transcoder=64.79.101.29:6459 segments=3 taskId=63053 fname=https://3.130.191.167:8935/stream/41fcf9cc-3cb2-41e5-8181-868ed195ce07/333.tempfile err=<nil>
I0711 15:50:18.987350     730 orchestrator.go:525] Transcoding of segment manifestID=41fcf9cc-3cb2-41e5-8181-868ed195ce07 seqNo=333 took=260.770562ms
I0711 15:50:18.987386     730 orchestrator.go:540] Transcoded segment manifestID=41fcf9cc-3cb2-41e5-8181-868ed195ce07 seqNo=333 profile=720p len=544824
I0711 15:50:18.991133     730 orchestrator.go:540] Transcoded segment manifestID=41fcf9cc-3cb2-41e5-8181-868ed195ce07 seqNo=333 profile=360p len=318660
I0711 15:50:18.993357     730 orchestrator.go:540] Transcoded segment manifestID=41fcf9cc-3cb2-41e5-8181-868ed195ce07 seqNo=333 profile=240p len=166568
I0711 15:50:19.005662     730 player.go:105] LPMS got HTTP request @ /stream/41fcf9cc-3cb2-41e5-8181-868ed195ce07/240p/333.ts
I0711 15:50:19.006078     730 player.go:105] LPMS got HTTP request @ /stream/41fcf9cc-3cb2-41e5-8181-868ed195ce07/720p/333.ts
I0711 15:50:19.029205     730 player.go:105] LPMS got HTTP request @ /stream/41fcf9cc-3cb2-41e5-8181-868ed195ce07/360p/333.ts
I0711 15:50:19.324591     730 orchestrator.go:170] Receiving ticket manifestID=7f224d53-7fa1-4b50-ba1b-ba5910bb1e69 faceValue=0.028260869565217391 ETH winProb=0.0000353846 ev=1000000000000.00
E0711 15:50:19.325108     730 orchestrator.go:178] Error receiving ticket manifestID=7f224d53-7fa1-4b50-ba1b-ba5910bb1e69 recipientRandHash=86bb5ad81faa117062519fc853c2e21428ac2304cbaa241c1b71f9f273fa6f80 senderNonce=1: TicketParams expired
I0711 15:50:19.325209     730 orchestrator.go:170] Receiving ticket manifestID=7f224d53-7fa1-4b50-ba1b-ba5910bb1e69 faceValue=0.028260869565217391 ETH winProb=0.0000353846 ev=1000000000000.00
E0711 15:50:19.325663     730 orchestrator.go:178] Error receiving ticket manifestID=7f224d53-7fa1-4b50-ba1b-ba5910bb1e69 recipientRandHash=86bb5ad81faa117062519fc853c2e21428ac2304cbaa241c1b71f9f273fa6f80 senderNonce=2: TicketParams expired
E0711 15:50:19.325694     730 segment_rpc.go:74] error processing payment: TicketParams expired
I0711 15:50:19.371620     730 orchestrator.go:433] Starting to transcode segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2672
I0711 15:50:19.371663     730 orchestrator.go:442] Submitted segment to transcode loop manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2672
I0711 15:50:19.501933     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/2672.tempfile
I0711 15:50:19.607324     730 orchestrator.go:702] Successfully received results from remote transcoder=64.79.101.29:6459 segments=3 taskId=63054 fname=https://3.130.191.167:8935/stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/2672.tempfile err=<nil>
I0711 15:50:19.607365     730 orchestrator.go:525] Transcoding of segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2672 took=235.303684ms
I0711 15:50:19.607380     730 orchestrator.go:540] Transcoded segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2672 profile=720p len=260944
I0711 15:50:19.609193     730 orchestrator.go:540] Transcoded segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2672 profile=360p len=169952
I0711 15:50:19.610353     730 orchestrator.go:540] Transcoded segment manifestID=2500e7f3-4265-43e8-8aa8-df1d01a94201 seqNo=2672 profile=240p len=88924
I0711 15:50:19.622737     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/240p/2672.ts
I0711 15:50:19.623045     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/720p/2672.ts
I0711 15:50:19.645546     730 player.go:105] LPMS got HTTP request @ /stream/2500e7f3-4265-43e8-8aa8-df1d01a94201/360p/2672.ts
I0711 15:50:20.217768     730 orchestrator.go:170] Receiving ticket manifestID=45790cb5-ce6a-480b-88e7-f9eec607a963 faceValue=0.028260869565217391 ETH winProb=0.0000353846 ev=1000000000000.00
E0711 15:50:20.218356     730 orchestrator.go:178] Error receiving ticket manifestID=45790cb5-ce6a-480b-88e7-f9eec607a963 recipientRandHash=051e6934ad70e229715406578720a475940638006bfd920a2b553391d5f11a2c senderNonce=1: TicketParams expired
E0711 15:50:20.218412     730 segment_rpc.go:74] error processing payment: TicketParams expired
```

**Expected behavior**

A lower number of TicketParams expired errors because a broadcaster should [refresh its ticket params](https://github.com/livepeer/go-livepeer/blob/6ddf9f8d8ad11e3ddcc582c889c00aa9c46e5caa/server/broadcast.go#L400) for an orchestrator whenever it sees that the ticket params are expired.

Possible reasons for this larger number of TicketParams expired errors:

1. The ticket params expire after the broadcaster validates them (i.e. in network transit)
2. Broadcaster and orchestrators have different views of the head of the chain. For example, if a broadcaster sees block N - 5 and an orchestrator sees block N, then the broadcaster would not refresh a set of ticket params that expire at block N and when the orchestrator receives the payment it will see that the ticket params are expired.

Things that might be worth looking into:

- Block sync issues for the broadcaster and orchestrator
- Set longer expiration periods for ticket params on the orchestrator (currently set to 5 blocks which is pretty short)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Linux
 - Version [e.g. 22]: 0.5.9

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**
Currently the blockwatcher will only process a single block per polling interval. This PR implements a `syncToLatestBlock` function that's called on each polling interval. 

This function requests the last block from a remote ethereum node and loops `pollNextBlock()` until the block number of the top of the stack equals that of the last block. 

**How did you test each of these updates (required)**
Tested manually on rinkeby with a polling interval of 60 seconds

**Does this pull request close any open issues?**
Fixes #1575  where nodes would run into expired ticket param errors due to their nodes falling behind on blocks when setting polling intervals greater than the block time. This can still occur however because ticket params expiration is 5 blocks, so the polling interval should still be small enough. We could lengthen this expiration time in a subsequent PR if necessary.

**Checklist:**
- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

File: eth/blockwatch/block_watcher.go [hunk 1]
```diff
@@ -146,6 +146,25 @@ func (w *Watcher) InspectRetainedBlocks() ([]*MiniHeader, error) {
...
+
+	for {
+		latestHeader, err := w.stack.Peek()
+		if err != nil {
+			return err
+		}
+		if lastBlock.Number.Cmp(latestHeader.Number) == 0 {
+			break
+		}
+		w.pollNextBlock()
```
Comment (yondonfu) [inline eth/blockwatch/block_watcher.go]: Let's handle the error returned here.

File: eth/blockwatch/block_watcher.go [hunk 2]
```diff
@@ -146,6 +146,25 @@ func (w *Watcher) InspectRetainedBlocks() ([]*MiniHeader, error) {
 	return w.stack.Inspect()
 }
 
+func (w *Watcher) syncToLatestBlock() error {
+	lastBlock, err := w.client.HeaderByNumber(nil)
```
Comment (yondonfu) [inline eth/blockwatch/block_watcher.go]: Should this be called lastHeader since HeaderByNumber returns a header?

File: eth/blockwatch/block_watcher.go [hunk 3]
```diff
@@ -146,6 +146,25 @@ func (w *Watcher) InspectRetainedBlocks() ([]*MiniHeader, error) {
...
+	if err != nil {
+		return err
+	}
+
+	for {
+		latestHeader, err := w.stack.Peek()
```
Comment (yondonfu) [inline eth/blockwatch/block_watcher.go]: Currently, we call Peek() once for each loop iteration. What about calling Peek() once, calculating the # of headers to fetch and then running the loop that many times? Avoids the extra DB reads and a tad bit more explicit when the loop will end.

File: eth/blockwatch/block_watcher.go [hunk 4]
```diff
@@ -146,6 +146,25 @@ func (w *Watcher) InspectRetainedBlocks() ([]*MiniHeader, error) {
 	return w.stack.Inspect()
 }
 
+func (w *Watcher) syncToLatestBlock() error {
```
Comment (yondonfu) [inline eth/blockwatch/block_watcher.go:149]: Is it possible for issues to arise if multiple calls for this method are in-progress? i.e. After tick 1, we start syncing N blocks, but before that sync completes, tick 2 occurs and we start another sync. Seems like this would depend on the polling interval (which sets how often ticks/syncs occur) and the speed of the header fetching requests - likely not a common issue, but maybe possible to occur under certain circumstances?

I see that the upstream package uses a [mutex](https://github.com/0xProject/0x-mesh/blob/80d4c33b9c753dd967dd653d6fbfb8f46dffc606/ethereum/blockwatch/block_watcher.go#L92) that might guard against this particular issue.

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: eth/blockwatch/block_watcher.go (hunk 2 above)
Comment (kyriediculous) [reply eth/blockwatch/block_watcher.go]: Adopted the naming from https://github.com/0xProject/0x-mesh/blob/80d4c33b9c753dd967dd653d6fbfb8f46dffc606/ethereum/blockwatch/block_watcher.go#L257

File: eth/blockwatch/block_watcher.go (hunk 4 above)
Comment (kyriediculous) [reply eth/blockwatch/block_watcher.go:149]: fixed in https://github.com/livepeer/go-livepeer/pull/1729/commits/511c85802c591398ed2ba931af5013a70cea502a

File: eth/blockwatch/block_watcher.go (hunk 3 above)
Comment (kyriediculous) [reply eth/blockwatch/block_watcher.go]: fixed in https://github.com/livepeer/go-livepeer/pull/1729/commits/511c85802c591398ed2ba931af5013a70cea502a

File: eth/blockwatch/block_watcher.go (hunk 1 above)
Comment (kyriediculous) [reply eth/blockwatch/block_watcher.go]: fixed in https://github.com/livepeer/go-livepeer/pull/1729/commits/511c85802c591398ed2ba931af5013a70cea502a

File: eth/blockwatch/block_watcher.go (hunk 4 above)
Comment (kyriediculous) [reply eth/blockwatch/block_watcher.go:149]: Forgot `defer` for the unlock added in subsequent commit

File: eth/blockwatch/block_watcher.go (hunk 2 above)
Comment (yondonfu) [reply eth/blockwatch/block_watcher.go]: Bump because it looks like the variable name here was not updated.

File: eth/blockwatch/block_watcher.go [hunk 5]
```diff
@@ -146,6 +146,27 @@ func (w *Watcher) InspectRetainedBlocks() ([]*MiniHeader, error) {
...
+	if err != nil {
+		return err
+	}
+
+	latestHeader, err := w.stack.Peek()
+	if err != nil {
+		return err
+	}
+
+	for i := lastBlock.Number; i.Cmp(latestHeader.Number) == 0; i = i.Add(i, big.NewInt(1)) {
```
Comment (yondonfu) [inline eth/blockwatch/block_watcher.go]: There are a few issues with this loop:

- The conditional needs to be updated here. This loop would never run when latestHeader.Number != i because `i.Cmp(latestHeader.Number) == 0` evaluates to false on the first iteration
- The loop counter is not being initialized properly. lastBlock.Number will actually be the latest block number and latestHeader.Number will actually be the last block number stored (the variable names should be updated to clarify the value they refer to). So, if lastBlock.Number > latestHeader.Number, this loop would never run even if the conditional issue mentioned above was fixed

Let's fix this and make sure to at the very least manually test it as well.

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: eth/blockwatch/block_watcher.go (hunk 5 above)
Comment (kyriediculous) [reply eth/blockwatch/block_watcher.go]: manually tested on rinkeby with a block polling interval of 1 minute and confirmed we process 3-4 blocks every interval

**Review by yondonfu — APPROVED** [review]
LGTM 🚢  after squashing
