### PR TITLE
devtool - auto find controller address and mining account

### LINKED ISSUE #663: Devtool flags
**Describe the bug**
Devtool is missing some flags that are required to generate a functioning setup; as a result it can only be compatible with fresh protocol deployments by changing hardcoded values.

- [ ] gethMiningAccount
- [ ] controllerAddr
- [ ] network name (should also probably default to devenv, not mainnet)

These are the local changes I had to make to get things working:

```diff
diff --git a/cmd/devtool/devtool.go b/cmd/devtool/devtool.go
index 9683ec1e..d9b8401d 100644
--- a/cmd/devtool/devtool.go
+++ b/cmd/devtool/devtool.go
@@ -20,8 +20,8 @@ import (
 )
 
 const (
-	gethMiningAccount = "87da6a8c6e9eff15d703fc2773e32f6af8dbe301"
-	controllerAddr    = "93ad00a63b14492386df9f1cc123d785705bdf99"
+	gethMiningAccount = "2a78627a7d6648a048f31ec7e130df8a0a0aec27"
+	controllerAddr    = "91D178E5c3D85a60963a5886765D6e26235f172E"
 	clientIdentifier  = "geth" // Client identifier to advertise over the network
 	passphrase        = ""
 	serviceURI        = "https://127.0.0.1:8936"
@@ -73,7 +73,7 @@ func main() {
 	acc := createKey(tempKeystoreDir)
 	glog.Infof("Using account %s", acc)
 	dataDir := filepath.Join(*baseDataDir, t+"_"+acc)
-	dataDirToCreate := filepath.Join(dataDir, "mainnet")
+	dataDirToCreate := filepath.Join(dataDir, "devenv")
 	err = os.MkdirAll(dataDirToCreate, 0755)
 	if err != nil {
 		glog.Fatalf("Can't create directory %v", err)
@@ -247,7 +247,7 @@ func createRunScript(ethAcctAddr, dataDir string, isBroadcaster bool) {
 
 	if !isBroadcaster {
 		script += fmt.Sprintf(` -initializeRound=true \
-    -serviceAddr 127.0.0.1:8936 -httpAddr 127.0.0.1:8936  -transcoder \
+    -serviceAddr 127.0.0.1:8936 -httpAddr 127.0.0.1:8936  -transcoder -devenv \
     -cliAddr 127.0.0.1:7936 -ipfsPath ./%s/trans
     `, dataDir)
 	}
```

**To Reproduce**
Run `./devtool -endpoint "ws://brix.local:8546" setup transcoder` with the `pm` branch deployed on devenv. My devtool/node is running remotely from devenv in this case; substitute the endpoint as necessary.

**Expected behavior**

The transcoder should be successfully registered.

### PR DESCRIPTION
**Pull request by darkdarkdragon**
**What does this pull request do? Explain your changes. (required)**
Automatically finds Geth mining account and controller address in devtool.

**Specific updates (required)**
- add auto discovery of Geth mining account and of controller address
- added `miningaccount` and `controller` command line flags to override, if necessary

**How did you test each of these updates (required)**
Tested against devenv with protocol's pm branch, and against docker with old and new protocols.

**Does this pull request close any open issues?**
Fixes #663 

**Checklist:**

- [ ] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [ ] All tests in `./test.sh` pass

### CODE REVIEW

File: cmd/devtool/devtool.go [hunk 1]
```diff
@@ -299,6 +315,34 @@ func remoteConsole(destAccountAddr string) error {
 	}
 	defer console.Stop(false)
 
+	if !controllerAddrOverride {
+		// f9a6cf519167d81bc5cb3d26c60c0c9a19704aa908c148e82a861b570f4cd2d7 - SetContractInfo event
+		getControllerAddressScript := `
+		var logs = [];
+		var filter = web3.eth.filter({ fromBlock: 0, toBlock: "latest",
+			topics: ["0xf9a6cf519167d81bc5cb3d26c60c0c9a19704aa908c148e82a861b570f4cd2d7"]});
```
Comment (angyangie) [inline cmd/devtool/devtool.go:323]: I'm curious - where does this value come from?

File: cmd/devtool/devtool.go [hunk 2]
```diff
@@ -20,27 +22,39 @@ import (
...
 )
 
 var (
-	ethTxTimeout = 600 * time.Second
-	endpoint     = "ws://localhost:8546/"
+	ethTxTimeout              = 600 * time.Second
+	endpoint                  = "ws://localhost:8546/"
+	gethMiningAccount         = "87da6a8c6e9eff15d703fc2773e32f6af8dbe301"
+	gethMiningAccountOverride = false
+	controllerAddr            = "0x04B9De88c81cda06165CF65a908e5f1EFBB9493B"
```
Comment (angyangie) [inline cmd/devtool/devtool.go:35]: What are some example situations in which you'd have to change the `gethMiningAccount` and/or `controllerAddr`, and set the `gethMiningAccountOverride` and `controllerAddrOverride` to true?

File: cmd/devtool/devtool.go (hunk 1 above)
Comment (darkdarkdragon) [reply cmd/devtool/devtool.go:323]: I've made comment couple lines before, but it's not detailed enough if your not familiar with Eth - in Eth, events identified by making keccak hash of event signature, for this case it is `keccack("SetContractInfo(bytes32,address,bytes20)")` - where `SetContractInfo` is event name and in parentheses - arguments types.

File: cmd/devtool/devtool.go (hunk 2 above)
Comment (darkdarkdragon) [reply cmd/devtool/devtool.go:35]: it is for the cases I'm not accounted for - for example, probably it will not work on Rinkeby, because I'm trying to enumerate events from first block till latest.

**Review by angyangie — APPROVED** [review]
