### PR TITLE
Fix HTTP push handler accepting bad URL

### LINKED ISSUE #1283: Panic in HTTP push handler
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0xf4af36]

goroutine 24705 [running]:
github.com/livepeer/go-livepeer/server.(*LivepeerServer).HandlePush.func1(0xc00016de00, 0xc000231b20, 0xc0001f45a0, 0x24)
        /build/server/mediaserver.go:624 +0xd6
created by github.com/livepeer/go-livepeer/server.(*LivepeerServer).HandlePush
        /build/server/mediaserver.go:621 +0x8a9

### PR DESCRIPTION
**Pull request by darkdarkdragon**
**What does this pull request do? Explain your changes. (required)**
In HTTP push handler, check that manifest ID parsed from incoming URL is not empty.

**How did you test each of these updates (required)**
Unit test added.

**Does this pull request close any open issues?**
Fixes #1283 

**Checklist:**

- [ ] README and other documentation updated
- [ ] Node runs in OSX and devenv
- [ ] All tests in `./test.sh` pass

### CODE REVIEW

File: server/mediaserver.go [hunk 1]
```diff
@@ -592,12 +591,16 @@ func (s *LivepeerServer) HandlePush(w http.ResponseWriter, r *http.Request) {
 
 	now := time.Now()
 	mid := parseManifestID(r.URL.Path)
-	s.connectionLock.Lock()
+	if mid == "" {
+		http.Error(w, `Bad URL`, http.StatusBadRequest)
+		return
+	}
+	s.connectionLock.RLock()
```
Comment (j0sh) [inline server/mediaserver.go]: The `cxn.lastUsed = now` assignment is a write, not a read - need to keep the `Lock` here. (Yes, it is not ideal to take a global lock here but it's OK, for now to avoid introducing yet another layer of connection-level locking.)

Comment (darkdarkdragon) [reply server/mediaserver.go]: It doesn't mutate `rtmpConnections` map - which we're protecting by this lock. So why not to use `RLock`?

File: server/mediaserver.go [hunk 2]
```diff
@@ -412,8 +412,8 @@ func (s *LivepeerServer) registerConnection(rtmpStrm stream.RTMPVideoStream) (*r
 	hlsStrmID := core.MakeStreamID(mid, &vProfile)
 	s.connectionLock.Lock()
 	_, exists := s.rtmpConnections[mid]
-	s.connectionLock.Unlock()
```
Comment (j0sh) [inline server/mediaserver.go:415]: The following few lines of code can be very expensive, especially in other function call-outs where we don't necessarily always know how long they will take (eg, `NewBasicPlaylistManager` and `NewSessionManager`).

In fact, we all spent a few days debugging a deadlock in this exact same spot a few months ago because we were holding the lock for too long during `NewSessionManager`. We have a few options here:

* Make any external calls outside the lock. This is what the old code does.

* Check again that the session exists before assigning within the lock. We could add this.

* Accept that we might get multiple sessions or requests for a given manifest ID. This usually means the client is behaving inappropriately and shouldn't happen under normal conditions. In our case, the worst that happens is that "old" sessions get overwritten. That seems OK here. What we should ensure is that crash-prone bits are made more robust. If understand the root of the crash in https://github.com/livepeer/go-livepeer/pull/1284 correctly, it was something like this:

1. Multiple pushes come in very quickly such that the several sessions are created for the same manifest ID.
2. Multiple cleanup tickers are started
3. Cleanup ticker didn't check for the existence of the connection
4. Hence, if one connection was cleaned up, the second would lead to a crash

The actual solution for here seems to be to fix the cleanup ticker to check for existence of the connection, rather than making changes around locking here.

File: server/mediaserver.go (hunk 1 above)
Comment (j0sh) [reply server/mediaserver.go]: Multiple requests to the same MID could still change the same object

Comment (darkdarkdragon) [reply server/mediaserver.go]: It's just one `lastUsed` field. Don't see any problem in that.

File: server/mediaserver.go (hunk 2 above)
Comment (darkdarkdragon) [reply server/mediaserver.go:415]: > Check again that the session exists before assigning within the lock. We could add this.
> The actual solution for here seems to be to fix the cleanup ticker to check for existence of the connection

Made both 26a4773e393a7e8159e84dac30145ffe5482ffe7

File: server/mediaserver.go [hunk 3]
```diff
@@ -410,9 +410,9 @@ func (s *LivepeerServer) registerConnection(rtmpStrm stream.RTMPVideoStream) (*r
 		Bitrate:    "4000k", // Fix this
 	}
 	hlsStrmID := core.MakeStreamID(mid, &vProfile)
-	s.connectionLock.Lock()
+	s.connectionLock.RLock()
```
Comment (j0sh) [inline server/mediaserver.go:414]: Maybe add a comment explaining that we do an early check for session existence here because it may be a while between initializing a session and assigning the session to the connection map. (Otherwise the code reads a bit strangely, since we do the same check almost immediately after the other.)

Comment (darkdarkdragon) [reply server/mediaserver.go:414]: Added comments in db802aeba273c686aaa8e0f58d03c65983830fe6

**Comment by darkdarkdragon** [comment]
> Also, could we add a unit test for this case?

Added unit tests covering all branches with `lastUsed` in db802aeba273c686aaa8e0f58d03c65983830fe6

File: server/mediaserver.go [hunk 4]
```diff
@@ -616,19 +630,23 @@ func (s *LivepeerServer) HandlePush(w http.ResponseWriter, r *http.Request) {
...
 
-		ticker := time.NewTicker(RefreshIntervalHttpPush)
+		ticker := time.NewTicker(refreshIntervalHttpPush)
 
 		go func(s *LivepeerServer, mid core.ManifestID) {
+			defer ticker.Stop()
 			for range ticker.C {
 				s.connectionLock.RLock()
-				lastUsed := s.rtmpConnections[mid].lastUsed
-				s.connectionLock.RUnlock()
```
Comment (j0sh) [inline server/mediaserver.go:625]: Best to keep lock handling to a minimum since it's so easy to mess up. Right now, the unlock needs to be special-cased in three different places, which makes reasoning about the flow difficult. An improvement would be something like:

```golang
lastUsed := time.Now().Sub(2 * refreshIntervalHttpPush) // default to remove if nonexistent
s.connectionLock.RLock()
cxn, exists := s.rtmpConnections[mid]
if exists {
  lastUsed = cxn.lastUsed
}
s.connectionLock.RULock()

if time.Since(lastUsed) {
  removeRTMPStream(s, mid)
}
```

Comment (darkdarkdragon) [reply server/mediaserver.go:625]: Fixed

File: server/mediaserver.go [hunk 5]
```diff
@@ -635,18 +635,16 @@ func (s *LivepeerServer) HandlePush(w http.ResponseWriter, r *http.Request) {
...
-				if cxn, exists := s.rtmpConnections[mid]; exists {
-					if time.Since(cxn.lastUsed) > refreshIntervalHttpPush {
-						s.connectionLock.RUnlock()
-						_ = removeRTMPStream(s, mid)
-						return
-					}
-				} else {
-					s.connectionLock.RUnlock()
-					return
+				if cx, exists := s.rtmpConnections[mid]; exists {
```
Comment (j0sh) [inline server/mediaserver.go]: We use `cxn` as a matter of convention elsewhere. Maybe preserve that? Otherwise, these changes look good.

Comment (darkdarkdragon) [reply server/mediaserver.go]: fixed

**Review by j0sh — APPROVED** [review]
🚢
