### PR TITLE
server: set transcoding options in offchain mode

### LINKED ISSUE #681: Set -transcodingOptions in offchain mode
**Describe the bug**
The `BroadcastJobVideoProfiles` field in `mediaserver.go` is set via the `-transcodingOptions` CLI flag during `StartMediaServer`. However, this only happens in onchain mode. This should work in offchain mode as well.

**To Reproduce**
* Run a broadcast node with `-offchain -orchAddr ... -transcodingOptions P240p30fps4x3`
* Start a stream and check the transcoded output
* The default transcoding options are used instead rather than the given `-transcodingOptions` field.

**Expected behavior**
The `-transcodingOptions` should be used in offchain mode, rather than the defaults.

### PR DESCRIPTION
**Pull request by yondonfu**
**What does this pull request do? Explain your changes. (required)**

Allow a broadcaster to use the `-transcodingOptions` flag to set requested video profiles for transcoding even when in off-chain mode.

**Specific updates (required)**

- Set `BroadcastJobVideoProfiles` in `mediaserver.go` even when in off-chain mode

**How did you test each of these updates (required)**

Ran the node in devenv with the `-offchain` and `-transcodingOptions` flags.

**Does this pull request close any open issues?**

Fixes #681 

**Checklist:**

- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

File: server/mediaserver.go [hunk 1]
```diff
@@ -102,18 +102,16 @@ func NewLivepeerServer(rtmpAddr string, httpAddr string, lpNode *core.LivepeerNo
...
+		p, ok := ffmpeg.VideoProfileLookup[strings.TrimSpace(opt)]
+		if ok {
+			bProfiles = append(bProfiles, p)
 		}
-		BroadcastJobVideoProfiles = bProfiles
-		glog.V(common.SHORT).Infof("Transcode Job Price: %v, Transcode Job Type: %v", BroadcastPrice, BroadcastJobVideoProfiles)
 	}
+	BroadcastJobVideoProfiles = bProfiles
+
+	glog.V(common.SHORT).Infof("Transcode Video Profiles: %v", BroadcastJobVideoProfiles)
```
Comment (j0sh) [inline server/mediaserver.go]: The broadcast price was printed before. Shouldn't we still print it now?

**Review by j0sh — APPROVED** [review]
Just a small comment regarding logging, otherwise LGTM 🚢

File: server/mediaserver.go (hunk 1 above)
Comment (yondonfu) [reply server/mediaserver.go]: Broadcast price isn't used right now, but perhaps it will used in the future when we add support for broadcasters to set max prices to use for payments - added it back to the log message!
