### PR TITLE
server: fix current round locked check in activateOrchestrator

### LINKED ISSUE #1648: CLI: Activate orchestrator always results in "error: current round is locked"
**Describe the bug**
After Invoke multi-step "become an orchestrator" follow with
Error activating orchestrator: current round is locked.

The round is not actually locked 

**Expected behavior**
Should only throw error when the roundi s locked 

**Additional context**
the following code https://github.com/livepeer/go-livepeer/blob/9d47b956559b00d07951dd4ae29f4d03969bf08f/server/webserver.go#L234 results in a false positive for the round being locked 
```golang
		ok, err := s.LivepeerNode.Eth.CurrentRoundLocked()
		if err != nil {
			respondWith500(w, err.Error())
			return
		}
		if !ok {
			respondWith500(w, "current round is locked")
			return
		}

```

`if !ok`  should be `if ok` but we should also rename `ok` to `isLocked` for readability

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**
Fix current round locked check in `/activateOrchestrator` endpoint for the CLI server which will always respond that the current round is locked 

**Does this pull request close any open issues?**
Fixes #1648 

**Checklist:**
- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

File: server/webserver.go [hunk 1]
```diff
@@ -231,12 +231,12 @@ func (s *LivepeerServer) cliWebServerHandlers(bindAddr string) *http.ServeMux {
 			return
 		}
 
-		ok, err := s.LivepeerNode.Eth.CurrentRoundLocked()
+		isLocked, err := s.LivepeerNode.Eth.CurrentRoundLocked()
 		if err != nil {
 			respondWith500(w, err.Error())
 			return
 		}
-		if !ok {
```
Comment (yondonfu) [inline server/webserver.go:239]: Since this is something a test would've caught what do you think about adding a test case that a) fails without this change and b) passes with this change?

Comment (kyriediculous) [reply server/webserver.go:239]: Added in e8e0bb51 along with some form param tests , decided to omit some other stuff would take quite a bit of time to add 100% coverage due to all the several codepaths and is not relevant for this PR.

Comment (kyriediculous) [reply server/webserver.go:239]: Not sure why the subsequent tests fail all of a sudden still, I made sure to properly close the server and request bodies in 133b459

Comment (yondonfu) [reply server/webserver.go:239]: > Not sure why the subsequent tests fail all of a sudden still

915349c should fix those tests. Previously, e8e0bb5 passed `eth.StubClient{}` as an arg to the LivepeerNode constructor in `newMockServer()` which caused test cases in `TestGetEthChainID` that expected LivepeerNode to be in off-chain mode (the test cases for error cases) to break.

**Review by yondonfu — APPROVED** [review]
LGTM pending green CI and squashing fixup commits.
