### PR TITLE
Clear the video segment cache after the stream is finished.

### LINKED ISSUE #443: MediaPlaylist does NOT get cleaned up
**Describe the bug**
Unlike the MasterPlaylist, the MediaPlaylist doesn't get cleaned up when the stream stops.  This makes it look like old video segments are always lingering around.

**To Reproduce**
1. Stream a RTMP stream into the server.  It should create a HLS master playlist and a media playlist.
2. Stop the stream.
3. Curl the master playlist by `curl localhost:8935/stream/{masterPlaylistID}.m3u8`.  It should be gone.
4. Curl the media playlist by `curl localhost:8935/stream/{mediaPlaylistID}.m3u8`.  It's still there.

**Expected behavior**
The media playlist and the segments should both be cleaned up.

**Additional context**
This is the issue @chrishobcroft was seeing yesterday during the broadcast.  Furthermore, it causes the new stream to work incorrectly (the new stream doesn't get properly created)

### PR DESCRIPTION
**Pull request by ericxtang**
`GetHLSSubsciber` and `EvictHLSSubscriber` are not used by any external users, so I removed them from the interface.

Adding `EvictHLSStream` to address https://github.com/livepeer/go-livepeer/issues/443

This closes https://github.com/livepeer/go-livepeer/issues/443

### CODE REVIEW

**Review by j0sh — CHANGES_REQUESTED** [review]
Was `GetHLSSubscriber` part of the interface in order to help test it? The test seemed good, so is there a reason we shouldn't keep it?

**Comment by ericxtang** [comment]
`GetHLSSubscriber` looks a little strange in the interface anyways IMO - it feels more like an internal method.  The cache should be in charge of getting data.  Golang unit tests don't need a method to be in the interface to test it, and we currently don't have any tests that depend on `GetHLSSubscriber`.

File: core/videocache_test.go [hunk 1]
```diff
@@ -43,30 +43,7 @@ func TestEvictMasterPlaylist(t *testing.T) {
 	}
 }
 
-func TestGetHLSSubscriber(t *testing.T) {
```
Comment (j0sh) [inline core/videocache_test.go:46]: This tests GetHLSSubscriber and it got removed

Comment (ericxtang) [reply core/videocache_test.go:46]: Good point.  Added back in.

**Review by j0sh — APPROVED** [review]
