### PR TITLE
Use JSON config file to specify renditions

### LINKED ISSUE #1271: B should refuse to start if invalid value provided via `-transcodingOptions`
**Describe the bug**
If invalid value provided throw `-transcodingOptions` B silently ignores that and successfully starts with empty list of profiles to transcode.

**To Reproduce**
1. Run B providing random string in `-transcodingOptions`
2. B starts with zero profiles to transcode

**Expected behaviour**
Should fail to start with error message.

### PR DESCRIPTION
**Pull request by j0sh**
**TODO**

- [x] Documentation updates.
- [x] Manual testing with existing workflows - have only tested with the pull prototype
- [x] Limited set of integration tests [here](https://gist.github.com/j0sh/9d884a19bb92e504092e71fd19d812e5#file-run-sh)

**What does this pull request do? Explain your changes. (required)**

Currently, only pre-defined presets can be selected via CLI flags. These presets expose a limited subset of the configuration available to the user. In order to to access all the configuration options, the user needs to run a separate webhook service. While webhooks are extremely useful in a distributed, scaled environment, they are unwieldy for local  use of the node.

This PR enables the ability to configure the output presets via JSON file. The existing `-transcodingOptions` flag is overloaded as follows:

* If the `-transcodingOptions` flag is not set, nothing happens (default presets are used). Matches current behavior. 
* Attempts to read a file based on the value of `-transcodingOptions`.
* If reading the file succeeds, parses and processes the JSON.
* If there is an error reading the file, attempts to parse the preset string. Matches current behavior.
* If no profile is successfully read, fails. This is new behavior.

The existing JSON definition from the webhook is reused. This was the fastest way to get things working. The only thing worse than JSON for configuration is YAML. 🙈  We can always add better format support later.

**Specific updates (required)**

- Moves transcodingOptions processing to `NewLivepeerServer` from `StartMediaServer`. This is a bit neater and makes later work easier ([pull mode](https://github.com/livepeer/go-livepeer/compare/ja/pull) does not start the media server but still needs to initialize a livepeer server)
- Moves JSON-to-VideoProfile parsing into its own helper function.
- Invokes the helper function within `NewLivepeerServer`, in addition to the webhook handler.
- Tightens up error handling around invalid encoding profiles
- Adds test coverage
- Updates documentation, including the addition of a page on transcoding configuration

**How did you test each of these updates (required)**

Tons of unit tests. Most of the changes here are unit tests.

Manually tested as part of the pull mode work.

Regression tests. This also goes through earlier tests which exercises webhook components, which ensures the existing functionality remains unchanged. https://gist.github.com/j0sh/9d884a19bb92e504092e71fd19d812e5/revisions#diff-1b0c2b516b83393edb7200ad5ff12181

**Does this pull request close any open issues?**

Fixes https://github.com/livepeer/go-livepeer/issues/1271

**Checklist:**

- [x] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

**Comment by j0sh** [comment]
Ready for review.

File: common/util_test.go [hunk 1]
```diff
@@ -201,6 +201,22 @@ func TestVideoProfile_FormatExtension(t *testing.T) {
 		t.Error("Did not get expected error")
 	}
 }
+
+func TestVideoProfile_ProfileNameToValue(t *testing.T) {
+	assert := assert.New(t)
+	inp := []string{"", "h264baseline", "h264main", "h264high", "h264constrainedhigh"}
```
Comment (yondonfu) [inline common/util_test.go:207]: Missing "none" which is included in the `EncoderProfileLookup` map in `EncoderProfileNameToValue()`?

File: doc/rtmpwebhookauth.md [hunk 2]
```diff
@@ -10,9 +12,9 @@ For example:
 livepeer -authWebhookUrl http://ownserver/auth
 ```
 
-For each incoming RTMP stream, the Livepeer node will make a `POST` request to the `http://ownserver/auth` endpoint, passing the URL of the RTMP request as JSON object.
+For each incoming stream, the Livepeer node will make a `POST` request to the `http://ownserver/auth` endpoint, passing the URL of the RTMP request as JSON object.
```
Comment (yondonfu) [inline doc/rtmpwebhookauth.md]: "passing the URL of the RTMP request" -> "passing the URL of the request"?

File: doc/transcodingoptions.md [hunk 3]
```diff
@@ -0,0 +1,157 @@
...
+
+ If the aspect ratio of the source video does not match the target aspect ratio, the output is fit to the larger dimension, and the smaller dimension is rescaled proportionately to maintain the source aspect ratio.
+
+If a different behavior is needed, please [let us know](https://github.com/livepeer/go-livepeer/issues/new?template=feature_request.md) by filing a feature request.
+
+### Webhook Authentication
+
+See the [webhook documentation](rtmpwebhookauth.md) for details. To configure the transcoding output, either the `profiles` or `presets` fields in the webhook response can be set, or both.
+
+.se  The `profiles` field in the webhook follows the JSON options that are described in this document, The valid `preset` names follows as described.
```
Comment (yondonfu) [inline doc/transcodingoptions.md]: Extraneous ".se"?

File: server/mediaserver.go [hunk 4]
```diff
@@ -312,6 +304,49 @@ func authenticateStream(url string) (*authWebhookResponse, error) {
...
+				profile.Height,
+				profile.Bitrate)
+		}
+		var gop time.Duration
+		if profile.GOP != "" {
+			if profile.GOP == "intra" {
+				gop = ffmpeg.GOPIntraOnly
+			} else {
+				gopFloat, err := strconv.ParseFloat(profile.GOP, 64)
+				if err != nil || gopFloat <= 0.0 {
```
Comment (yondonfu) [inline server/mediaserver.go]: Looks like we can avoid the nested error check here with something like:

```
if err != nil {
    return nil, err
}

if gopFloat <= 0.0 {
    return nil, errors.New("invalid gop value")
}
```

**Review by yondonfu — CHANGES_REQUESTED** [review]
Docs look great! Just a few small comments.

**Comment by darkdarkdragon** [comment]
Agreed with Yondon's comments, otherwise looks good.

Small note - this one fixes #1271 😄

File: server/mediaserver.go (hunk 4 above)
Comment (j0sh) [reply server/mediaserver.go]: Fixed in 4b17b6ca9b4e86f1e4c5d5648be235e0580fafc6

File: common/util_test.go (hunk 1 above)
Comment (j0sh) [reply common/util_test.go:207]: Fixed by adding a separate check in 4b17b6ca9b4e86f1e4c5d5648be235e0580fafc6 . Note that we can't add a new element to that list, since it matches exactly the number of profiles we have (it's intended to trigger a failure if we ever add a new profile to LPMS without corresponding support in go-livepeer)

File: doc/rtmpwebhookauth.md (hunk 2 above)
Comment (j0sh) [reply doc/rtmpwebhookauth.md]: Fixed in bf686d88df7a7bc34da1baca46351a730d83fa37 , and a number of other usages of "RTMP" that were also missed.

File: doc/transcodingoptions.md (hunk 3 above)
Comment (j0sh) [reply doc/transcodingoptions.md]: Yeah that whole line is nonsense. Fixed in bf686d88df7a7bc34da1baca46351a730d83fa37

**Review by yondonfu — APPROVED** [review]
LGTM!

**Review by darkdarkdragon — APPROVED** [review]
LGTM
