### PR TITLE
common: Get gpus using pci info if gpu.GrahpicsCards is empty

### LINKED ISSUE #2339: -nvidia all flag fails on VM
**Describe the bug**
On a rented google VM the `-nvidia all` flag throws an error, however, when the card slot is specified `-nvidia 0` the program launches correctly.

**Spec**
 - OS: Debian GNU/Linux 10
 - Release: 10
 - Google Rented VM
 - GPU: Tesla T4
 - Livepeer Version: v0.5.29 - linux-amd64
 

**Screenshots**
With `-nvidia all` flag set.
error

Nvidia smi
nvidia-smi

Operating system
debain

### PR DESCRIPTION
**Pull request by red-0ne**
**What does this pull request do? Explain your changes. (required)**
Fix `-nvidia all` flag not detecting GPUs.
On VMs `ghw.GPU()` does return an empty array. We try to fallback to `ghw.PCI()` by picking only graphics cards. `pci.Device.Name`, `pci.Driver` and `pci.Device.Class.Name` are queried to detect display controller PCI devices

**Specific updates (required)**
- Check `pci.Device.Name`, `pci.Driver` and `pci.Device.Class.Name` if `gpu.GraphicsCards` is empty

**How did you test each of these updates (required)**
- Launch a GCP VM instance that has an Nvidia GPU
- run `./livepeer -orchestrator -transcoder -network offchain -nvidia all`
- Observe that GPUs are identified

**Does this pull request close any open issues?**
Fixes #2339

**Checklist:**
- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [ ] ~~README and other documentation updated~~
- [x] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

File: common/util.go [hunk 1]
```diff
@@ -441,18 +441,38 @@ func ReadAtMost(r io.Reader, n int) ([]byte, error) {
 }
 
 func detectNvidiaDevices() ([]string, error) {
+	nvidiaCardCount := 0
```
Comment (leszko) [inline common/util.go:469]: nit: Why did you move this code up?

**Review by leszko — APPROVED** [review]
Looks good from my end, but added also @AlexKordic, so we also have some thoughts from the network-video team.

File: common/util.go (hunk 1 above)
Comment (red-0ne) [reply common/util.go:469]: Since `nvidiaCardCount` and `re` are used in both code branchings I preferred to take it out of the `GPU` path to highlight the shared usage. It may also be after `ghw.GPU()` so we allocate resources only if the later does not return an error.

**Review by AlexKordic — APPROVED** [review]
LGTM!

**Comment by AlexKordic** [comment]
@red-0ne did you get the chance to test on GCP with multiple gpus?

**Comment by red-0ne** [comment]
> @red-0ne did you get the chance to test on GCP with multiple gpus?

I only tested with one GPU. I will test with an instance that has more GPUs

**Comment by red-0ne** [comment]
> @red-0ne did you get the chance to test on GCP with multiple gpus?

Launched a 4 gpus instance, seems that they are detected correctly.
```
./livepeer -orchestrator -transcoder -network offchain -nvidia all
I0526 21:34:32.417592    6009 starter.go:317] ***Livepeer is running on the offchain network***
I0526 21:34:32.417731    6009 starter.go:334] Creating data dir: /home/redouane/.lpData/offchain
WARNING: 
/sys/class/drm does not exist on this system (likely the host system is a
virtual machine or container with no graphics). Therefore,
GPUInfo.GraphicsCards will be an empty array.
I0526 21:34:32.483523    6009 starter.go:378] Nvidia devices: [0 1 2 3]
I0526 21:34:32.483619    6009 starter.go:382] Transcoding on these Nvidia devices: [0 1 2 3]
I0526 21:34:41.903177    6009 transcoder.go:279] optional capability "H264 Decode YUV444 8-bit" is not supported on device 0, set verbosity level to see more details
I0526 21:34:41.905162    6009 transcoder.go:279] optional capability "H264 Decode YUV422 8-bit" is not supported on device 0, set verbosity level to see more details
I0526 21:34:41.907015    6009 transcoder.go:279] optional capability "H264 Decode YUV444 10-bit" is not supported on device 0, set verbosity level to see more details
I0526 21:34:41.909081    6009 transcoder.go:279] optional capability "H264 Decode YUV422 10-bit" is not supported on device 0, set verbosity level to see more details
I0526 21:34:41.910973    6009 transcoder.go:279] optional capability "H264 Decode YUV420 10-bit" is not supported on device 0, set verbosity level to see more details
I0526 21:34:41.911938    6009 starter.go:461] ***Livepeer is in off-chain mode***
I0526 21:34:42.200090    6009 starter.go:1113] ***Livepeer Running in Orchestrator Mode***
I0526 21:34:42.200282    6009 cert.go:83] Private key and cert not found. Generating
I0526 21:34:42.200525    6009 cert.go:22] Generating cert for 34.78.85.181
I0526 21:34:42.200970    6009 rpc.go:197] Listening for RPC on :8935
I0526 21:34:42.201384    6009 webserver.go:24] CLI server listening on 127.0.0.1:7935
I0526 21:34:47.200602    6009 starter.go:1094] Orchestrator not available at https://34.78.85.181:8935; shutting down
I0526 21:34:47.200826    6009 starter.go:1135] Orchestrator server shut down
```

File: common/stub.go [hunk 2]
```diff
@@ -0,0 +1,19 @@
+package common
+
+import (
+	"github.com/jaypipes/ghw/pkg/gpu"
+	"github.com/jaypipes/ghw/pkg/pci"
+)
+
+type StubHardware struct {
```
Comment (leszko) [inline common/stub.go]: 1. If this stub is used only in `util_test.go`, could you move it to `util_test.go`? No need to create a separate go file.
2. The other thing is that you may not need this stub at all. Instead of having this stub, how about assigning the function directly, like this one?

```go
	// Test available GPU cards
	gpus := []*gpu.GraphicsCard{}
	for i := 0; i < 3; i++ {
		gpus = append(gpus, &gpu.GraphicsCard{
			DeviceInfo: &ghw.PCIDevice{
				Vendor: &pcidb.Vendor{
					Name: "--Nvidia Corp",
				},
			},
		})
	}

	GetGPU = func() ([]*gpu.GraphicsCard, error) {
		return gpus, nil
	}
```

File: common/util.go [hunk 3]
```diff
@@ -440,19 +442,62 @@ func ReadAtMost(r io.Reader, n int) ([]byte, error) {
...
+	pci, err := ghw.PCI()
+
+	if err != nil {
+		return nil, err
+	}
+
+	return pci.ListDevices(), nil
+}
+
+var GetGPU = getGPU
```
Comment (leszko) [inline common/util.go]: Could you make these variables package-private if they are used only for tests? Meaning, make the first letter lowercase. Like this.

```go
var getGpu = getGpuDefault
var getCpu = getCpuDefault
```

File: common/util_test.go [hunk 4]
```diff
@@ -348,3 +352,99 @@ func TestRatPriceInfo(t *testing.T) {
 	assert.Nil(err)
 	assert.Zero(priceInfo.Cmp(big.NewRat(7, 2)))
 }
+
+func TestParseAccelDevices(t *testing.T) {
```
Comment (leszko) [inline common/util_test.go]: How about creating 4 separate test functions (instead of aggregating 4 tests in one test function)? You could have something like this one.

```go
func TestParseAccessDevices_Gpu(t *testing.T) { ... }
func TestParseAccessDevices_GpuWrongDriver(t *testing.T) { ... }
func TestParseAccessDevices_GpuFailedProbing(t *testing.T) { ... }
func TestParseAccessDevices_FailedDetection(t *testing.T) { ... }
```

**Review by leszko — APPROVED** [review]
