### PR TITLE
server: fix EthChainID webserver endpoint in offchain mode to return 'offchain' instead of '0'

### LINKED ISSUE #1378: livepeer_cli runtime error
**Describe the bug**

`livepeer_cli` having issues on dev. Manually setting `w.offchain = true` in `func (w *wizard) checkNet() {}` fixes the issue temporarily.

**To Reproduce**

1. Run `./livepeer -datadir $HOME/lp-data-1 -broadcaster -transcodingOptions P144p30fps16x9,P576p30fps16x9 -orchAddr localhost:1998 -authWebhookUrl http://localhost:3004/api/stream/hook`
2. Run `./livepeer -datadir $HOME/lp-data-2 -orchestrator -transcoder -cliAddr localhost:1999 -serviceAddr localhost:1998`
3. Run `./livepeer_cli -http 7935`
4. See error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x47fa97e]

goroutine 1 [running]:
math/big.(*Int).Int64(...)
	/usr/local/go/src/math/big/int.go:372
main.(*wizard).delegatorStats(0xc0000f1ec0)
	/Users/angie/git/go-livepeer/cmd/livepeer_cli/wizard_stats.go:228 +0x8e
main.(*wizard).stats(0xc0000f1ec0, 0xc0000d0000)
	/Users/angie/git/go-livepeer/cmd/livepeer_cli/wizard_stats.go:78 +0xb3c
main.(*wizard).run(0xc0000f1ec0)
	/Users/angie/git/go-livepeer/cmd/livepeer_cli/livepeer_cli.go:146 +0x3ce
main.main.func1(0xc000328000, 0xc000328000, 0xc000557ac7)
	/Users/angie/git/go-livepeer/cmd/livepeer_cli/livepeer_cli.go:56 +0x551
github.com/urfave/cli.HandleAction(0x50ba080, 0x528dcf0, 0xc000328000, 0xc000312ba0, 0x0)
	/Users/angie/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.(*App).Run(0xc0002bc820, 0xc0000ba180, 0x3, 0x3, 0x0, 0x0)
	/Users/angie/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:264 +0x58c
main.main()
	/Users/angie/git/go-livepeer/cmd/livepeer_cli/livepeer_cli.go:62 +0x32b
```

**Expected behavior**
An interactive livepeer_cli 

**Desktop (please complete the following information):**
Terminal

**Additional Notes**
(From @j0sh ) Looking at delegatorStats (the function where it's crashing) there is indeed an offchain check, so whatever w.offchain is, it's not being set correctly.  Yep - looks like the EthChainID just writes a "0" for offchain when it should be "offchain". Either that or the checkNet function needs to be updated to check for  nID == "0"

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**
Fixes a bug whereby the `EthChainID` webserver handler returns "0" when offchain , but the actual check compares against the string literal "offchain" 

https://github.com/livepeer/go-livepeer/blob/c4a3004f8318220b42eacea33d392049cb7fa188/server/webserver.go#L1077

https://github.com/livepeer/go-livepeer/blob/c4a3004f8318220b42eacea33d392049cb7fa188/cmd/livepeer_cli/livepeer_cli.go#L173

**Specific updates (required)**
- write "offchain" to the http response in offchain mode
- add unit test for on-chain mode

**How did you test each of these updates (required)**
adjusted & ran unit tests
ran reproduction steps in CLI (run in offchain mode, then run CLI)

**Does this pull request close any open issues?**
Fixes #1378 

**Checklist:**
- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

File: server/webserver.go [hunk 1]
```diff
@@ -1074,19 +1074,15 @@ func (s *LivepeerServer) cliWebServerHandlers(bindAddr string) *http.ServeMux {
 
 	mux.HandleFunc("/EthChainID", func(w http.ResponseWriter, r *http.Request) {
 		if s.LivepeerNode.Eth == nil {
-			w.Write([]byte("0"))
+			w.Write([]byte("offchain"))
```
Comment (yondonfu) [inline server/webserver.go]: Since the other return values for this handler are chain ID integers and we already use [0 as the chain ID](https://github.com/livepeer/go-livepeer/blob/c4a3004f8318220b42eacea33d392049cb7fa188/cmd/livepeer/livepeer.go#L306) in off-chain mode, WDYT about still returning 0 here for consistent return types from the handler and changing [checkNet()](https://github.com/livepeer/go-livepeer/blob/dacb1cb745503e730f9b342c2ad6e0079a03b1ab/cmd/livepeer_cli/livepeer_cli.go#L176) to check for 0?

Comment (kyriediculous) [reply server/webserver.go]: fixed in 78d85ab

**Review by yondonfu — COMMENTED** [review]
Changes look good - let's rebase

**Comment by kyriediculous** [comment]
rebased !

**Review by yondonfu — APPROVED** [review]
LGTM 🚢
