### PR TITLE
eth: discard gas prices below minGasPrice

### LINKED ISSUE #1851: Many insufficient faceValue ticket face value for redeem tx cost errors
**Describe the bug**

There has been an uptick in "insufficient faceValue ticket face value..." errors reported by Os.

The current hypothesis is that the Os are receiving gas prices from their JSON-RPC provider that are really low or even 0 in certain cases and as a result, the computed face value end up being [less than the ticket EV](https://github.com/livepeer/go-livepeer/blob/7a0fd1f6b958d61177fc01c488972f54b8bad1e3/pm/recipient.go#L237) resulting in the face value to be set to the ticket EV. Since the ticket EV is 1000 gwei, in pretty much all cases the face value will be less than the tx cost for redeeming a winning ticket.

See this [tweet thread](https://twitter.com/YondonFu/status/1386693693088964609) for some resources to support the hypothesis that Os are receiving really low gas prices from their JSON-RPC provider at least for brief periods of time.

The negative consequences of this issue are:

- Os receive many winning tickets, but none of them are redeemed
- Os end up with a ton of logs with the aforementioned error
- Any tickets that should be redeemed are stuck behind these low face value tickets in the queue

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**
Adds a minGasPrice to the gas price monitor and discards fetched gas prices below it 

Sets a specific setting for mainnet 

**How did you test each of these updates (required)**
Unit tests

**Does this pull request close any open issues?**
Fixes #1851 

**Checklist:**
- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [x] README and other documentation updated
- [x] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

File: cmd/livepeer/livepeer.go [hunk 1]
```diff
@@ -202,6 +203,7 @@ func main() {
 		},
 		"mainnet": {
 			ethController: "0xf96d54e490317c557a967abfa5d6e33006be69b3",
+			minGasPrice:   big.NewInt(1e9),
```
Comment (yondonfu) [inline cmd/livepeer/livepeer.go]: Should we use [params.GWei](https://github.com/ethereum/go-ethereum/blob/d8ff53dfb8a516f47db37dbc7fd7ad18a1e8a125/params/denomination.go#L26)?

File: eth/gaspricemonitor.go [hunk 2]
```diff
@@ -32,18 +32,25 @@ type GasPriceMonitor struct {
...
 
 	// update is a channel used to send notifications to a listener
 	// when the gas price is updated
 	update chan struct{}
 }
 
 // NewGasPriceMonitor returns a GasPriceMonitor
-func NewGasPriceMonitor(gpo GasPriceOracle, pollingInterval time.Duration) *GasPriceMonitor {
+func NewGasPriceMonitor(gpo GasPriceOracle, pollingInterval time.Duration, minGasPrice *big.Int) *GasPriceMonitor {
+	minGasP := big.NewInt(0)
```
Comment (yondonfu) [inline eth/gaspricemonitor.go:45]: Don't think we need this as the minGasPrice param value is not from an untrusted source (unlike in other cases where we should be more defensive since an untrusted source could give us unexpected values) and the caller is responsible for passing in a sane value.

File: eth/gaspricemonitor_test.go [hunk 3]
```diff
@@ -131,14 +132,21 @@ func TestStart_Polling(t *testing.T) {
 	// There should be more queries now
 	assert.Greater(gpo.Queries(), queries)
 	assert.Equal(gasPrice3, gpm.GasPrice())
+
+	go func() {
+		gpo.SetGasPrice(gasPrice4)
+	}()
+	time.Sleep(100 * time.Millisecond)
+	assert.Greater(gpo.Queries(), queries)
```
Comment (yondonfu) [inline eth/gaspricemonitor_test.go:142]: I think we want to update `queries` with `queries = gpo.Queries()` before L136 in order to take a snapshot of the # of queries before and after the sleep to ensure that an additional query was ran during the sleep and after the goroutine executed.

**Review by yondonfu — CHANGES_REQUESTED** [review]
Overall LGTM. Just a few minor comments. After those are addressed and a changelog entry is added should be good to go.

File: eth/gaspricemonitor.go (hunk 2 above)
Comment (kyriediculous) [reply eth/gaspricemonitor.go:45]: I disagree, I don't think it's correct to assume that a caller will pass in sane values, ever.  It's not because we pass in a sane value that a third party potentially using this package will. Passing in a `nil` value will lead to unexpected behaviour under the form of a panic so we do need this.

File: cmd/livepeer/livepeer.go (hunk 1 above)
Comment (kyriediculous) [reply cmd/livepeer/livepeer.go]: It seems like the compiler looks at `int64(params.GWei)` as a constant still rather than a variable that needs to convert the untyped constant to an int64 at runtime so I'm okay with this.

File: eth/gaspricemonitor.go (hunk 2 above)
Comment (yondonfu) [reply eth/gaspricemonitor.go:45]: Upon further thought, I agree with your point here 👍 .

**Comment by yondonfu** [comment]
Good to go after a changelog entry.

**Comment by kyriediculous** [comment]
added changelog entry and rebased

**Review by yondonfu — APPROVED** [review]
LGTM!
