### PR TITLE
Self check related changes.

### LINKED ISSUE #600: Orchestrator doesn't start
**Describe the bug**
Orchestrator, at start, fails to pass `CheckTranscoderAvailability` check and exits.

**To Reproduce**
Try to run orchestrator.

**Additional context**
here
https://github.com/livepeer/go-livepeer/blob/3a435f5e8c3a8a0b2dcfa366587d2127a04d7907/server/rpc.go#L120-L122
connection gets closed right after being open

also this function doesn't work as expected - it fails at `verifyMsgSig`
https://github.com/livepeer/go-livepeer/blob/3a435f5e8c3a8a0b2dcfa366587d2127a04d7907/server/rpc.go#L76-L100

### PR DESCRIPTION
**Pull request by j0sh**
* Fix verification param transposition. This wasn't caught by unit testing because of a typo in the test name.
* Use manually specified ServiceURI if not set. Not strictly necessary at the moment, but useful for quick testing. Will become necessary for offchain mode. Perhaps we should also rename this to "orchAddr" following the O/T split.
* rpc: Return the underlying orchestrator connection so we don't close the cxn immediately after creating it.

Fixes https://github.com/livepeer/go-livepeer/issues/600

### CODE REVIEW

**Review by darkdarkdragon — APPROVED** [review]
LGTM

File: server/rpc_test.go [hunk 1]
```diff
@@ -292,7 +292,7 @@ func TestRPCSeg(t *testing.T) {
 	}
 }
 
-func testPing(t *testing.T) {
+func TestPing(t *testing.T) {
```
Comment (angyangie) [inline server/rpc_test.go:295]: Didn't realize this had to be capitalized. Noted!

File: server/rpc.go [hunk 2]
```diff
@@ -82,10 +82,11 @@ func CheckTranscoderAvailability(orch Orchestrator) bool {
 
 	ping := crypto.Keccak256(ts_signature)
 
-	orch_client, err := startOrchestratorClient(orch.ServiceURI().String())
+	orch_client, conn, err := startOrchestratorClient(orch.ServiceURI().String())
 	if err != nil {
 		return false
 	}
+	defer conn.Close()
```
Comment (angyangie) [inline server/rpc.go:89]: I see. We want the orchestrator connection to close after this function exits .... i.e. once we've checked that the orchestrator ("transcoder") is available. Noted!

File: server/rpc.go [hunk 3]
```diff
@@ -96,15 +97,15 @@ func CheckTranscoderAvailability(orch Orchestrator) bool {
 		return false
 	}
 
-	return verifyMsgSig(orch.Address(), string(pong.Value), ping)
+	return verifyMsgSig(orch.Address(), string(ping), pong.Value)
```
Comment (angyangie) [inline server/rpc.go:100]: `Sig` is the return value. `Msg` is the input ping value. Noted!

**Review by angyangie — APPROVED** [review]
Thanks for handling this @j0sh !
