### PR TITLE
Fix ServiceURI Reset Bug

### LINKED ISSUE #691: Transcoding Result Contains Incorrect URL
**Describe the bug**
The transcoding result contains incorrect URL when using a newly registered O. This seems to be because the OS.SaveData in `rpc.go->ServeSegment` is giving back the old URI.

**To Reproduce**
1. Start a new O.
2. Register the O onchain (make sure it's the only O)
3. Start streaming to B
4. You'll see errors described below
5. Stop Stream, restart O
6. The error goes away.

**Expected behavior**
O should automatically update the ServiceURI with the new URI without needed a restart.

**Screenshots**
```
E0117 21:24:22.813874       1 player.go:163] Error getting segment /stream/85eb7484/P240p30fps16x9/0.ts: ErrNotFound
E0117 21:24:22.813901       1 player.go:163] Error getting segment /stream/85eb7484/P360p30fps16x9/0.ts: ErrNotFound
E0117 21:24:22.814074       1 drivers.go:75] Non-200 response 500 Internal Server Error
E0117 21:24:22.814102       1 broadcast.go:158] Download error with segment 0: 500 Internal Server Error (URL: http://127.0.0.1:8935/stream/85eb7484/P360p30fps16x9/0.ts)
E0117 21:24:22.814150       1 drivers.go:75] Non-200 response 500 Internal Server Error
E0117 21:24:22.814179       1 broadcast.go:158] Download error with segment 0: 500 Internal Server Error (URL: http://127.0.0.1:8935/stream/85eb7484/P240p30fps16x9/0.ts)
I0117 21:24:24.166130       1 rpc.go:530] Submitting segment 1 : 567008 bytes
I0117 21:24:24.179402       1 rpc.go:553] Uploaded segment 1
```

### PR DESCRIPTION
**Pull request by ericxtang**
**What does this pull request do? Explain your changes. (required)**

`baseURI` is not updated in the memory driver because it's set at startup time.  So we now change it to a pointer, so it'll always load the latest ServiceURI value.  Thanks to @angyangie for pairing with me on this.

**Specific updates (required)**

- Update `baseURI` to a pointer
- Create getters and setters to `ServiceURI` so when it's updated, we set the value instead of the pointer value
- Add a test

**How did you test each of these updates (required)**

With `TestServiceURIChange`

**Does this pull request close any open issues?**

Closes https://github.com/livepeer/go-livepeer/issues/691

**Checklist:**

- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

**Review by angyangie — APPROVED** [review]
Thanks for taking me on this bug hunting journey with you @ericxtang ! I learned a lot

File: drivers/local.go [hunk 1]
```diff
@@ -124,8 +124,8 @@ func (ostore *MemorySession) getAbsolutePath(name string) string {
 
 func (ostore *MemorySession) getAbsoluteURI(name string) string {
 	name = "/stream/" + ostore.getAbsolutePath(name)
-	if ostore.os.baseURI != "" {
-		return ostore.os.baseURI + name
+	if ostore.os.baseURI != nil {
+		return ostore.os.baseURI.String() + name
```
Comment (j0sh) [inline drivers/local.go:128]: Just a note that this won't be as "cheap" as it used to be, since serializing a string from a URL object does have a cost, see:  https://golang.org/src/net/url/url.go?s=21757:21786#L741 . Not a huge deal though as we don't call this function too often, just once per save.

**Review by j0sh — APPROVED** [review]
LGTM! 🚢

File: core/livepeernode_test.go [hunk 2]
```diff
@@ -91,3 +95,29 @@ func TestTranscodeAndBroadcast(t *testing.T) {
...
+	require.Nil(err)
+	assert.Equal("test://testurl.com/stream/testpath/testdata1", savedUrl)
+
+	glog.Infof("Setting service URL to newurl")
+	newUrl, err := url.Parse("test://newurl.com")
+	n.SetServiceURI(newUrl)
+	require.Nil(err)
+	url, err := sesh.SaveData("testdata2", []byte{0, 0, 0})
+	require.Nil(err)
+	assert.Equal("test://newurl.com/stream/testpath/testdata2", url)
```
Comment (darkdarkdragon) [inline core/livepeernode_test.go]: adding this 
```
	glog.Infof("Setting service URL to secondurl")
	secondUrl, err := url.Parse("test://secondurl.com")
	n.SetServiceURI(secondUrl)
	require.Nil(err)
	surl, err = sesh.SaveData("testdata3", []byte{0, 0, 0})
	require.Nil(err)
	assert.Equal("test://secondurl.com/stream/testpath/testdata3", surl)
```
to the end of test function will make it break

File: core/livepeernode.go [hunk 3]
```diff
@@ -125,3 +125,14 @@ func (n *LivepeerNode) StopEthServices() error {
...
+
+func (n *LivepeerNode) GetServiceURI() *url.URL {
+	return n.serviceURI
+}
+
+func (n *LivepeerNode) SetServiceURI(newUrl *url.URL) {
+	if newUrl != nil && n.serviceURI != nil {
+		*n.serviceURI = *newUrl
+	}
+	n.serviceURI = newUrl //for nil cases
```
Comment (darkdarkdragon) [inline core/livepeernode.go]: this should be in `else` branch - right now you're overwriting pointer and it breaks on second call to `SetServiceURI`.
I've added test case in comments.

**Review by darkdarkdragon — CHANGES_REQUESTED** [review]

File: core/livepeernode.go (hunk 3 above)
Comment (j0sh) [reply core/livepeernode.go]: Part of why this reads a bit strangely is because we're both 1) setting a possibly-nil pointer, and 2) setting the contents of that pointer. Both are done under different conditions.

If we can remove the first case then the function becomes much more straightforward. We can do this by storing the `LivepeerNode.serviceURI` as a value rather than a pointer. Eg,

```
type LivepeerNode struct {
   ...
	// Transcoder private fields
	serviceURI      url.URL // not a pointer
   ...
}

func (n *LivepeerNode) SetServiceURI(newUrl *url.URL) {
    // Is there anything here we need to be concerned about deep copying?
    // Most of the fields are straightforward but there's the UserInfo pointer
    // which I'm unsure about: https://golang.org/pkg/net/url/#URL
    n.serviceURI = *newURL
}
func (n *LivepeerNode) GetServiceURI() *url.URL {
    return &n.serviceURI
}
```

We might even be able to get rid of the accessor functions that way, but keeping them in is fine too.

Also, if we accept that the ServiceURI can be (re-)set at any time (and I suppose there's no reason it can't) then the race detector will probably complain that accesses to `n.serviceURI` are not protected, since the node may be transcoding at the moment that the service URI is set. Properly fixing that is more trouble than it's worth at this point though.

Comment (darkdarkdragon) [reply core/livepeernode.go]: > Part of why this reads a bit strangely is because we're both 1) setting a possibly-nil pointer, and 2) setting the contents of that pointer. Both are done under different conditions.

3) it is always overwriting pointer. So we are not achieving goal of `so it'll always load the latest ServiceURI value`- because on second invocation of `SetServiceURI` we're not setting content of `baseURI` - `LivepeerNode` doesn't have that pointer anymore. 
And we can't just simply set `serviceURI` to be value instead of pointer - `MemoryDriver` still need a way to check if it's empty.

Probably ideal solution here will be 
```golang
	if newUrl != nil && n.serviceURI != nil {
		*n.serviceURI = *newUrl
	} else if n.serviceURI == nil && newUrl != nil {
		n.serviceURI = &url.URL{}
		*n.serviceURI = *newUrl
	}
```

Comment (j0sh) [reply core/livepeernode.go]: > And we can't just simply set serviceURI to be value instead of pointer - MemoryDriver still need a way to check if it's empty.

The MemoryDriver only needs to check that the ServiceURI is non-nil here (which this PR does in `getAbsoluteURI`). Calling `.String()` on an empty URL yields the empty string which is fine.

Storing a value rather than a pointer should still work, unless I'm missing something else.

Comment (darkdarkdragon) [reply core/livepeernode.go]: If `.String()` returns empty string for empty `URL` structure then storing value is a way to go

**Review by j0sh — APPROVED** [review]

**Review by darkdarkdragon — APPROVED** [review]
LGTM
