### PR TITLE
Fix nil pointer in the block header logs

### LINKED ISSUE #2265: Nil Pointer in watchers while running in Arbitrum
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x7ff75be2a3d5]

goroutine 32836 [running]:
github.com/livepeer/go-livepeer/eth/watchers.(*SenderWatcher).handleBlockEvents(0xc002c89fd0, {0xc000882100, 0x1c, 0x0})
        D:/a/go-livepeer/go-livepeer/eth/watchers/senderwatcher.go:152 +0x55
created by github.com/livepeer/go-livepeer/eth/watchers.(*SenderWatcher).Watch
        D:/a/go-livepeer/go-livepeer/eth/watchers/senderwatcher.go:116 +0x385
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x7ff75be2c595]

goroutine 33 [running]:
github.com/livepeer/go-livepeer/eth/watchers.(*ServiceRegistryWatcher).handleBlockEvents(0xc000283f80, {0xc000882100, 0x1c, 0x0})
        D:/a/go-livepeer/go-livepeer/eth/watchers/serviceRegistryWatcher.go:61 +0x55
github.com/livepeer/go-livepeer/eth/watchers.(*ServiceRegistryWatcher).Watch(0xc000211e80)
        D:/a/go-livepeer/go-livepeer/eth/watchers/serviceRegistryWatcher.go:49 +0x20a
created by main.main
        D:/a/go-livepeer/go-livepeer/cmd/livepeer/livepeer.go:587 +0x43f8
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x58 pc=0x7ff75be2f355]

goroutine 32748 [running]:
github.com/livepeer/go-livepeer/eth/watchers.(*UnbondingWatcher).handleBlockEvents(0xc002c8ffd0, {0xc000882100, 0x1c, 0x0})
        D:/a/go-livepeer/go-livepeer/eth/watchers/unbondingwatcher.go:74 +0x55
created by github.com/livepeer/go-livepeer/eth/watchers.(*UnbondingWatcher).Watch
        D:/a/go-livepeer/go-livepeer/eth/watchers/unbondingwatcher.go:62 +0x2af
```

### PR DESCRIPTION
**Pull request by leszko**
**What does this pull request do? Explain your changes. (required)**
Fixes a bug introduced in https://github.com/livepeer/go-livepeer/pull/2222, block header logs were not preserved while enriching block with L1 Number.

**Specific updates (required)**

- 
- 
- 

**How did you test each of these updates (required)**

Unit test + checked in the debug that events returned from L2 API may not contain logs.

**Does this pull request close any open issues?**

fix #2265

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [ ] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

File: eth/blockwatch/block_watcher.go [hunk 1]
```diff
@@ -637,7 +637,12 @@ func (w *Watcher) enrichWithL1BlockNumber(header *MiniHeader) (*MiniHeader, erro
 	if header == nil || header.L1BlockNumber != nil {
 		return header, nil
 	}
-	return w.client.HeaderByHash(header.Hash)
+	fetchedBlock, err := w.client.HeaderByHash(header.Hash)
+	if err != nil {
+		return header, err
+	}
+	header.L1BlockNumber = fetchedBlock.L1BlockNumber
```
Comment (yondonfu) [inline eth/blockwatch/block_watcher.go:644]: Ah so the problem was that if `header` contained logs that were previously added to it we could end up returning a MiniHeader returned by HeaderByHash that does not have those logs. And the fix here is to make sure we copy over the L1BlockNumber from the MiniHeader returned by HeaderByHash to the `header` that is passed in to ensure that if the `header` passed in contains logs that they are preserved?

**Review by yondonfu — APPROVED** [review]
LGTM - just one clarifying question

File: eth/blockwatch/block_watcher.go (hunk 1 above)
Comment (leszko) [reply eth/blockwatch/block_watcher.go:644]: Yes, exactly as you described. Before, I thought that what we get from the RPC call already include in logs, but apparently that's not the case.
