### PR TITLE
Rotating IPFS logs

### LINKED ISSUE #272: IPFS errors for a long running transcoder node
After leaving a transcoder node running for awhile we start seeing a bunch of IPFS errors:

```
E0117 21:26:37.881374   25732 peerCache.go:79] Error writing connection to file system
21:26:39.978 ERROR       mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:140
21:26:49.978 ERROR       mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:140
21:28:49.978 ERROR       mdns: mdns lookup error: failed to bind to any multicast udp port mdns.go:140
```

And

```
22:00:14.833 ERROR        dht: checking dht client type: context canceled notif.go:81
22:01:38.149 ERROR        dht: checking dht client type: context canceled notif.go:81
```

And

```
21:09:47.238 ERROR        dht: checking dht client type: connection reset notif.go:81
```

### PR DESCRIPTION
**Pull request by yondonfu**
Fixes #272 

```
22:00:14.833 ERROR        dht: checking dht client type: context canceled notif.go:81
21:09:47.238 ERROR        dht: checking dht client type: connection reset notif.go:81
```

The above two errors are caused by either a timeout or unsupported connection with a remote peer when using the IPFS DHT. They should really be warning logs. In a more recent version of IPFS they have been downgraded to warning logs and this PR does the same for our vendored IPFS codebase. I didn't update the entire vendored IPFS codebase to the latest version because that would have required updating libp2p dependencies for go-livepeer-basicnet as well - figured we could hold off on doing that since the fix for the error message was just a couple lines of code changes in the vendored IPFS codebase.

```
21:26:39.978 ERROR       mdns: mdns lookup error: failed to bind to any unicast udp port mdns.go:140
21:28:49.978 ERROR       mdns: mdns lookup error: failed to bind to any multicast udp port mdns.go:140
```

The above two errors are caused by IPFS trying to use mDNS to discover additional peers in a LAN. The mDNS service will keep polling trying to query for entries https://github.com/libp2p/go-libp2p/blob/master/p2p/discovery/mdns.go#L140. Apparently, mDNS is not supported in many networks including cloud or shared infrastructure environments (https://github.com/whyrusleeping/mdns). I'm guessing AWS falls in this category, which explains why we kept seeing the above two errors.

None of the error messages should affect the operation of the IPFS node.

Now, the default behavior is to pipe IPFS logs into rotating logs stored in `<ipfsRepoPath>/logs/ipfs.log`.

### CODE REVIEW

File: cmd/livepeer/livepeer.go [hunk 1]
```diff
@@ -98,6 +100,7 @@ func main() {
 	monitor := flag.Bool("monitor", true, "Set to true to send performance metrics")
 	monhost := flag.String("monitorhost", "http://viz.livepeer.org:8081/metrics", "host name for the metrics data collector")
 	ipfsPath := flag.String("ipfsPath", fmt.Sprintf("%v/.ipfs", usr.HomeDir), "IPFS path")
+	noLogFiles := flag.Bool("noLogFiles", false, "Set to true if log files should not be generated")
```
Comment (ericxtang) [inline cmd/livepeer/livepeer.go]: Does this affect all logs or just IPFS logs for now?

Comment (yondonfu) [reply cmd/livepeer/livepeer.go]: Just IPFS logs for now

Comment (ericxtang) [reply cmd/livepeer/livepeer.go]: Maybe rename the flag to "noIPFSLogFiles" for now?

**Review by ericxtang — APPROVED** [review]
🚢
