### PR TITLE
Retry event subscriptions and failed RPC calls with remote ETH node

### LINKED ISSUE #298: Retry logic for Eth client
Noticed that Infura sometimes drops connections.  We should build in some retry logic to account for for network failures.

### LINKED ISSUE #310: Timeout getting deposit from blockchain
Since we've switched to Infura, we've been getting this error periodically.

```
E0227 20:52:28.174652   28154 mediaserver.go:134] Error getting deposit: write tcp 172.31.2.189:54176->34.197.26.107:443: i/o timeout
```

For the short term, let's add retry logic.

### LINKED ISSUE #313: Event monitor EOF
Got this error on a transcoder that's been running for a while: 
```
E0228 00:29:06.602594   20717 eventmonitor.go:123] Error with log subscription: EOF
E0228 00:29:06.602614   20717 eventmonitor.go:139] Error with header callback: EOF
E0228 00:29:06.602634   20717 eventmonitor.go:123] Error with log subscription: EOF
```

I think it has to do with the websocket timing out / closing the connection.  We might need a retry mechanism.

### PR DESCRIPTION
**Pull request by yondonfu**
Closes #313 
Closes #310 
Closes #298 

Adds retry logic for event subscriptions in `eventmonitor.go` and retry logic for RPC calls in the vendored geth RPC client `rpc/client.go`

### CODE REVIEW

File: server/webserver.go [hunk 1]
```diff
@@ -805,19 +807,23 @@ func (s *LivepeerServer) StartWebserver() {
...
 	http.HandleFunc("/broadcasterDeposit", func(w http.ResponseWriter, r *http.Request) {
 		if s.LivepeerNode.Eth != nil {
 			b, err := s.LivepeerNode.Eth.BroadcasterDeposit(s.LivepeerNode.Eth.Account().Address)
 			if err != nil {
+				glog.Error(err)
 				w.Write([]byte(""))
+			} else {
+				w.Write([]byte(b.String()))
 			}
-			w.Write([]byte(b.String()))
```
Comment (yondonfu) [inline server/webserver.go:820]: If there was an error in the call before, the returned result would still be nil instead of the empty string

File: vendor/github.com/ethereum/go-ethereum/rpc/client.go [hunk 2]
```diff
@@ -421,7 +420,15 @@ func (c *Client) send(ctx context.Context, op *requestOp, msg interface{}) error
 		log.Trace("", "msg", log.Lazy{Fn: func() string {
 			return fmt.Sprint("sending ", msg)
 		}})
+
+		retries := 0
 		err := c.write(ctx, msg)
+		for err != nil && retries < failedWriteRetries {
```
Comment (yondonfu) [inline vendor/github.com/ethereum/go-ethereum/rpc/client.go:426]: If a call to `write` fails, `c.writeConn` will be set to nil. Then, on the next call the RPC client will retry to reestablish the connection https://github.com/livepeer/go-livepeer/blob/e67b8370df00d5f8bf8a05d16d81a2c8648c7866/vendor/github.com/ethereum/go-ethereum/rpc/client.go#L450

**Review by ericxtang — APPROVED** [review]
Looks like a good solution for now.  🚢 

Would be interesting to monitor all the failure cases from Infura.  There are "write errors" and "subscribe errors".  The "write errors" are easier to deal with - we just retry.  "subscribe error" are a little more difficult - we don't know what all the options are for `em.eventSubMap[subName].sub.Err()`.  Maybe we have missed some important event and should refetch the data.  Maybe we need to keep a counter and eventually quit trying to re-subscribe.

**Comment by yondonfu** [comment]
Right, there is still an edge case with subscription retries where a transcoder's new job subscription could end due to a closed websocket connection with Infura, a new job is created that is assigned to the transcoder and when the transcoder successfully resubscribes to new jobs it will have missed the new job that was just created. Tracking that here: https://github.com/livepeer/go-livepeer/issues/315
