### PR TITLE
Point ffmpeg to with fix for fast verification

### LINKED ISSUE #2175: fast verification panic: lpms_compare_sign_bybuffer
Got this after flipping on verification on secondary broadcasters - partial stack trace here: https://gist.github.com/iameli/ab0fc42f239eeff1253759444dcd590a

Important bit:
```
fatal error: unexpected signal during runtime execution
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:726 +0x4ac

goroutine 1327 [syscall]:
runtime.cgocall(0x1095490, 0xc002482ac8, 0x1)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5b fp=0xc002482a98 sp=0xc002482a60 pc=0x47f3db
github.com/livepeer/lpms/ffmpeg._Cfunc_lpms_compare_sign_bybuffer(0xc0001f2800, 0xc000000121, 0xc0002b3e00, 0x121, 0x0)
	_cgo_gotypes.go:283 +0x4d fp=0xc002482ac8 sp=0xc002482a98 pc=0xbe42ed
github.com/livepeer/lpms/ffmpeg.CompareSignatureByBuffer.func1(0xc0001f2800, 0xc0001f2800, 0x121, 0x200, 0xc0002b3e00, 0xc0002b3e00, 0x121, 0x200, 0x1e40078)
	/go/pkg/mod/github.com/livepeer/lpms@v0.0.0-20211208221036-644122186d24/ffmpeg/ffmpeg.go:152 +0x91 fp=0xc002482b00 sp=0xc002482ac8 pc=0xbe9371
github.com/livepeer/lpms/ffmpeg.CompareSignatureByBuffer(0xc0001f2800, 0x121, 0x200, 0xc0002b3e00, 0x121, 0x200, 0x200, 0x0, 0x0)
	/go/pkg/mod/github.com/livepeer/lpms@v0.0.0-20211208221036-644122186d24/ffmpeg/ffmpeg.go:152 +0x85 fp=0xc002482b58 sp=0xc002482b00 pc=0xbe4c25
github.com/livepeer/go-livepeer/server.(*BroadcastSessionsManager).chooseResults(0xc014204e40, 0x1e4eb60, 0xc01e228330, 0xc0135102a0, 0x3, 0xc0198632c0, 0xf84f6eb78f204b0c, 0xc019863201, 0xc0135102a0)
	/build/server/broadcast.go:506 +0x3e5 fp=0xc002482cd8 sp=0xc002482b58 pc=0x102e9a5
```

### PR DESCRIPTION
**Pull request by darkdarkdragon**
**What does this pull request do? Explain your changes. (required)**
Uses latest FFMpeg

**Specific updates (required)**
Changed install_ffmpeg.sh

**How did you test each of these updates (required)**
Unit test in LPMS repo

**Does this pull request close any open issues?**
Fixes #2175 

**Checklist:**

- [ ] Read the [contribution guide](./doc/contributing.md)
- [ ] `make` runs successfully
- [ ] All tests in `./test.sh` pass
- [ ] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

File: install_ffmpeg.sh [hunk 1]
```diff
@@ -76,8 +76,8 @@ if [ ! -e "$ROOT/x264" ]; then
 fi
 
 if [[ $(uname) == "Linux" && $BUILD_TAGS == *"debug-video"* ]]; then
+  sudo apt-get install -y libnuma-dev cmake
```
Comment (yondonfu) [inline install_ffmpeg.sh:79]: Is the reason for moving this install step up here because we need to make sure these deps are installed even if x265 is already installed i.e. if the conditional on L80 evaluates to false?

**Review by yondonfu — APPROVED** [review]
LGTM. Just one question.

File: install_ffmpeg.sh (hunk 1 above)
Comment (darkdarkdragon) [reply install_ffmpeg.sh:79]: Yes - in CircleCI we have x265 folder cached, so `libnuma` is not installed (that's also why other PRs in LPMS fails now)
