### PR TITLE
common, core: use fixed point PriceInfo

### LINKED ISSUE #1426: O reporting error processing payment: invalid recipientRand for ticket recipientRandHash
**Describe the bug**

When running a BOT network on Mainnet, the O is receiving the following error, and refusing to Transcode:
```
O reporting error processing payment: invalid recipientRand for ticket recipientRandHash
```

Full error logs from all processes enclosed below.

**To Reproduce**

Run the following:

1. O with
```
./livepeer-linux-amd64/livepeer -network mainnet -orchestrator -cliAddr 127.0.0.1:7935 -httpAddr 127.0.0.1:8935 -serviceAddr 127.0.0.1:8935 -pricePerUnit 2000000 -pixelsPerUnit 1 -ticketEV 1000000000000 -orchSecret secret -v 99
```
2. T with
```
./livepeer-linux-amd64/livepeer -network mainnet -transcoder -orchAddr 127.0.0.1:8935 -cliAddr 127.0.0.1:7937 -httpAddr 127.0.0.1:8937 -orchSecret secret -maxSessions 1 -v 99
```
3. B with
```
./livepeer-linux-amd64/livepeer -network mainnet -broadcaster -cliAddr 127.0.0.1:7936 -rtmpAddr 127.0.0.1:1936 -httpAddr 0.0.0.0:8936 -orchAddr 127.0.0.1:8935 -transcodingOptions P144p30fps16x9 -depositMultiplier 1 -maxPricePerUnit 5000000 -pixelsPerUnit 1 -maxTicketEV 1000000000000000 -v 99
```
4. Publisher (P) with
```
ffmpeg -re -f lavfi -i testsrc=size=256x144:rate=30,format=yuv420p -f lavfi -i sine -threads 1 -c:v libx264 -b:v 1000k -preset ultrafast -x264-params keyint=30 -strict -2 -c:a aac -f flv rtmp://127.0.0.1:1936/hello_world
```
5. See the following error from the O (full log transcripts below, including livepeer_cli readouts):
```
I0317 07:28:07.065976   32391 orchestrator.go:172] Receiving ticket manifestID=hello_world faceValue=348837209302325 WEI winProb=0.0028666667 ev=1000000000000.00
E0317 07:28:07.066346   32391 orchestrator.go:180] Error receiving ticket manifestID=hello_world recipientRandHash=cd74b1b95dd742a10d3581f00701db6cd6c151f93e2462c5a8c566ad5107e7fc senderNonce=1: invalid recipientRand for ticket recipientRandHash
E0317 07:28:07.066470   32391 segment_rpc.go:70] error processing payment: invalid recipientRand for ticket recipientRandHash
```
6. See the following error from the B (full log transcripts below, including livepeer_cli readouts):
```
I0317 07:29:28.821545   32425 broadcast.go:269] Processing segment nonce=3315485789012245931 manifestID=hello_world seqNo=41 dur=1.98
I0317 07:29:28.821926   32425 broadcast.go:339] Trying to transcode segment nonce=3315485789012245931 seqNo=41
I0317 07:29:28.822015   32425 broadcast.go:360] Submitting segment nonce=3315485789012245931 manifestID=hello_world seqNo=41 orch=https://127.0.0.1:8935
I0317 07:29:28.823290   32425 segment_rpc.go:634] Created new payment - manifestID=hello_world recipient=0xDAC817294c0c87ca4fA1895eF4b972EAde99f2fd faceValue=348837209302325 WEI winProb=0.0028666667 price=151933.366 wei/pixel numTickets=1
I0317 07:29:28.823403   32425 segment_rpc.go:342] Submitting segment nonce=3315485789012245931 manifestID=hello_world seqNo=41 bytes=175216 orch=https://127.0.0.1:8935
E0317 07:29:28.825027   32425 segment_rpc.go:369] Error submitting segment nonce=3315485789012245931 manifestID=hello_world seqNo=41 code=400 orch=https://127.0.0.1:8935 err=invalid recipientRand for ticket recipientRandHash
I0317 07:29:28.825064   32425 broadcast.go:332] No sessions available for segment nonce=3315485789012245931 manifestID=hello_world seqNo=41
I0317 07:29:28.825087   32425 broadcast.go:126] Starting session refresh manifestID=hello_world
I0317 07:29:28.825116   32425 rpc.go:223] Connecting RPC to https://127.0.0.1:8935
I0317 07:29:28.827576   32425 discovery.go:91] Done fetching orch info numOrch=1 responses=1/1 timeout=false
I0317 07:29:28.827662   32425 broadcast.go:170] Ending session refresh manifestID=hello_world dur=20.5µs
```

**Expected behavior**

I expect that the Orchestrator should start sending content to the Transcoder, and getting paid from the Broadcaster's deposit / reserve.

**Environment**

- OS:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
- Livepeer
```
Livepeer Node Version: 0.5.5
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```

**Log files**

[publisher log.txt](https://github.com/livepeer/go-livepeer/files/4342079/publisher.log.txt)
[broadcaster livepeer_cli log.txt](https://github.com/livepeer/go-livepeer/files/4342080/broadcaster.livepeer_cli.log.txt)
[broadcaster log.txt](https://github.com/livepeer/go-livepeer/files/4342081/broadcaster.log.txt)
[transcoder log.txt](https://github.com/livepeer/go-livepeer/files/4342082/transcoder.log.txt)
[orchestrator livepeer_cli log.txt](https://github.com/livepeer/go-livepeer/files/4342083/orchestrator.livepeer_cli.log.txt)
[orchestrator log.txt](https://github.com/livepeer/go-livepeer/files/4342084/orchestrator.log.txt)

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**

Avoid possible int64 overflows when doing a `big.Rat` price to `net.PriceInfo` conversion, whereby `PriceInfo.PricePerUnit` is the numerator of the `big.Rat` and `PriceInfo.PixelsPerUnit` is the denominator, by converting the `big.Rat` to a fixed point representation with a scaling factor of `common.PriceScalingFactor`. 

`PriceInfo.PixelsPerUnit` will then be `common.PriceScalingFactor` and PriceInfo.PricePerUnit will be the returned value from `common.PriceToFixed()`

**Specific updates (required)**
- return fixed point price from `orch.priceInfo` rather than a `big.Rat`
- export `common.PriceScalingFactor`
- add unit test that checks overflows aren't happening

**How did you test each of these updates (required)**
- Ran & adjusted unit tests

**Does this pull request close any open issues?**
Fixes #1426

**Checklist:**
- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

File: core/orchestrator.go [hunk 1]
```diff
@@ -264,23 +264,25 @@ func (orch *orchestrator) PriceInfo(sender ethcommon.Address) (*net.PriceInfo, e
...
 	txCostMultiplier, err := orch.node.Recipient.TxCostMultiplier(sender)
 	if err != nil {
-		return nil, err
+		return 0, err
 	}
 	// pricePerPixel = basePrice * (1 + 1/ txCostMultiplier)
 	overhead := new(big.Rat).Add(big.NewRat(1, 1), new(big.Rat).Inv(txCostMultiplier))
-	return new(big.Rat).Mul(orch.node.GetBasePrice(), overhead), nil
+	price := new(big.Rat).Mul(orch.node.GetBasePrice(), overhead)
+	return common.PriceToFixed(price)
```
Comment (yondonfu) [inline core/orchestrator.go]: Since we're calling `common.FixedToPrice()` on the value returned by this method in both `TicketParams()` and `PriceInfo()`, it might make sense to move the `common.FixedToPrice()` call into this method.

Ex.

```golang
...
fixedPrice, err := common.PriceToFixed(new(big.Rat).Mul(orch.node.GetBasePrice(), overhead))
if err != nil {
    return nil, err
}

return common.FixedToPrice(fixedPrice), nil
```

If we do this I don't think additional changes would be necessary in the callers of `priceInfo()`.

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: core/orchestrator.go (hunk 1 above)
Comment (kyriediculous) [reply core/orchestrator.go]: This is quite a lot of conversions but I guess I'd be fine with this because it does reduce the changes in the callers. Does this reconversion to a big.Rat uphold the guarantee that we end up with a fraction with a denominator of `common.PriceScalingFactor` or smaller  and a numerator of `fixedPrice` or smaller (big.Rat will always seek out the smallest possible denominator) ?

Comment (kyriediculous) [reply core/orchestrator.go]: fixed in 55ec1c6 and unexported `common.PriceScalingFactor` in 141c824

Comment (yondonfu) [reply core/orchestrator.go]: > This is quite a lot of conversions but I guess I'd be fine with this because it does reduce the changes in the callers.

Given that previously we would've had to call `common.FixedToPrice()` in the callers since certain APIs require the price to be passed as `big.Rat` I actually think doing the conversion in `priceInfo()` leads to less conversions overall since we only need to do it once in `priceInfo()`.

> Does this reconversion to a big.Rat uphold the guarantee that we end up with a fraction with a denominator of common.PriceScalingFactor or smaller and a numerator of fixedPrice or smaller (big.Rat will always seek out the smallest possible denominator) ?

I think so. Even if the internal representation in a `big.Rat` uses the lowest denominator, the numerator will never be greater than `fixedPrice` and the denominator will never be greater than the price scaling factor.

File: core/orchestrator.go [hunk 2]
```diff
@@ -273,14 +273,19 @@ func (orch *orchestrator) PriceInfo(sender ethcommon.Address) (*net.PriceInfo, e
 	}, nil
 }
 
+// priceInfo returns price per pixel as a fixed number
```
Comment (yondonfu) [inline core/orchestrator.go]: Nit: "fixed point number"

File: core/orch_test.go [hunk 3]
```diff
@@ -1248,8 +1252,15 @@ func TestPriceInfo_ReturnsBigRat(t *testing.T) {
 	orch := NewOrchestrator(n, nil)
 
 	priceInfo, err := orch.PriceInfo(ethcommon.Address{})
-	assert.Nil(t, err)
-	assert.Zero(t, expPricePerPixel.Cmp(big.NewRat(priceInfo.PricePerUnit, priceInfo.PixelsPerUnit)))
+	assert.Nil(err)
+	assert.Zero(expPricePerPixel.Cmp(big.NewRat(priceInfo.PricePerUnit, priceInfo.PixelsPerUnit)))
+	fixedPrice, err := common.PriceToFixed(expPricePerPixel)
+	expPrice := common.FixedToPrice(fixedPrice)
+	require.Nil(err)
```
Comment (yondonfu) [inline core/orch_test.go:1257]: This require statement should be called before calling `common.FixedToPrice()`. Same comment for the rest of the test cases in this file that place the require after `common.FixedToPrice()`.

File: core/orch_test.go [hunk 4]
```diff
@@ -1248,8 +1252,15 @@ func TestPriceInfo_ReturnsBigRat(t *testing.T) {
...
+	assert.LessOrEqual(priceInfo.PricePerUnit, fixedPrice)
+	assert.LessOrEqual(priceInfo.PixelsPerUnit, priceScalingFactor)
```
Comment (yondonfu) [inline core/orch_test.go]: Do we need an assertion about the relationship between `PixelsPerUnit` and `priceScalingFactor`? Seems that what we really care about is the test below which checks that the the `net.PriceInfo` returned and the `big.Rat` have the same values when the numerator and denominator are converted to int64. Without this assertion this test wouldn't need to know about the price scaling factor at all which is currently a detail of the `common` package since that value is not exported. Feels like the details of that package are leaking out here by declaring `priceScalingFactor` be equal to 1000 at the top of this test function.

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: core/orch_test.go (hunk 4 above)
Comment (kyriediculous) [reply core/orch_test.go]: Good point but I thought it would be nice to actually have unit tests that test the guarantee that the numerator will never be greater than fixedPrice and the denominator will never be greater than the price scaling factor.

Although I guess you could say that this is implicitly tested by the assertions below as you mention.

File: core/orchestrator.go (hunk 2 above)
Comment (kyriediculous) [reply core/orchestrator.go]: fixed in ec041c2d

File: core/orch_test.go (hunk 3 above)
Comment (kyriediculous) [reply core/orch_test.go:1257]: fixed in ec041c2d

File: core/orch_test.go (hunk 4 above)
Comment (kyriediculous) [reply core/orch_test.go]: fixed in ec041c2d

File: core/orch_test.go [hunk 5]
```diff
@@ -1320,8 +1352,36 @@ func TestPriceInfo_ReturnsBigRat(t *testing.T) {
 	expPricePerPixel = big.NewRat(20, 1)
 
 	priceInfo, err = orch.PriceInfo(ethcommon.Address{})
-	assert.Nil(t, err)
-	assert.Zero(t, expPricePerPixel.Cmp(big.NewRat(priceInfo.PricePerUnit, priceInfo.PixelsPerUnit)))
+	assert.Nil(err)
+	assert.Zero(expPricePerPixel.Cmp(big.NewRat(priceInfo.PricePerUnit, priceInfo.PixelsPerUnit)))
+	fixedPrice, err = common.PriceToFixed(expPricePerPixel)
+	expPrice = common.FixedToPrice(fixedPrice)
+	require.Nil(err)
```
Comment (yondonfu) [inline core/orch_test.go:1358]: `require` should be before previous line.

File: core/orch_test.go [hunk 6]
```diff
@@ -1320,8 +1352,36 @@ func TestPriceInfo_ReturnsBigRat(t *testing.T) {
...
+	overhead := new(big.Rat).Add(big.NewRat(1, 1), new(big.Rat).Inv(txMultiplier))
+	expPricePerPixel = new(big.Rat).Mul(basePrice, overhead) // 23953749205332825000/926899968213313
+	require.Equal(expPricePerPixel.Num().Cmp(big.NewInt(int64(math.MaxInt64))), 1)
+	priceInfo, err = orch.PriceInfo(ethcommon.Address{})
+	assert.Nil(err)
+	// for this case price will be rounded when converting to fixed
+	assert.NotEqual(expPricePerPixel.Cmp(big.NewRat(priceInfo.PricePerUnit, priceInfo.PixelsPerUnit)), 0)
+	fixedPrice, err = common.PriceToFixed(expPricePerPixel)
+	expPrice = common.FixedToPrice(fixedPrice)
+	require.Nil(err)
```
Comment (yondonfu) [inline core/orch_test.go:1381]: `require` should be before previous line.

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: core/orch_test.go (hunk 6 above)
Comment (kyriediculous) [reply core/orch_test.go:1381]: fixed in 1ff75f7

File: core/orch_test.go (hunk 5 above)
Comment (kyriediculous) [reply core/orch_test.go:1358]: fixed in 1ff75f7

**Review by yondonfu — COMMENTED** [review]
Changes look good - let's rebase

**Comment by kyriediculous** [comment]
rebased !

**Review by yondonfu — APPROVED** [review]
LGTM 🚢
