### PR TITLE
CLI claim action and job service fixes

### LINKED ISSUE #275: JobService first claim bug
The job service seems to consistently be trying to make a first claim when there are no segments to claim

```
I0118 17:02:45.501111    3712 jobservice.go:145] Making the first claim
I0118 17:02:45.501137    3712 jobservice.go:156] No segments to claim
I0118 17:02:45.501636    3712 jobservice.go:145] Making the first claim
I0118 17:02:45.501651    3712 jobservice.go:156] No segments to claim
I0118 17:02:45.501659    3712 jobservice.go:145] Making the first claim
I0118 17:02:45.501669    3712 jobservice.go:156] No segments to claim
I0118 17:02:45.502239    3712 jobservice.go:145] Making the first claim
I0118 17:02:45.502253    3712 jobservice.go:156] No segments to claim
```

### PR DESCRIPTION
**Pull request by yondonfu**
- Updates the CLI claim rewards/fees action to submit multiple transactions for chunks of rounds instead of trying to loop through all the rounds since the last claim round
- Update the constant `BlocksUntilFirstClaimDeadline` to 230 (previously 200). This number is arbitrary and is a little bit less than the absolute max 256 to give a little flexibility for network congestion
- Update the constant `RoundsPerTokenSharesClaim` to 50 (previously 20). The client will now loop through 50 rounds per claimTokenPoolsShares transaction
- In `jobservice.go` stop watching to perform the first claim if it has been `BlocksUntilFirstClaimDeadline` since the job creation block and there are no claimable segments

Closes #275 and #274

### CODE REVIEW

File: eth/client.go [hunk 1]
```diff
@@ -31,7 +31,7 @@ import (
 )
 
 var (
-	RoundsPerTokenSharesClaim = big.NewInt(20)
+	RoundsPerTokenSharesClaim = big.NewInt(50)
```
Comment (dob) [inline eth/client.go:34]: This has interesting consequences for the UX of things like using metamask to auth transactions for bonding/unbonding. In production it's almost 1 tx for every two months since the last bond/unbond/claim action. That seems borderline reasonable...so in the worst case if they haven't touched it for a year they may have to submit 7 tx's. But generally they may only to submit 1 or 2...which I think is at least tolerable for the metamask style UX. cc @jozanza 

On another note however, just because we can fit this many rounds into one claim in the gas limit on our testnet, doesn't mean that a big-gas transaction will go over well and get included quickly on ETH main net under congestion. You're not seeing a lot of 1 tx blocks these days.

Comment (yondonfu) [reply eth/client.go:34]: Right, in reality we should observe the estimate the ball park gas usage for particular number of rounds and then decide on a number based on that which might very well be lower than this number. I will look into doing some getting some gas reporting stats. I bumped it up here primarily for ease of use on the test network where it doesn't matter with the expectation that this number will probably change

**Review by ericxtang — APPROVED** [review]
This looks good. Fees like we need to do more thinking about the gas limit problem before getting to a good strategy. In the mean time, let's 🚢
