### PR TITLE
eth/types/segment_test: fix broken test

### LINKED ISSUE #973: all tests must pass (`go test ./...`)
In an effort to move towards portability and continuous integration, we must make sure that all tests pass.

Developers should run:
```
go test ./...
```
before every check-in to ensure that all existing tests pass before proposing any pull requests.  Developers are encouraged to include tests to cover every testable change made to the repository.

For now, let's just make sure that the existing tests all pass.

Once this is done, we should add `go test ./...` to CI.

### LINKED ISSUE #974: go test fails: github.com/livepeer/go-livepeer/eth/types [setup failed]
blocks #973
```
$ go test ./...
# github.com/livepeer/go-livepeer/eth/types
eth/types/segment_test.go:37:58: missing ',' before newline in composite literal
FAIL	github.com/livepeer/go-livepeer/eth/types [setup failed]
?   	github.com/livepeer/go-livepeer/cmd/devtool	[no test files]
?   	github.com/livepeer/go-livepeer/cmd/livepeer	[no test files]
ok  	github.com/livepeer/go-livepeer/cmd/livepeer_cli	(cached)
?   	github.com/livepeer/go-livepeer/cmd/simple_auth_server	[no test files]
ok  	github.com/livepeer/go-livepeer/common	(cached)
ok  	github.com/livepeer/go-livepeer/core	(cached)
ok  	github.com/livepeer/go-livepeer/discovery	(cached)
ok  	github.com/livepeer/go-livepeer/drivers	(cached)
ok  	github.com/livepeer/go-livepeer/eth	(cached)
?   	github.com/livepeer/go-livepeer/eth/contracts	[no test files]
ok  	github.com/livepeer/go-livepeer/eth/eventservices	(cached)
?   	github.com/livepeer/go-livepeer/ipfs	[no test files]
ok  	github.com/livepeer/go-livepeer/monitor	(cached)
?   	github.com/livepeer/go-livepeer/net	[no test files]
ok  	github.com/livepeer/go-livepeer/pm	(cached)
ok  	github.com/livepeer/go-livepeer/server	(cached)
```

...It's not as simple as a missing comma (`,`) ...  After fixing that, the new failure is:
```
$ go test ./...
# github.com/livepeer/go-livepeer/eth/types [github.com/livepeer/go-livepeer/eth/types.test]
eth/types/segment_test.go:23:3: cannot use d0 (type string) as type common.Hash in field value
eth/types/segment_test.go:38:3: cannot use common.RightPadBytes(([]byte)("browns"), 32) (type []byte) as type common.Hash in field value
eth/types/segment_test.go:40:18: undefined: common.Keccak256
eth/types/transcodereceipt_test.go:24:3: cannot use d0 (type string) as type []byte in field value
eth/types/transcodereceipt_test.go:25:3: cannot use tD0 (type string) as type []byte in field value
?   	github.com/livepeer/go-livepeer/cmd/devtool	[no test files]
?   	github.com/livepeer/go-livepeer/cmd/livepeer	[no test files]
ok  	github.com/livepeer/go-livepeer/cmd/livepeer_cli	(cached)
?   	github.com/livepeer/go-livepeer/cmd/simple_auth_server	[no test files]
ok  	github.com/livepeer/go-livepeer/common	(cached)
ok  	github.com/livepeer/go-livepeer/core	(cached)
ok  	github.com/livepeer/go-livepeer/discovery	(cached)
ok  	github.com/livepeer/go-livepeer/drivers	(cached)
ok  	github.com/livepeer/go-livepeer/eth	(cached)
?   	github.com/livepeer/go-livepeer/eth/contracts	[no test files]
ok  	github.com/livepeer/go-livepeer/eth/eventservices	(cached)
FAIL	github.com/livepeer/go-livepeer/eth/types [build failed]
?   	github.com/livepeer/go-livepeer/ipfs	[no test files]
ok  	github.com/livepeer/go-livepeer/monitor	(cached)
?   	github.com/livepeer/go-livepeer/net	[no test files]
ok  	github.com/livepeer/go-livepeer/pm	(cached)
ok  	github.com/livepeer/go-livepeer/server	(cached)
```

### PR DESCRIPTION
**Pull request by mk-livepeer**
The test `eth/types/segment_test.go` is currently broken, but the breakage is hidden by an error about a missing `,` .  Let's rip off the band-aid and fix this test!

* eth/types/segment_test.go:37:58: missing ',' before newline in composite literal
* eth/types/segment_test.go: fix missing import "bytes"
* eth/types/segment_test.go: whitespace cleanup
* eth/types: fix segment tests

closes #974 
closes #973

### CODE REVIEW

**Comment by kyriediculous** [comment]
I have added a commit that makes the tests pass. 
Main issues where that we were using the wrong types where we should have `ethcommon.Hash` as well as `Keccak256Hash` being located in the `crypto` package and not the `common` package of go-ethereum.

**Comment by mk-livepeer** [comment]
Indeed, tests pass now - thank you @kyriediculous !
```
$ go test ./...
?   	github.com/livepeer/go-livepeer/cmd/devtool	[no test files]
?   	github.com/livepeer/go-livepeer/cmd/livepeer	[no test files]
ok  	github.com/livepeer/go-livepeer/cmd/livepeer_cli	(cached)
?   	github.com/livepeer/go-livepeer/cmd/simple_auth_server	[no test files]
ok  	github.com/livepeer/go-livepeer/common	(cached)
ok  	github.com/livepeer/go-livepeer/core	(cached)
ok  	github.com/livepeer/go-livepeer/discovery	(cached)
ok  	github.com/livepeer/go-livepeer/drivers	(cached)
ok  	github.com/livepeer/go-livepeer/eth	(cached)
?   	github.com/livepeer/go-livepeer/eth/contracts	[no test files]
ok  	github.com/livepeer/go-livepeer/eth/eventservices	(cached)
ok  	github.com/livepeer/go-livepeer/eth/types	0.019s
?   	github.com/livepeer/go-livepeer/ipfs	[no test files]
ok  	github.com/livepeer/go-livepeer/monitor	(cached)
?   	github.com/livepeer/go-livepeer/net	[no test files]
ok  	github.com/livepeer/go-livepeer/pm	(cached)
ok  	github.com/livepeer/go-livepeer/server	(cached)
```

File: eth/types/segment_test.go [hunk 1]
```diff
@@ -35,9 +36,9 @@ func TestSegmentFlatten(t *testing.T) {
 	s := Segment{
 		StreamID:              "abcdef",
 		SegmentSequenceNumber: big.NewInt(1234),
-		DataHash:              ethcommon.RightPadBytes([]byte("browns"), 32),
+		DataHash:              ethcommon.BytesToHash(ethcommon.RightPadBytes([]byte("browns"), 32)),
 	}
-	if !bytes.Equal(ethcommon.Keccak256(s.Flatten()), s.Hash().Bytes()) {
+	if !bytes.Equal(crypto.Keccak256Hash(s.Flatten()).Bytes(), s.Hash().Bytes()) {
```
Comment (yondonfu) [inline eth/types/segment_test.go]: We can use `crypto.Keccak256()` (it returns `[]byte`)

**Review by yondonfu — COMMENTED** [review]
I don't think `types/segment.go` or `types/transcodereceipt.go` are used anymore so we could also just remove them

File: eth/types/segment_test.go (hunk 1 above)
Comment (kyriediculous) [reply eth/types/segment_test.go]: I was thinking the same that they are not used anymore but wasn't sure. 

I'm in favor of removal then, or do you want to keep the fixed tests as reference just in case?

Comment (yondonfu) [reply eth/types/segment_test.go]: I'm ok with removing

Comment (kyriediculous) [reply eth/types/segment_test.go]: I removed the files and their failing tests and rebased to drop the pervious commits.

Comment (yondonfu) [reply eth/types/segment_test.go]: Should remove the test files as well?

Comment (kyriediculous) [reply eth/types/segment_test.go]: I did but must have been reset when rebasing I guess, we're good now.

**Comment by mkrufky** [comment]
Seems fine to me.  :+1:     A word of advice, "force-push" should only be used when absolutely necessary.  In order to have a clean merge, just "squash" the PR when it's time to merge it.   When you force-push, it obliterates the history, and opens the door to additional human error (such as deleting the `.go` files but not the tests ;-) ) 

"force-push" is dangerous, and should not be a part of standard workflow - I repeat, it is OK to use when necessary, but please use it only when absolutely necessary.

**Review by yondonfu — APPROVED** [review]
LGTM

**Comment by j0sh** [comment]
> A word of advice, "force-push" should only be used when absolutely necessary. 

A force push is a "replace" rather than an "append" of a remote branch. Discouraging force-pushing is tantamount to discouraging rebases and amends. One of the under-utilized aspects of Git is the ability to tidy up commits in feature branches. Folks actively discourage that workflow for many of the reasons @mkrufky mentioned. To me, that's more of an indictment against Git's atrocious UX (and Github's poor support for non-Github-blessed workflows). It's a shame, because the ability to do so is one of those distinctly powerful features that sets Git apart from, say, Subversion (in addition to the whole DVCS thing...).

Personally, I don't have an issue with force-pushes as part of incremental maintenance on a feature branch. Mistakes can happen sometimes (the blame is really on Git porcelain, not the person), but practice makes perfect and it's really, really hard to permanently break things with Git. (It's OK to disagree vehemently with me on this; to each their own.)

**Comment by kyriediculous** [comment]
I think what @mk-livepeer meant is that I just did the rebase and force push a little prematurely, which is true. My reasoning for that was that previous commits didn't really matter because those involve changed files that were being deleted in the subsequent commit (the one we rebased to). But I can see the reasoning for wanting to keep those until we actually merge.

**Comment by j0sh** [comment]
> I just did the rebase and force push a little prematurely, which is true

It's not your fault - it's Git's fault! And then it's Github's fault on top of that, because their UX funnels people into a very specific review workflow (eg, only fixup prior to merging), which discourages incremental usage of some of the more powerful features of Git.
