### PR TITLE
server: transcode auth webhook

### LINKED ISSUE #1569: Transcoding Protocol Authentication
## Abstract

Currently, there is no authentication for the transcoding network protocol. A method of authentication is proposed for the transcoding network protocol which re-introduces an [authentication token](https://github.com/livepeer/go-livepeer/commit/fae70f384ab151b2f2c50495f3c406c706ef0412) that is acquired during discovery. This authentication scheme will also be useful for broadcasters running [Livepeer ingest](https://gist.github.com/j0sh/df016ea5da7e4e368e4f648faa9d4a32) ("proxy mode") and helps resolve some other [long-standing](https://github.com/livepeer/go-livepeer/issues/695) issues.

## Motivation

There are a few scenarios that might want access to be checked:

* Staging / testing environments that may be otherwise publicly accessible
* Livepeer.com hosted service - for both hosted broadcasters (proxy - authenticating customers) and orchestrators (for usage by internal / trusted Bs)
* Other types of private networks
* Onchain orchestrators that may want to implement an allow-list or deny-list of broadcaster addresses
* External rate limiting of jobs or certain addresses

## Proposed Solution

* Configure offchain broadcasters with an identifier. Use this value in the [`OrchestratorRequest.address`](https://github.com/livepeer/go-livepeer/blob/9fd21617aee0d73ac10e191ab4b6c5b33789c1dc/net/lp_rpc.proto#L29-L32) RPC field. This could be an API key, for example. If omitted, the value can remain empty.
* For onchain broadcasters, this identifier remains the ETH address.
* During [OrchestratorInfo handling](https://github.com/livepeer/go-livepeer/blob/9fd21617aee0d73ac10e191ab4b6c5b33789c1dc/server/rpc.go#L245-L253), make a webhook call if a webhook is configured. The configuration can reuse the `-authWebhookUrl` flag.
* The `url` field of the webhook request can be something like `livepeer://<broadcaster-address>` , where the address is encoded, maybe as hexadecimal (Eth standard), base64 (more compact), base32 (human friendly), etc. Optionally, it might help someday to distinguish the modes in use, eg proxy or on-chain, such as `livepeer+proxy://<broadcaster-address>` (B in proxy mode) or `livepeer+mainnet://<broadcaster-address>` (O on mainnet) or `livepeer+proxy+rinkeby://<broadcaster-address>` (B in proxy mode using Rinkeby).
* Assume only a 200 OK response is needed for webhook success. Later on, additional values may be returned from the webhook response in order to further control the flow. Any other non-200 response is an error.
* If webhook fails, error out from the RPC call, which will propagate back to the broadcaster.
* If no webhook is configured, assume success.
* If authentication succeeds, generate a token, something like: `token=hmac(secret, transcode-index|expiration)` and return an opaque blob to the broadcaster as part of the OrchestratorInfo message.
* The blob should be a base64'd Protocol Buffers message containing the token, transcode index and expiration.
* The secret can be generated once at start-up time, or derived based on the address. Should not be predictable and does not need to persist across restarts. This does mean that nodes which restart mid-stream will need to have the streams re-authenticate, but that seems OK for simplicity.
* Use `transcode-index` as a job identifier. This should be an unpredictable / random value that is generated fresh for each discovery call.
* Set a reasonable expiration; say 30 minutes or so. This prevents token reuse in the far future.
* Auth tokens with an updated expiration can be [refreshed](https://github.com/livepeer/go-livepeer/blob/9fd21617aee0d73ac10e191ab4b6c5b33789c1dc/server/broadcast.go#L399-L406) in the same manner that payment parameters are refreshed.
* Broadcaster-side, the blob should be incorporated into an auth header for each segment. The broadcaster doesn't need to process the blob or be aware of its structure, other than to copy it into the header. See the [old auth token](https://github.com/livepeer/go-livepeer/commit/fae70f384ab151b2f2c50495f3c406c706ef0412) for an example.
* Auth token should be validated at submission time for each segment. The HMAC means auth tokens don't need to persist between discovery calls; persistence only happens once a transcode session is started.

## Implementation Tasks and Considerations

Implementing transcoding auth should open the way for resolving https://github.com/livepeer/go-livepeer/issues/695 and the associated issues within that ticket; the `transcode-index` value within the HMAC construction can be used as a key into the transcode index.

The broadcaster transmitted manifest ID becomes unnecessary at this point, and its use should be removed from the orchestrator. (Broadcasters should opt to continue transmitting the manifest ID to maintain compatibility with older orchestrators.) However, the orchestrator still has its own uses for the manifest ID, for various indexing / naming purposes. The orchestrator's own manifest ID should be populated with the `transcode-index` value.

Depending on the roll-out timeline, orchestrators may opt to continue using broadcaster-supplied Manifest IDs if the auth token is absent, in order to maintain compatibility with older broadcasters. But this may be one case where a hard break is desirable.

Transcoding auth would also make [Livepeer ingest](https://gist.github.com/j0sh/df016ea5da7e4e368e4f648faa9d4a32) available to the hosted service, although the webhook endpoint would likely need to be updated for the new scheme.

## Testing Tasks and Considerations

Test Everything. Including back compat regression testing, eg  https://gist.github.com/j0sh/9d884a19bb92e504092e71fd19d812e5#file-run-sh, which also serves as a form of integration test.

## Known Unknowns

N/A

## Alternatives

Auth could be done via external means such as a proxy in front of the node. But this integrates and extends better into the tooling we already have.

## Additional Context

This is one of the pieces needed to make node-first workable in the hosted production infra, along with Livepeer ingest.

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**
Allows Orchestrators to specify an `-authWebhookUrl` to authenticate broadcasters upon discovery (`GetOrchestatorInfo`). 

**Specific updates (required)**
- created an `authenticateBroadcaster()` function in `server/rpc.go` this will no-op if no `-authWebhookUrl` is specified

- Add a call to `authenticateBroadcaster()` when calling `getOrchestrator()` in `server/rpc.go`

- Added unit tests for this new behaviour for `getOrchestrator()` using the `httptest` package which spins up a one-off http server which we specify as  `server.AuthWebhookUrl`

- Updated documentation on auth webhooks in `doc` 

**How did you test each of these updates (required)**
Added unit/integration tests

**Does this pull request close any open issues?**
Fixes #1569 

**Checklist:**
- [x] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

File: server/rpc.go [hunk 1]
```diff
@@ -302,6 +309,34 @@ func verifyOrchestratorReq(orch Orchestrator, addr ethcommon.Address, sig []byte
 	return orch.CheckCapacity("")
 }
 
+// authenticateBroadcaster returns an error if authentication fails
+func authenticateBroadcaster(id string) error {
+	if AuthWebhookURL == "" {
```
Comment (darkdarkdragon) [inline server/rpc.go:334]: `AuthWebhookURL` is set only for Broadcaster node

**Review by darkdarkdragon — CHANGES_REQUESTED** [review]

File: server/rpc.go (hunk 1 above)
Comment (kyriediculous) [reply server/rpc.go:334]: fixed in 9ce9e44f

File: doc/rtmpwebhookauth.md [hunk 2]
```diff
@@ -1,8 +1,8 @@
 # Webhook Authentication
 
-Incoming streams can be authenticated using webhooks. To use these webhooks, node operators must implement their own web service / endpoint to be accessed only by the Livepeer node. As new streams appear, the Livepeer node will call this endpoint to determine whether the given stream is allowed.
+Incoming streams can be authenticated using webhooks on both Orchestrator and Broadcaster nodes. To use these webhooks, node operators must implement their own web service / endpoint to be accessed only by the Livepeer node. As new streams appear, the Livepeer node will call this endpoint to determine whether the given stream is allowed.
 
-Webhooks can authenticate streams supported by the RTMP and HTTP push ingest protocols. See the [ingest documentation](ingest.md) for details on how to use these protocols.
+The webhook server should respond with HTTP status code `200` in order to authenticate / authorize the stream. A response with a HTTP status code other than `200` will cause the Livepeer node to disconnect the stream.
```
Comment (darkdarkdragon) [inline doc/rtmpwebhookauth.md:5]: This says that code should be strictly 200 for success, but actual code checks for whole 2XX range. Should we make them match?

**Review by darkdarkdragon — CHANGES_REQUESTED** [review]

File: doc/rtmpwebhookauth.md [hunk 3]
```diff
@@ -1,8 +1,8 @@
 # Webhook Authentication
 
-Incoming streams can be authenticated using webhooks. To use these webhooks, node operators must implement their own web service / endpoint to be accessed only by the Livepeer node. As new streams appear, the Livepeer node will call this endpoint to determine whether the given stream is allowed.
+Incoming streams can be authenticated using webhooks on both Orchestrator and Broadcaster nodes. To use these webhooks, node operators must implement their own web service / endpoint to be accessed only by the Livepeer node. As new streams appear, the Livepeer node will call this endpoint to determine whether the given stream is allowed.
```
Comment (yondonfu) [inline doc/rtmpwebhookauth.md]: I don't think we capitalize orchestrator and broadcaster elsewhere. If that is the case, then I suggest staying consistent with that convention.

File: server/rpc.go [hunk 4]
```diff
@@ -302,6 +309,34 @@ func verifyOrchestratorReq(orch Orchestrator, addr ethcommon.Address, sig []byte
...
+		return err
+	}
+
+	body, err := ioutil.ReadAll(res.Body)
+	defer res.Body.Close()
+	if err != nil {
+		return err
+	}
+
+	if res.StatusCode < 200 || res.StatusCode >= 300 {
```
Comment (yondonfu) [inline server/rpc.go]: Second Ivan's earlier comment about matching up the status code check here with the description in the docs. FWIW the webhook authentication on B also strictly checks for a 200 status code.

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: doc/rtmpwebhookauth.md (hunk 3 above)
Comment (kyriediculous) [reply doc/rtmpwebhookauth.md]: fixed in 4090a12

File: doc/rtmpwebhookauth.md (hunk 2 above)
Comment (kyriediculous) [reply doc/rtmpwebhookauth.md:5]: fixed in 4090a12

**Review by yondonfu — APPROVED** [review]
LGTM

**Review by darkdarkdragon — APPROVED** [review]
