### PR TITLE
cmd: Add fail-fast approach in case of incorrect config file

### LINKED ISSUE #2193: Livepeer configuration parameters are ignored
**Describe the bug**
When the Livepeer configuration file contains an unknown parameter, then all the following parameters are ignored.

**To Reproduce**
1. Created the following `livepeer.conf`

```
someMisspelledParameter 1234
reward false
```

2. Run Livepeer

```
$ livepeer -config livepeer.conf
```

3. Check that the `reward` parameter is ignored from `livepeer.conf`.

**Expected behavior**
We should have a fail-fast approach and if there is any unknown parameter, then just fail starting Livepeer.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
Related Discord discussion: https://discord.com/channels/423160867534929930/932724294230900776/933199481065840731

### PR DESCRIPTION
**Pull request by leszko**
**What does this pull request do? Explain your changes. (required)**
Fail fast when there is an error in the Livepeer config file.

**Specific updates (required)**
N/A

**How did you test each of these updates (required)**

1. Non-existing config file
```
$ ./livepeer -config nonExistingFile.conf
F0120 11:58:24.943412   42834 livepeer.go:171] Error using config file: open nonExistingFile.conf: no such file or directory
```
2. Config file with a flag that was not defined
```
$ cat livepeer.conf 
reward false malformed
$ ./livepeer -config livepeer.conf 
F0120 11:59:23.205466   42904 livepeer.go:171] Error using config file: error setting flag "reward" from config file: parse error
```
3. Malformed config file
```
$ cat livepeer.conf 
nonExistingFlag 123
reward false
$ ./livepeer -config livepeer.conf 
F0120 11:59:52.497457   42961 livepeer.go:171] Error using config file: config file flag "nonExistingFlag" not defined in flag set
```

**Does this pull request close any open issues?**
fix #2193

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [ ] README and other documentation updated
- [x] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

File: cmd/livepeer/livepeer.go [hunk 1]
```diff
@@ -162,11 +162,14 @@ func main() {
...
 	// Config file
 	_ = flag.String("config", "", "Config file in the format 'key value', flags and env vars take precedence over the config file")
-	ff.Parse(flag.CommandLine, os.Args[1:],
+	err = ff.Parse(flag.CommandLine, os.Args[1:],
 		ff.WithConfigFileFlag("config"),
 		ff.WithEnvVarPrefix("LP"),
 		ff.WithConfigFileParser(ff.PlainParser),
 	)
+	if err != nil {
+		glog.Fatal("Error using config file: ", err)
```
Comment (yondonfu) [inline cmd/livepeer/livepeer.go]: IIUC this error message will be not be accurate if CLI flags are used instead of a config file since `ff.Parse()` does not necessarily parse a config file if one is not provided and CLI flags are passed instead. Perhaps a more descriptive error message would be just: "Error parsing config"? WDYT?

**Review by yondonfu — APPROVED** [review]
LGTM. Just a minor question - feel free to address before merging if you agree.

File: cmd/livepeer/livepeer.go (hunk 1 above)
Comment (leszko) [reply cmd/livepeer/livepeer.go]: Right, updated in 3c0e0d3aab9ed3135c3b248ffba20380416067bc
