### PR TITLE
2 small fixes

### LINKED ISSUE #306: Event Server i/o Timeout
Livepeer 0.1.11

After starting my node, I am getting the following message ~every 30 seconds:

`Couldn't connect to the event server Post http://viz.livepeer.org:8081/metrics: dial tcp 13.58.252.248:8081: i/o timeout`

Restarting the node does not fix this.

### LINKED ISSUE #307: livepeer_cli on Rinkeby still sending people to eth-testnet.livepeer.org (linux)
When I try to "Get test Eth" through livepeer_cli on linux, it still tells me to:

> Go to eth-testnet.livepeer.org and use the faucet.

This faucet wasn't working when I used it, I suspect because it's only loading accounts on the testnet Blockchain?

image

When I charged my account from https://faucet.rinkeby.io/ it worked just fine :)

### PR DESCRIPTION
**Pull request by ericxtang**
Closes #306 
Closes #307

### CODE REVIEW

File: cmd/livepeer_cli/livepeer_cli.go [hunk 1]
```diff
@@ -165,7 +165,7 @@ func (w *wizard) doCLIOpt(choice string, transcoder bool) {
 		w.requestTokens()
 		return
 	case "11":
-		fmt.Print("Go to eth-testnet.livepeer.org and use the faucet. (enter to continue)")
+		fmt.Print("For Rinkeby, go to the Rinkeby faucet.  For the Livepeer testnet, go to eth-testnet.livepeer.org and use the faucet. (enter to continue)")
```
Comment (j0sh) [inline cmd/livepeer_cli/livepeer_cli.go]: Perhaps we should point them to the URL of a Rinkeby faucet?

**Review by j0sh — APPROVED** [review]
🚢
