### PR TITLE
pm: lower avgGasPrice

### LINKED ISSUE #2473: Streams drop using low face value
**Describe the bug**
Streams can drop due to face value of ticket being low using the `maxFaceValue` flag.  This only happens when gas prices spike.

This has to do with the code in `recipient.go` below where it uses 200 gwei as the `avgGasPrice` to check if ticket `faceValue` is less than current txCost or txCost with `avgGasPrice`.

https://github.com/livepeer/go-livepeer/blob/00a3e6d81edaf76bca19264d65269e4aa5f8c1c5/pm/recipient.go#L29-L31

This 200 gwei `avgGasPrice` is then used to compare `faceValue` to `txCost` with `avgGasPrice` of 200 gwei with the much higher gas used on Arbitrum (1,200,000 hardcoded, was 350,000 before switch to Arbitrum).  This test will always fail because it calculates a 0.24ETH value to compare the `faceValue` to.  

https://github.com/livepeer/go-livepeer/blob/00a3e6d81edaf76bca19264d65269e4aa5f8c1c5/pm/recipient.go#L304-L306

**To Reproduce**
1. Set `maxFaceValue` to really low value of 0.0012 when gas price is above 1 gwei
2. Observe `insufficient sender reserve` error in logs

**Expected behavior**
`faceValue` check to `txCost` should use an `avgGasPrice` that is a reasonable amount for Arbitrum.

**Additional context**
Ticket face value determined in `recipient.go` can return `insufficient sender reserve` error when ticket face value is set really low and gas prices start to spike.  See table below:

image

### PR DESCRIPTION
**Pull request by leszko**
**What does this pull request do? Explain your changes. (required)**

Lower the hardcoded avg gas price to prevent Os from dropping streams in case of the gas price spikes.

The value is changed from `200` => `140`. Here's the rationale why this value was chosen. In our problematic scenario, in the case when `maxFaceValue` is **not** set, then:

1. In order to not drop the stream during gas spike this condition `faceValue.Cmp(r.txCostWithGasPrice(avgGasPrice)) < 0` must be `false`
2. In the worse case scenario, face value [equals to max float](https://github.com/livepeer/go-livepeer/blob/8b3fcd674859f184407323266b6d1aae0ab42534/pm/recipient.go#L279) (which corresponds to the [B's reserve](https://github.com/livepeer/go-livepeer/blob/5d9bcaa325d8caa18151b42f50f4f78bf76834d7/pm/sendermonitor.go#L191), currently `180000000000000000`)
3. `txCostWithGasPrice()` is calculated as `redeemGas * avgGasPrice`, where Arbitrum `redeemGas` is [hardcoded](url) as `1200000`
4. That means that `180000000000000000 < 1200000 * avgGasPrice` must be `false`
5. That means that `180000000000000000 >= 1200000 * avgGasPrice` must be `true`
6. That means that `avgGasPrice <= 180000000000000000 / 1200000` => `avgGasPrice <= 150000000000`

So, with the current B's reserve and the current hardcoded `redeemGas`, the `avgGasPrice` must be smaller than `150 Gwei`. To make a buffer, I changed it to `140`.

**Specific updates (required)**

- Change `avgGasPrice`
- Simplify the condition check

**How did you test each of these updates (required)**

Debugged with Orchestrator.

**Does this pull request close any open issues?**

fix #2473

**Checklist:**

- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [ ] ~README and other documentation updated~
- [x] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

**Comment by yondonfu** [comment]
Just to clarify my own understanding (I wrote this avgGasPrice check awhile ago, but I need to jog my memory around how it works...):

`avgGasPrice` is supposed to represent the average gas price during a period of time. For simplicity, it was originally hardcoded to 200 gwei which indicates that the average gas price is 200 gwei (which was probably accurate at some point on L1). 

The check `faceValue.Cmp(r.txCostWithGasPrice(avgGasPrice)) < 0` is used as a secondary check when `faceValue < txCost` where `txCost` is calculated based on the current estimated gas price. The reason for having this secondary check is that when `faceValue < txCost` it might be the case that we are in the middle of a gas price spike which is why `faceValue < txCost`. If we are in the middle of a gas price spike it would be reasonable to expect the gas price to fall after a period of time. As long as the `faceValue` can cover the expected tx cost based on `avgGasPrice` (recall that this is meant to represent the average gas price) then O advertises ticket params assuming that the gas price will fall to `avgGasPrice` or lower.

With this in mind, it makes sense that a lower `avgGasPrice` makes sense here because the average gas price on Arbitrum is substantially lower than 200 gwei. In reality, the average gas price is even lower than 140 gwei (I know that the OP describes deriving this value based on an assumption of the value of B's reserve, but I generally don't think we should hardcoded values based on an assumption of the value of B's reserve).

I think this PR is fine as-is though as the more ideal solution is to not hardcode a value for `avgGasPrice` at all which can be followed up on.

File: pm/recipient.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ var evMultiplier = big.NewInt(100)
 
 // Hardcode to 200 gwei
```
Comment (yondonfu) [inline pm/recipient.go]: Let's update this comment

**Review by yondonfu — APPROVED** [review]
Minor comment about fixing an outdated comment.

Other than that LGTM.

**Comment by leszko** [comment]
> Just to clarify my own understanding (I wrote this avgGasPrice check awhile ago, but I need to jog my memory around how it works...):
> 
> `avgGasPrice` is supposed to represent the average gas price during a period of time. For simplicity, it was originally hardcoded to 200 gwei which indicates that the average gas price is 200 gwei (which was probably accurate at some point on L1).
> 
> The check `faceValue.Cmp(r.txCostWithGasPrice(avgGasPrice)) < 0` is used as a secondary check when `faceValue < txCost` where `txCost` is calculated based on the current estimated gas price. The reason for having this secondary check is that when `faceValue < txCost` it might be the case that we are in the middle of a gas price spike which is why `faceValue < txCost`. If we are in the middle of a gas price spike it would be reasonable to expect the gas price to fall after a period of time. As long as the `faceValue` can cover the expected tx cost based on `avgGasPrice` (recall that this is meant to represent the average gas price) then O advertises ticket params assuming that the gas price will fall to `avgGasPrice` or lower.
> 
> With this in mind, it makes sense that a lower `avgGasPrice` makes sense here because the average gas price on Arbitrum is substantially lower than 200 gwei. In reality, the average gas price is even lower than 140 gwei (I know that the OP describes deriving this value based on an assumption of the value of B's reserve, but I generally don't think we should hardcoded values based on an assumption of the value of B's reserve).
> 
> I think this PR is fine as-is though as the more ideal solution is to not hardcode a value for `avgGasPrice` at all which can be followed up on.

Yes, everything you described is correct. You may be right that we should maybe not make any assumptions about our B reserve. So how, about setting average gas price to some more realistic number in Arbitrum, like `2` or `3`. Wdyt?

**Comment by yondonfu** [comment]
> So how, about setting average gas price to some more realistic number in Arbitrum, like 2 or 3. Wdyt?

👍

File: pm/recipient.go (hunk 1 above)
Comment (leszko) [reply pm/recipient.go]: Updated in 98cad6dc510f138751a9ac9cc889588372ef9ceb

**Comment by leszko** [comment]
> > So how, about setting average gas price to some more realistic number in Arbitrum, like 2 or 3. Wdyt?
> 
> 👍

Updated in 98cad6dc510f138751a9ac9cc889588372ef9ceb
