### PR TITLE
Transaction receipt status & video profile ids

### LINKED ISSUE #162: Check transaction receipt for transaction status
With the new Byzantium changes, transaction receipts now include a status field that indicate whether a transaction succeeded or failed. We should check for this and remove the current hack of comparing gas consumed with gas used to check for transaction status

### PR DESCRIPTION
**Pull request by yondonfu**
- Updated vendored Geth to 1.7.2
- Checking transaction receipt status instead of the previous hack of checking if all the gas was consumed in a transaction (made possible by Byzantium)
- Using first 4 bytes of keccak256 hash of video profile name as video profile id. The video profile ids are concatenated together to form the transcodingOptions string which is submitted on-chain by the broadcaster. The video profile ids are first sorted by video profile name

Closes #162 #158 #153

### CODE REVIEW

**Comment by ericxtang** [comment]
I remember we did a few changes in the vendored go-ethereum code base
* In accounts/abi/method.go, we added the fix for the dynamic length param fix
* In ethclient/ethclient.go, we added BlockByTxHash
* Changes in accounts/abi/type.go 
* Changes in accounts/abi/bind/template.go

Looks like some of the files are removed, and some were updated.  Did you have to cherry pick the changes?

**Comment by yondonfu** [comment]
I merged go-ethereum with the head at the commit for the 1.7.2 release into my branch with the dynamic length param fix (https://github.com/yondonfu/go-ethereum/tree/abi-offset-fixed-arrays) and then added the BlockByTxHash into ethclient/ethclient.go - I then replaced the vendored go-ethereum with this code base.

The changes in accounts/abi/type.go and accounts/abi/bind/template.go are not included right now because those were actually for generating the Go contract bindings which I believe in most cases we would be using the globally installed `abigen` command and would not be relying on any of the contract binding generation code in a vendored code base. Plus, those changes only had to do with deploying contracts using the Go contract bindings - since we're mainly relying on Truffle to deploy the contracts now and then using the Go contract bindings only to interact with the already deployed contracts, I don't think they are necessary.

File: eth/client.go [hunk 1]
```diff
@@ -934,8 +951,8 @@ func (c *Client) GetReceipt(tx *types.Transaction) (*types.Receipt, error) {
 		}
 
 		if receipt != nil {
-			if tx.Gas().Cmp(receipt.GasUsed) == 0 {
-				return nil, fmt.Errorf("Tx %v threw", tx.Hash().Hex())
+			if receipt.Status == uint(0) {
```
Comment (yondonfu) [inline eth/client.go:954]: Just noting here that this change would be backward incompatible - you would have to be using a Byzantium compatible version of Geth (or any other Ethereum client) since the receipt status was only added in Byzantium

**Comment by ericxtang** [comment]
🚢

**Review by ericxtang — APPROVED** [review]
