### PR TITLE
eth: prefill last seen block state in timewatcher

### LINKED ISSUE #1420: panic: runtime error in version 0.5.5
**Describe the bug**

Livepeer binaries running in `-orchestrator` mode failing with runtime error under specific use-case.

**To Reproduce**

1. Run a B with:
```
./livepeer-linux-amd64/livepeer -network rinkeby -broadcaster -cliAddr 127.0.0.1:7935 -rtmpAddr 127.0.0.1:1935 -httpAddr 0.0.0.0:8935 -orchAddr 127.0.0.1:8936 -transcodingOptions P144p30fps16x9 -depositMultiplier 1 -maxPricePerUnit 5000000000 -pixelsPerUnit 1 -maxTicketEV 1000000000000000000 -v 99
```
2. Wait for the B to report `LPMS Server listening on rtmp://127.0.0.1:1935`

3. Publish content into the B with the command below:
```
ffmpeg -re -f lavfi -i testsrc=size=256x144:rate=30,format=yuv420p -f lavfi -i sine -threads 1 -c:v libx264 -b:v 1000k -preset ultrafast -x264-params keyint=30 -strict -2 -c:a aac -f flv rtmp://127.0.0.1:1935/hello_world
```
4. Run an O with the following command (note, no process is running as `-transcoder`)
```
./livepeer-linux-amd64/livepeer -network rinkeby -orchestrator -cliAddr 127.0.0.1:7936 -httpAddr 127.0.0.1:8936 -serviceAddr 127.0.0.1:8936 -pricePerUnit 2000000000 -pixelsPerUnit 1 -ticketEV 1000000000000000 -orchSecret secret -v 99
```
5. See the following log from the O:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5bd4f9]
```
(Full log output from process below)

**Expected behavior**

In this case, I expect that the O will publish no available sessions to the B, and wait until a T registers to it.

This case models when a O goes offline while a B is already processing content. When the O comes back online, there would be a time when the B is sending to the O, before any Ts have registered.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
```
ubuntu@ip-172-31-43-225:~$ ./livepeer-linux-amd64/livepeer -version
Livepeer Node Version: 0.5.5
Golang runtime version: gc go1.13.4
Architecture: amd64
Operating system: linux
```

**Log**
From `-orchestrator` process which crashed:
```
ubuntu@ip-172-31-43-225:~$ ./livepeer-linux-amd64/livepeer -network rinkeby -orchestrator -cliAddr 127.0.0.1:7936 -httpAddr 127.0.0.1:8936 -serviceAddr 127.0.0.1:8936 -pricePerUnit 2000000000 -pixelsPerUnit 1 -ticketEV 1000000000000000 -orchSecret secret -v 99
I0313 11:11:40.660593    2660 livepeer.go:204] ***Livepeer is running on the rinkeby network: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea***
I0313 11:11:40.661783    2660 db.go:316] Initialized DB node
I0313 11:11:41.177397    2660 accountmanager.go:61] Found existing ETH account
I0313 11:11:41.177425    2660 accountmanager.go:188] Defaulting to first ETH account in keystore 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
I0313 11:11:41.177442    2660 accountmanager.go:70] Using Ethereum account: 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
I0313 11:11:42.164207    2660 accountmanager.go:93] Please enter the passphrase to unlock Ethereum account 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
Passphrase: 
I0313 11:11:46.207982    2660 accountmanager.go:104] Unlocked ETH account: 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
I0313 11:11:46.208287    2660 client.go:215] Controller: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea
I0313 11:11:46.324241    2660 client.go:236] LivepeerToken: 0x23b814a57D53b1a7A860194F53401D0D639abED7
I0313 11:11:46.427484    2660 client.go:257] ServiceRegistry: 0xa7AFBB45eb8C27a26379F9C550B3b9be7f09c3eA
I0313 11:11:46.530619    2660 client.go:278] BondingManager: 0xe75a5DccfFe8939F7f16CC7f63EB252bB542FE95
I0313 11:11:46.656612    2660 client.go:299] TicketBroker: 0x40897Ff6e44Ca2e145A691701897844669Bf7cee
I0313 11:11:46.761289    2660 client.go:320] RoundsManager: 0x572d1591bD41f50130FD0212058eAe34F1B17290
I0313 11:11:46.868399    2660 client.go:341] Minter: 0xe5056d1fE48F562dd8AcB1BBFFa147223d448C1B
I0313 11:11:46.977089    2660 client.go:362] LivepeerTokenFaucet: 0x6b752dA302C80795ACc9347AF8f472D3473b19f2
I0313 11:11:47.087770    2660 livepeer.go:469] Price: 2000000000 wei for 1 pixels
 
I0313 11:11:47.831603    2660 livepeer.go:898] Orchestrator 0xXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX is active
I0313 11:11:47.934238    2660 gaspricemonitor.go:134] Cached gas price: 1000000000
I0313 11:11:48.050917    2660 block_watcher.go:318] Backfilling block events (this can take a while)...
I0313 11:11:48.050945    2660 block_watcher.go:319] Start block: 6130376		 End block: 6130375		Blocks elapsed: -1
I0313 11:11:48.057024    2660 block_watcher.go:537] fetching block logs from=6130376 to=6130375
I0313 11:11:48.157951    2660 livepeer.go:777] ***Livepeer Running in Orchestrator Mode***
I0313 11:11:48.158044    2660 mediaserver.go:141] Transcode Job Type: [{P240p30fps16x9 600k 30 426x240 16:9} {P360p30fps16x9 1200k 30 640x360 16:9}]
I0313 11:11:48.158168    2660 cert.go:83] Private key and cert not found. Generating
I0313 11:11:48.158170    2660 webserver.go:70] CLI server listening on 127.0.0.1:7936
I0313 11:11:48.158438    2660 cert.go:22] Generating cert for 127.0.0.1
I0313 11:11:48.158745    2660 rpc.go:155] Listening for RPC on 127.0.0.1:8936
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5bd4f9]

goroutine 105 [running]:
math/big.(*Int).Add(0xc000299a40, 0x0, 0xc00037f360, 0xc0fdf299de)
	/usr/lib/go-1.13/src/math/big/int.go:117 +0x29
github.com/livepeer/go-livepeer/pm.(*recipient).TicketParams(0xc00072a2d0, 0xca870c4c2917c8da, 0xea72b9f45e89a14f, 0xc0fdf299de, 0xc0007a8880, 0x0, 0x0, 0x1)
	/build/pm/recipient.go:221 +0x196
github.com/livepeer/go-livepeer/core.(*orchestrator).TicketParams(0xc0001f0fc0, 0xca870c4c2917c8da, 0xea72b9f45e89a14f, 0xc0fdf299de, 0xc0006a2188, 0x0, 0x0)
	/build/core/orchestrator.go:238 +0xe6
github.com/livepeer/go-livepeer/server.orchestratorInfo(0x1f6dbe0, 0xc0001f0fc0, 0xca870c4c2917c8da, 0xea72b9f45e89a14f, 0xfdf299de, 0xc00068f8c0, 0x16, 0x50, 0x0, 0x0)
	/build/server/rpc.go:256 +0x52
github.com/livepeer/go-livepeer/server.getOrchestrator(0x1f6dbe0, 0xc0001f0fc0, 0xc000128f50, 0x1b6a9e0, 0xc000771800, 0x1f49080)
	/build/server/rpc.go:252 +0x21c
github.com/livepeer/go-livepeer/server.(*lphttp).GetOrchestrator(0xc00028dde0, 0x1f5b200, 0xc000277b30, 0xc000128f50, 0xc00028dde0, 0xc000277b30, 0xc000063a80)
	/build/server/rpc.go:128 +0x41
github.com/livepeer/go-livepeer/net._Orchestrator_GetOrchestrator_Handler(0x1b6a9e0, 0xc00028dde0, 0x1f5b200, 0xc000277b30, 0xc000771860, 0x0, 0x1f5b200, 0xc000277b30, 0xc000780060, 0x59)
	/build/net/lp_rpc.pb.go:1341 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00073eb00, 0x1f67b20, 0xc0001e1320, 0xc0000f7d00, 0xc0001f10e0, 0x2b65080, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:995 +0x460
google.golang.org/grpc.(*Server).handleStream(0xc00073eb00, 0x1f67b20, 0xc0001e1320, 0xc0000f7d00, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:1275 +0xd97
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0004934e0, 0xc00073eb00, 0x1f67b20, 0xc0001e1320, 0xc0000f7d00)
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:710 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.23.0/server.go:708 +0xa1
```

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**
Prefetch the state for `lastSeenBlock` in the timewatcher to prevent nil pointer errors when no blocks have elapsed and thus the state isn't populated through backfilling

**Specific updates (required)**
- Added a StubBackend for testing
- Added fetching last seen block number when calling `timeWatcher.Watch()`

**How did you test each of these updates (required)**
Added unit tests

**Does this pull request close any open issues?**
Fixes #1420 

**Checklist:**
- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

File: eth/watchers/timewatcher.go [hunk 1]
```diff
@@ -122,6 +124,19 @@ func (tw *TimeWatcher) Watch() error {
...
 	}
 
+	b, err := tw.lpEth.Backend()
+	if err != nil {
+		return err
+	}
+
+	ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
+	defer cancel()
+	lastSeenBlock, err := b.HeaderByNumber(ctx, nil)
```
Comment (yondonfu) [inline eth/watchers/timewatcher.go]: Instead of fetching the latest block number via RPC request here could we use the latest block number returned by `tw.watcher.GetLatestBlock()`? If this value is behind the latest block height, then `tw.lastSeenBlock` will be initialized to this value and then it will be updated when backfilling is complete. If the block watcher has no latest block then `tw.lastSeenBlock` will be nil at first, but it will also be updated when backfilling is complete (which should be fine since the node will not receive any external requests until after backfilling is complete).

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: eth/watchers/timewatcher.go (hunk 1 above)
Comment (kyriediculous) [reply eth/watchers/timewatcher.go]: This issue occurs when we do not backfill so after backfilling is complete `tw.lastSeenBlock` will still be `nil` and we'll still run into a nil-pointer error when receiving a `GetOrchestratorInfo` request before the first block is propagated.

Comment (yondonfu) [reply eth/watchers/timewatcher.go]: I believe that backfilling does not occur when the ETH node's latest block is less than or equal to the block watcher's latest block. Wouldn't this imply that the block watcher has a latest block and that `tw.lastSeenBlock` is initialized to a non-nil value? The only time `tw.lastSeenBlock` is initialized to nil would be if the block watcher does not have a latest block, but that would imply that backfilling will occur and set `tw.lastSeenBlock` to a non-nil value. We could also use a safer default value for `tw.lastSeenBlock` like 0.

I'm mainly inquiring about this possibility since we already have services in the node that handle RPC requests for updating the latest known block number I'm curious to see if we can avoid introducing an additional one off RPC request here.

Comment (kyriediculous) [reply eth/watchers/timewatcher.go]: Oh yes I see what you're saying. Sorry I read your initial comment a little too fast.

Comment (kyriediculous) [reply eth/watchers/timewatcher.go]: fixed in a53f76fd

I commented out the stubBackend I wrote but can remove it if you want.

File: eth/watchers/timewatcher.go [hunk 2]
```diff
@@ -122,6 +122,12 @@ func (tw *TimeWatcher) Watch() error {
 		return fmt.Errorf("error fetching initial transcoderPoolSize err=%v", err)
 	}
 
+	lastSeenBlock, err := tw.watcher.GetLatestBlock()
+	if err != nil {
+		return fmt.Errorf("error fetching last seen block err=%v", err)
+	}
+	tw.setLastSeenBlock(lastSeenBlock.Number)
```
Comment (yondonfu) [inline eth/watchers/timewatcher.go]: I think `lastSeenBlock` can be nil if the node has a fresh DB. We should add a nil check and if it is nil we can use a sane default value like `big.NewInt(0)` which should only be temporary until backfilling updates the value to the latest block number.

File: eth/stubclient.go [hunk 3]
```diff
@@ -332,3 +335,84 @@ func (c *StubClient) SetGasInfo(uint64, *big.Int) error { return nil }
 
 // Faucet
 func (c *StubClient) NextValidRequest(common.Address) (*big.Int, error) { return nil, nil }
+
+/* STUB BACKEND
```
Comment (yondonfu) [inline eth/stubclient.go]: Let's remove this in the interest of reducing the diff for this PR - if we do end up needing this stub at a later point in time it should be straightforward to add it then.

File: eth/stubclient.go [hunk 4]
```diff
@@ -174,6 +174,7 @@ type StubClient struct {
 	Err                          error
 	TotalStake                   *big.Int
 	TranscoderPoolError          error
+	StubBackend                  Backend
```
Comment (yondonfu) [inline eth/stubclient.go]: Doesn't look like we need this anymore?

File: eth/stubclient.go [hunk 5]
```diff
@@ -182,18 +183,20 @@ type stubTranscoder struct {
...
-func (e *StubClient) CurrentRound() (*big.Int, error)                    { return big.NewInt(0), e.RoundsErr }
-func (e *StubClient) LastInitializedRound() (*big.Int, error)            { return big.NewInt(0), e.RoundsErr }
-func (e *StubClient) BlockHashForRound(round *big.Int) ([32]byte, error) { return [32]byte{}, nil }
-func (e *StubClient) CurrentRoundInitialized() (bool, error)             { return false, nil }
-func (e *StubClient) CurrentRoundLocked() (bool, error)                  { return false, nil }
-func (e *StubClient) CurrentRoundStartBlock() (*big.Int, error)          { return nil, nil }
-func (e *StubClient) Paused() (bool, error)                              { return false, nil }
+func (e *StubClient) InitializeRound() (*types.Transaction, error) { return nil, nil }
+func (e *StubClient) CurrentRound() (*big.Int, error)              { return big.NewInt(0), e.RoundsErr }
+func (e *StubClient) LastInitializedRound() (*big.Int, error)      { return e.BlockNum, e.RoundsErr }
```
Comment (yondonfu) [inline eth/stubclient.go]: Returning a field named `e.BlockNum` in `LastInitializedRound()` seems strange and is a bit confusing in the tests. Can we use something like `e.Round`?

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: eth/watchers/timewatcher.go (hunk 2 above)
Comment (kyriediculous) [reply eth/watchers/timewatcher.go]: There's no need to set initialise this value I think as we have a nil check in the handler and the node will always backfill in this case before starting normal node operations.

```
func (tw *TimeWatcher) handleBlockNum(event *blockwatch.Event) {
	last := tw.LastSeenBlock()
	new := event.BlockHeader.Number
	if last == nil || last.Cmp(new) != 0 {
		tw.setLastSeenBlock(new)
		tw.blockSubFeed.Send(new)
	}
}
```

Comment (yondonfu) [reply eth/watchers/timewatcher.go]: `handleBlockNum()` is only called when a `blockwatch.Event` is received via the block watcher subscription. This piece of code is run before the block watcher subscription is created and the value returned by `tw.watcher.GetLatestBlock()` could be nil (i.e. if the node has a fresh DB).

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: eth/watchers/timewatcher.go (hunk 2 above)
Comment (kyriediculous) [reply eth/watchers/timewatcher.go]: Yes that's true but that doesn't really matter there's three scenarios that are all covered as is.

- Node has a fresh DB
  1. initialise `tw.lastSeenBlock = nil`
  2. backfill all blocks from the current round
  3. `tw.lastSeenBlock` is now set to the last seen backfilled block

- Node has a DB with an outdated `lastSeenblock`
 1. Initialise `tw.lastSeenBlock` to the last seen block in the DB
 2. If the block is in the current round start backfilling else backfill from the current round start block
 3. Set `tw.lastSeenblock` to the last backfilled block

- Node has a DB with a last seen block >= the actual last seen block
 1. Initialise `tw.LastSeenBlock` to the latest seen block
 2. Don't backfill
 
None of these cases will end up with a `tw.lastSeenBlock = nil` by the time node startup is complete.

Comment (yondonfu) [reply eth/watchers/timewatcher.go]: If the node has a fresh DB, after the call to `tw.watcher.GetLatestBlock()` the `lastSeenBlock` variable will be set to nil. Then `lastSeenBlock.Number` L129 will trigger a nil pointer error. All this happens before backfilling happens.

Comment (kyriediculous) [reply eth/watchers/timewatcher.go]: Ah right ! I missed that part 😅

Comment (kyriediculous) [reply eth/watchers/timewatcher.go]: fixup cc20510 & unit test af853a1

**Comment by kyriediculous** [comment]
I see everything has been marked as resolved, can I rebase ?

**Review by yondonfu — COMMENTED** [review]
Changes look good - let's rebase.

**Comment by kyriediculous** [comment]
rebased

**Review by yondonfu — APPROVED** [review]
LGTM 🚢
