### PR TITLE
eth,misc: Use transaction manager with confirmation and optional replacement queue

### LINKED ISSUE #1906: Failed gas estimation with revert for txs when another tx affecting the same state is pending
# Background

A few orchestrators have reported gas estimation failing for reward txs with the confusing error message of:

```
failed to estimate gas needed: execution reverted: caller has already called reward for the current round
```

This error message is confusing because in these cases reward txs for these orchestrators had not yet been mined in the current round. This error message was observed when the node tried to automatically submit reward txs and when `livepeer_cli` was used to manually submit a reward tx. 

In one case, the operator was able to solve this problem by restarting the orchestrator with a different ETH provider (i.e. switched from a cluster of geth nodes to Infura). After the reward tx was mined, the operator observed a sequence of failed txs:

1. [Successful reward tx](https://etherscan.io/tx/0xdd9ea3c395af5cc174f2cbf124a66ef7bb00e742f0bdfe5cc638ad2b0193710c)
2. [Reverted reward tx](https://etherscan.io/tx/0xcfbc7664378b5726402944f49283dedabbd6798bbf5ec0fe7d782cbc93e0d83f)

The orchestrator had also previously attempted to submit transcoder txs (omitted from the above list, but can be found on the account's Etherscan page), but the node timed out waiting for each of the txs to be mined. The failed tx sequence and the node timing out waiting for some of the txs in the sequence leads me to the believe that the problem was that a bunch of txs were stuck pending which resulted in a few additional problems one of them being failed gas estimation with a revert. I'll focus on this problem in this issue.

The reward tx submitted by the orchestrator while another reward tx was pending resulted in a failed gas estimation with a revert because the node currently uses [EstimateGas](https://github.com/ethereum/go-ethereum/blob/0e9c7d564d6000a372cd3df914ec6c969aea29f2/ethclient/ethclient.go#L505) which calls the `eth_estimateGas` RPC method under the hood without a specified block number. When `eth_estimateGas` is called without a specific block number, it will by default by run against the current ["pending" block](https://github.com/ethereum/go-ethereum/blob/5cff9754d795971451f2f4e8a2cc0c6f51ce9802/internal/ethapi/api.go#L1040). I believe this means that a pending reward tx from the orchestrator would be applied to state such that when gas estimation is invoked for the new reward tx it will execute against state that was already updated by the pending reward tx. As a result, the new reward tx would revert during gas estimation since the updated state reflects that reward was already called in the current round.

This problem will typically arise if an initial reward tx (or any tx for that matter) is submitted with a low gas price such it gets stuck in the pending state. Previously, this would only happen if the required gas price for a tx to be mined in a timely manner spiked up right after a tx was submitted. However, lately, the `eth_gasPrice` RPC call can return extremely low gas prices (lower than what is actually required) depending on the ETH node/provider as a result of an uptick of 0/1 wei gas price MEV txs being mined. geth updated its gas price oracle implementation to stabilize values returned by `eth_gasPrice` in [v1.10.3](https://github.com/ethereum/go-ethereum/releases/tag/v1.10.3), but orchestrator operators may be slow to upgrade and ETH providers running geth might still be using an older version - for example, [Infura is still on v.1.10.2](https://forkmon.ethdevops.io/). While #1860 improved the stability of the gas price monitor in the livepeer node, it is still possible for an [extremely low gas price to be attached to a tx at submission time](https://github.com/ethereum/go-ethereum/blob/0e9c7d564d6000a372cd3df914ec6c969aea29f2/accounts/abi/bind/base.go#L229).

# Possible Solutions

#1841 could help by giving a livepeer node access to a more robust gas price service.

I think support for tx retries with gas price bumping for all txs (we currently have a more limited version implemented just for reward txs) would also help here assuming that the implementation includes:

- A max # of retries
- A time interval between retries
- A strategy to bump the previous gas price by X% OR use the current fetched gas price if it is higher than the result of the former

The time interval between retries would give the livepeer node an opportunity to get a fresh gas price after a period of time - even if the `eth_gasPrice` RPC call returns extremely low gas prices sometimes it is less likely to consistently return extremely low gas prices. The gas price setting strategy ensures that if the fresh gas price is more reasonable than the previous extremely low gas price then it will be used.

Given that recent versions of geth help with this problem when still using the `eth_gasPrice` RPC call to fetch gas prices (so its a matter of orchestrator operators upgrading their geth or ETH providers upgrading their geth), I'm a bit more interested in exploring the tx retries solution first as that will also be generally useful outside of addressing this problem.

### PR DESCRIPTION
**Pull request by kyriediculous**
**What does this pull request do? Explain your changes. (required)**
Use a `TransactionManager` to handle transactions. This service will forward transactions to the ethereum JSON-RPC, when a transaction is broadcasted to the ethereum network it will be added to the queue. Lowest non-confirmed transactions are popped off the queue to wait until they are mined and retrieve their transaction receipt. 

Once the transaction receipt is found it will be sent over a subscription of transaction receipts that services that want feedback on tx confirmation can subscribe to. This subscription service now powers `LivepeerEthClient.CheckTx()` under the hood. 

**Specific updates (required)**
- 75eed97c84e9d40194403996fc75443f7d375d9e  eth: transaction manager with confirmation queue and optional replacement transactions

-  60d33a0c763505098488050999b220f51ed740a3  pm: handle ticket revert error

- a7b7c5e46e7d406a0f6330f53751a53e20e217ac  eth: remove replacement transactions from reward service

- d4886f688b6edc8f25243d846872a8821ca9b16f  eth,server: move max gas price logic to gas price monitor

- b12a24dc6888ff94d6a68fe3f6628cc828a1e015 eth: make abiMap and txLog helpers in the eth package rather than Backend methods

- 1b89b5c37b1a57da231df387bb8f3d163ed412a0  cmd: replace transaction flag

- efa84b466cebc138501eb8dcb380abe7fbbfd539  cmd,eth: use struct for LivepeerEthClient constructor parameters that aren't other services

**How did you test each of these updates (required)**
- Unit tests

- [ ] TODO add `TransactionManager` unit tests

**Does this pull request close any open issues?**
Fixes #1906

**Checklist:**
- [x] Read the [contribution guide](./doc/contributing.md)
- [x] `make` runs successfully
- [x] All tests in `./test.sh` pass
- [x] README and other documentation updated
- [ ] [Pending changelog](./CHANGELOG_PENDING.md) updated

### CODE REVIEW

File: eth/backend.go [hunk 1]
```diff
@@ -42,32 +44,27 @@ type Backend interface {
...
+	GasPriceMonitor() *GasPriceMonitor
 }
 
 type backend struct {
 	*ethclient.Client
-	abiMap       map[string]*abi.ABI
 	nonceManager *NonceManager
 	signer       types.Signer
+	gpm          *GasPriceMonitor
+	tm           ethereum.TransactionSender
```
Comment (kyriediculous) [inline eth/backend.go]: prolly better to just refer to `*TransactionManager`

File: cmd/livepeer/livepeer.go [hunk 2]
```diff
@@ -134,6 +134,7 @@ func main() {
 	ethKeystorePath := flag.String("ethKeystorePath", "", "Path for the Eth Key")
 	ethOrchAddr := flag.String("ethOrchAddr", "", "ETH address of an on-chain registered orchestrator")
 	ethUrl := flag.String("ethUrl", "", "Ethereum node JSON-RPC URL")
+	replaceTx := flag.Bool("replaceTransactions", true, "Set to true to replace ethereum transactions with a higher gas price if they time out")
```
Comment (yondonfu) [inline cmd/livepeer/livepeer.go]: What about a `-maxTxReplacements <INTEGER>` flag instead? The value for this flag is the # of times a tx can be replaced (also the # of times the gas price of a tx can be increased). The default value could be something that feels reasonable like 3. The user could set the value to 0 to disable tx replacements.

While an excessively high # of tx replacements may be unlikely in practice if things are implemented correctly, setting a ceiling will be safer to account for pathological cases where the node might just keep endlessly replacing txs. And for users that want to be more careful, they can set a lower ceiling. With this in mind, I think it makes sense to use the same flag to express both enabling/disabling tx replacements and the max # of tx replacements.

File: pm/queue.go [hunk 3]
```diff
@@ -131,7 +131,7 @@ ticketLoop:
 						// If the ticket is used, we can mark it as redeemed
 						if res.err != nil {
 							glog.Errorf("Error redeeming err=%v", res.err)
-							if res.err != errIsUsedTicket {
+							if res.err != errIsUsedTicket && err != errTicketRevert {
```
Comment (yondonfu) [inline pm/queue.go]:
```suggestion
							if res.err != errIsUsedTicket && res.err != errTicketRevert {
```

File: eth/backend.go [hunk 4]
```diff
@@ -197,18 +147,48 @@ func (b *backend) retryRemoteCall(remoteCall func() ([]byte, error)) (out []byte
...
 
-func makeABIMap() (map[string]*abi.ABI, error) {
+func makeABIMap() map[string]*abi.ABI {
 	abiMap := make(map[string]*abi.ABI)
 
 	for _, ABI := range abis {
 		parsedAbi, err := abi.JSON(strings.NewReader(ABI))
 		if err != nil {
-			return map[string]*abi.ABI{}, err
+			glog.Errorf("Error creating ABI mappings, can not parse transaction logs err=%v", err)
```
Comment (yondonfu) [inline eth/backend.go]:
```suggestion
			glog.Errorf("Error creating ABI map err=%v", err)
```

since there is no transaction log parsing in this function.

File: eth/client.go [hunk 5]
```diff
@@ -883,84 +888,31 @@ func (c *client) ContractAddresses() map[string]ethcommon.Address {
...
+	for {
+		select {
+		case err := <-txSub.Err():
+			return err
+		case event := <-txs:
+			if tx.Hash() == event.TxHash {
+				if event.Status == uint64(0) {
+					return fmt.Errorf("transaction failed txHash=%v", event.TxHash)
+				}
+				break txLoop
```
Comment (yondonfu) [inline eth/client.go]: Can we just return nil here?

File: eth/transactionManager.go [hunk 6]
```diff
@@ -0,0 +1,233 @@
...
+		for {
+			if err := tm.wait(tx); err == context.DeadlineExceeded && tm.replaceTx {
+				newTx, replaceErr := tm.replace(tx)
+				if replaceErr != nil {
+					glog.Error(replaceErr)
+					break
+				}
+				tx = newTx
+			} else {
+				glog.Error(err)
```
Comment (yondonfu) [inline eth/transactionManager.go]: There should be an error check here. Otherwise this will log err even if it is nil.

File: eth/transactionManager.go [hunk 7]
```diff
@@ -0,0 +1,233 @@
...
+	defer cancel()
+
+	receipt, err := bind.WaitMined(ctx, tm.eth, tx)
+	if err != nil {
+		return err
+	}
+
+	tm.feed.Send(receipt)
+
+	if receipt.Status == uint64(0) {
```
Comment (yondonfu) [inline eth/transactionManager.go]: What about just letting the caller i.e. CheckTx() handle this check? Otherwise, we currently have this check here and in CheckTx().

File: eth/client.go [hunk 8]
```diff
@@ -883,84 +888,31 @@ func (c *client) ContractAddresses() map[string]ethcommon.Address {
...
 
 func (c *client) CheckTx(tx *types.Transaction) error {
-	ctx, cancel := context.WithTimeout(context.Background(), c.txTimeout)
-	defer cancel()
-
-	receipt, err := bind.WaitMined(ctx, c.backend, tx)
-	if err != nil {
-		return err
+	txs := make(chan *types.Receipt, 10)
+	b, ok := c.backend.(*backend)
```
Comment (yondonfu) [inline eth/client.go]: Could we avoid this type assertion if the TransactionManager was just a field on `client`? Feels a bit weird to do a type assertion just so we can fetch the TransactionManager field on the underlying backend type.

File: eth/client.go [hunk 9]
```diff
@@ -883,84 +888,31 @@ func (c *client) ContractAddresses() map[string]ethcommon.Address {
...
+	txSub := b.tm.Subscribe(txs)
+	defer txSub.Unsubscribe()
+
+txLoop:
+	for {
+		select {
+		case err := <-txSub.Err():
+			return err
+		case event := <-txs:
+			if tx.Hash() == event.TxHash {
```
Comment (yondonfu) [inline eth/client.go]: Looks like this TransactionManager API currently implies that a tx will always be confirmed which is signaled by receiving a receipt in the subscription channel. Do we really want the API to make this guarantee to the caller? If we end up adding a max # of replacements there seems like there could be edge cases where the max # of replacements is hit without the tx being confirmed. In that scenario, a receipt would never be received in the subscription channel and the caller would wait forever. Perhaps the API should give the caller a receipt *or* an error?

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: cmd/livepeer/livepeer.go (hunk 2 above)
Comment (kyriediculous) [reply cmd/livepeer/livepeer.go]: I think this can be a neat addition yeah. One thing that I don't really like here is the hardcoded `EThTxTimeout`, while a user can set the number of max replacements to do it is not immeadiatly known how often the replacement will be tried. 

Allowing a `ethTxTimeout` flag could help here but also again increases the amount of config params required. 

What are your thoughts on that?

**Comment by kyriediculous** [comment]
@yondonfu Do we want persistent storage for the transaction confirmation queue to avoid unexpected behaviour between node restarts when transactions are still pending ?

File: eth/client.go (hunk 8 above)
Comment (kyriediculous) [reply eth/client.go]: The contract bindings use `Backend` to send transactions which uses `TransactionManager` under the hood. 

The `Backend` does not have access to the `client`.

File: eth/client.go (hunk 9 above)
Comment (kyriediculous) [reply eth/client.go]: Yeah in retrospect I like your idea better than the current implementation, this will also give us access to revert reason error messages being returned back through `checkTx` 

Updated this API and its implementation in 41d57f11cc1d93e63a2345f082783d00eb600e24

File: eth/client.go (hunk 8 above)
Comment (yondonfu) [reply eth/client.go]: I was thinking something like this:

```golang
type client struct {
    // Other fields
    ...
    transactionManager *TransactionManager // This is the same TransactionManager used by the backend
}

func (c *client) CheckTx(tx *types.Transaction) error {
    receipts := make(chan *transactionReceipt, 10)
    txSub := c.transactionManager.Subscribe(receipts)
    defer txSub.Unsubscribe()
    ...
}
```

The main reason for this suggestion is that it feels a bit weird to break the Backend interface abstraction with a type assertion just to fetch the TransactionManager field on the underlying backend type. If we're breaking the Backend interface abstraction within the client then it raises the question of why the Backend interface is being used if we're exposing the implementation details of the underlying type to the client.

File: eth/gaspricemonitor.go [hunk 10]
```diff
@@ -125,6 +127,18 @@ func (gpm *GasPriceMonitor) Stop() error {
 	return nil
 }
 
+func (gpm *GasPriceMonitor) SetMaxGasPrice(gp *big.Int) {
+	gpm.gasPriceMu.Lock()
+	defer gpm.gasPriceMu.Unlock()
+	gpm.maxGasPrice = gp
+}
+
+func (gpm *GasPriceMonitor) MaxGasPrice() *big.Int {
```
Comment (yondonfu) [inline eth/gaspricemonitor.go:168]: I think the maxGasPrice field should also be initialized in the constructor.

File: eth/client.go [hunk 11]
```diff
@@ -148,34 +145,42 @@ type client struct {
...
 }
 
-func NewClient(accountAddr ethcommon.Address, keystoreDir, password string, eth *ethclient.Client, controllerAddr ethcommon.Address, txTimeout time.Duration, maxGasPrice *big.Int) (LivepeerEthClient, error) {
+type LivepeerEthClientConfig struct {
+	AccountAddr       ethcommon.Address
+	KeystoreDir       string
+	Password          string
+	ControllerAddr    ethcommon.Address
+	TxTimeout         time.Duration
+	MaxGasPrice       *big.Int
```
Comment (yondonfu) [inline eth/client.go]: Doesn't look like this is used anywhere. If we add support for initializing the maxGasPrice field in the GasPriceMonitor constructor we could remove this field since the client is initialized with an existing GasPriceMonitor instance which should already have an initialized maxGasPrice.

File: eth/transactionManager.go [hunk 12]
```diff
@@ -0,0 +1,241 @@
...
+	"github.com/ethereum/go-ethereum/core/types"
+	"github.com/ethereum/go-ethereum/ethclient"
+	"github.com/ethereum/go-ethereum/event"
+	"github.com/golang/glog"
+	"github.com/livepeer/go-livepeer/common"
+)
+
+type TransactionManager struct {
+	txTimeout       time.Duration
+	maxReplaceMents int
```
Comment (yondonfu) [inline eth/transactionManager.go]:
```suggestion
	maxTxReplacements int
```

File: eth/transactionManager.go [hunk 13]
```diff
@@ -0,0 +1,241 @@
...
+	am  AccountManager
+
+	cond sync.Cond
+
+	quit chan struct{}
+}
+
+type transactionQueue []*types.Transaction
+
+type transactionReceipt struct {
```
Comment (yondonfu) [inline eth/transactionManager.go:52]: Would `transactionResult` be a more clearer name given that this struct already holds a transaction receipt?

File: eth/client.go [hunk 14]
```diff
@@ -148,34 +145,42 @@ type client struct {
...
 	if err != nil {
 		return nil, err
 	}
-	backend.SetMaxGasPrice(maxGasPrice)
 
-	am, err := NewAccountManager(accountAddr, keystoreDir, signer)
-	if err != nil {
-		return nil, err
-	}
+	tm := NewTransactionManager(eth, gpm, am, cfg.TxTimeout, cfg.MaxTxReplacements)
```
Comment (yondonfu) [inline eth/client.go]: Doesn't look like `Start()` and `Stop()` are ever called for the TransactionManager which would be required to start the checkTxLoop.

File: eth/transactionManager.go [hunk 15]
```diff
@@ -0,0 +1,241 @@
...
+		var (
+			receipt *types.Receipt
+			err     error
+		)
+
+		for i := 0; i <= tm.maxReplaceMents; i++ {
+			if receipt, err = tm.wait(tx); err == context.DeadlineExceeded && tm.maxReplaceMents > 0 {
+				newTx, replaceErr := tm.replace(tx)
+				if replaceErr != nil {
+					glog.Error(replaceErr)
```
Comment (yondonfu) [inline eth/transactionManager.go]: I think `replaceError` should be propagated back to the feed so that a consumer of the feed can get error information about the failed replacement. At the moment, after we break here, the value sent to the feed will just include the `err` variable which would just be `context.DeadlineExceeded`.

File: eth/transactionManager.go [hunk 16]
```diff
@@ -0,0 +1,241 @@
...
+					break
+				}
+				tx = newTx
+			} else {
+				if err != nil {
+					glog.Error(err)
```
Comment (yondonfu) [inline eth/transactionManager.go]: I think this error should be propagated back to the feed so that a consumer of the feed can get error information about the failed replacement. At the moment, after we break here, the value sent to the feed will just include the original `err` variable which would be `context.DeadlineExceeded`.

File: pm/sendermonitor.go [hunk 17]
```diff
@@ -422,7 +424,7 @@ func (sm *LocalSenderMonitor) redeemWinningTicket(ticket *SignedTicket) (*types.
 		if monitor.Enabled {
 			monitor.TicketRedemptionError()
 		}
-		return nil, err
+		return nil, errTicketRevert
```
Comment (yondonfu) [inline pm/sendermonitor.go]: Returning `errTicketRevert` here obfuscates the error returned by `CheckTx` which also includes the hash of the reverted tx. As a result, we lose access to that information. Could we continue passing the error from `CheckTx` here and having a different check for a reverted tx error?

**Review by yondonfu — CHANGES_REQUESTED** [review]
How were these changes tested?

Given that the logic of the transaction manager for handling replacing pending transactions is important for funds management and node operation could we add unit tests particularly around the automated transaction replacement flow?

File: eth/transactionManager.go (hunk 16 above)
Comment (kyriediculous) [reply eth/transactionManager.go]: This error is already propagated back to the feed by default and can only ever result in it being `context.DeadlineExceeded` when the node isn't set to replace transactions in which case we likely want to notify the user to manually check confirmation through this error.

File: cmd/devtool/devtool.go [hunk 18]
```diff
@@ -159,10 +161,42 @@ func ethSetup(ethAcctAddr, keystoreDir string, isBroadcaster bool) {
 	}
 	glog.Infof("Using controller address %s", ethController)
 
-	client, err := eth.NewClient(ethcommon.HexToAddress(ethAcctAddr), keystoreDir, passphrase, backend,
-		ethcommon.HexToAddress(ethController), ethTxTimeout, nil)
+	gpm := eth.NewGasPriceMonitor(backend, 5*time.Second, big.NewInt(0), nil)
+
+	chainID, err := backend.ChainID(context.Background())
+	if err != nil {
+		glog.Errorf("failed to get chain ID from remote ethereum node: %v", err)
```
Comment (yondonfu) [inline cmd/devtool/devtool.go]:
```suggestion
		glog.Errorf("Failed to get chain ID from remote ethereum node: %v", err)
```

File: cmd/devtool/devtool.go [hunk 19]
```diff
@@ -159,10 +161,42 @@ func ethSetup(ethAcctAddr, keystoreDir string, isBroadcaster bool) {
...
+		return
+	}
+
+	signer := types.NewEIP155Signer(chainID)
+
+	am, err := eth.NewAccountManager(ethcommon.HexToAddress(ethAcctAddr), keystoreDir, signer)
+	if err != nil {
+		glog.Errorf("error creating Ethereum account manager: %v", err)
```
Comment (yondonfu) [inline cmd/devtool/devtool.go]:
```suggestion
		glog.Errorf("Error creating Ethereum account manager: %v", err)
```

File: cmd/devtool/devtool.go [hunk 20]
```diff
@@ -159,10 +161,42 @@ func ethSetup(ethAcctAddr, keystoreDir string, isBroadcaster bool) {
...
+		return
+	}
+
+	if err := am.Unlock(passphrase); err != nil {
+		glog.Errorf("error unlocking Ethereum account: %v", err)
+		return
+	}
+
+	tm := eth.NewTransactionManager(backend, gpm, am, 5*time.Minute, 0)
+	tm.Start()
```
Comment (yondonfu) [inline cmd/devtool/devtool.go]: This will block so it should be called in a goroutine.

File: cmd/livepeer/livepeer.go [hunk 21]
```diff
@@ -390,7 +392,41 @@ func main() {
 			bigMaxGasPrice = big.NewInt(int64(*maxGasPrice))
 		}
 
-		client, err := eth.NewClient(ethcommon.HexToAddress(*ethAcctAddr), keystoreDir, *ethPassword, backend, ethcommon.HexToAddress(*ethController), EthTxTimeout, bigMaxGasPrice)
+		gpm := eth.NewGasPriceMonitor(backend, blockPollingTime, minGasPrice, bigMaxGasPrice)
+		// Start gas price monitor
+		_, err = gpm.Start(ctx)
+		if err != nil {
+			glog.Errorf("error starting gas price monitor: %v", err)
```
Comment (yondonfu) [inline cmd/livepeer/livepeer.go]:
```suggestion
			glog.Errorf("Error starting gas price monitor: %v", err)
```

File: cmd/livepeer/livepeer.go [hunk 22]
```diff
@@ -390,7 +392,41 @@ func main() {
...
+			return
+		}
+		defer gpm.Stop()
+
+		signer := types.NewEIP155Signer(chainID)
+
+		am, err := eth.NewAccountManager(ethcommon.HexToAddress(*ethAcctAddr), keystoreDir, signer)
+		if err != nil {
+			glog.Errorf("error creating Ethereum account manager: %v", err)
```
Comment (yondonfu) [inline cmd/livepeer/livepeer.go]:
```suggestion
			glog.Errorf("Error creating Ethereum account manager: %v", err)
```

File: cmd/livepeer/livepeer.go [hunk 23]
```diff
@@ -390,7 +392,41 @@ func main() {
...
+			return
+		}
+
+		if err := am.Unlock(*ethPassword); err != nil {
+			glog.Errorf("error unlocking Ethereum account: %v", err)
```
Comment (yondonfu) [inline cmd/livepeer/livepeer.go]:
```suggestion
			glog.Errorf("Error unlocking Ethereum account: %v", err)
```

File: cmd/devtool/devtool.go [hunk 24]
```diff
@@ -159,10 +161,42 @@ func ethSetup(ethAcctAddr, keystoreDir string, isBroadcaster bool) {
...
+	signer := types.NewEIP155Signer(chainID)
+
+	am, err := eth.NewAccountManager(ethcommon.HexToAddress(ethAcctAddr), keystoreDir, signer)
+	if err != nil {
+		glog.Errorf("error creating Ethereum account manager: %v", err)
+		return
+	}
+
+	if err := am.Unlock(passphrase); err != nil {
+		glog.Errorf("error unlocking Ethereum account: %v", err)
```
Comment (yondonfu) [inline cmd/devtool/devtool.go]:
```suggestion
		glog.Errorf("Error unlocking Ethereum account: %v", err)
```

File: cmd/livepeer/livepeer.go [hunk 25]
```diff
@@ -390,7 +392,41 @@ func main() {
...
+			return
+		}
+
+		tm := eth.NewTransactionManager(backend, gpm, am, EthTxTimeout, *maxTxReplacements)
+		tm.Start()
```
Comment (yondonfu) [inline cmd/livepeer/livepeer.go]: This will block so it needs to be called in a goroutine.

File: eth/client.go [hunk 26]
```diff
@@ -883,84 +870,28 @@ func (c *client) ContractAddresses() map[string]ethcommon.Address {
...
+		select {
+		case err := <-txSub.Err():
+			return err
+		case receipt := <-receipts:
+			if tx.Hash() == receipt.TxHash {
+				if receipt.err != nil {
+					return receipt.err
+				}
+				if receipt.Status == uint64(0) {
+					return fmt.Errorf("transaction failed txHash=%v", receipt.TxHash)
```
Comment (yondonfu) [inline eth/client.go]:
```suggestion
					return fmt.Errorf("transaction failed txHash=%v", receipt.TxHash.Hex())
```

I think we need to call Hex() in order to log a hex string here?

File: eth/transactionManager.go [hunk 27]
```diff
@@ -0,0 +1,242 @@
...
+	txTimeout       time.Duration
+	maxReplacements int
+
+	queue transactionQueue
+
+	// subscriptions
+	feed  event.Feed
+	scope event.SubscriptionScope
+
+	eth *ethclient.Client
```
Comment (yondonfu) [inline eth/transactionManager.go]: A thought on how we could test the tx replacement behavior:

Replacing this `ethclient.Client` with an interface might make writing tests for the replacement logic easier. 

Something like:

```golang
type TransactionSenderReader interface {
	ethereum.TransactionSender
	ethereum.TransactionReader
	// Required for bind.DeployBackend argument in bind.WaitMined
	CodeAt(context.Context, ethcommon.Address, *big.Int) ([]byte, error)
}
```

Then, a stub implementation of the interface could be used in tests allowing us to control how long it takes for a transaction receipt to be returned in `bind.WaitMined()` since the stub implementation could wait X ms before returning a receipt for a call to `TransactionReceipt()`. If the `txTimeout` is set to Y ms such that Y < X, then we should be able to trigger a timeout which should prompt the TransactionManager to submit a replacement tx. The stub implementation could keep track of the txs sent via `SendTransaction()` and we could check the gas price and nonce for txs to assert that replacement txs are actually being sent. Then, we could also write assertions that the TransactionManager does not submit more than `maxReplacements` replacement txs.

File: eth/transactionManager.go (hunk 16 above)
Comment (yondonfu) [reply eth/transactionManager.go]: My mistake - I misread the code. You're right that this error is propagated to the feed.

File: eth/transactionManager.go [hunk 28]
```diff
@@ -0,0 +1,242 @@
...
+				tx = newTx
+			} else {
+				if err != nil {
+					glog.Error(err)
+				}
+				break
+			}
+		}
+
+		tm.feed.Send(&transactionReceipt{*receipt, err})
```
Comment (yondonfu) [inline eth/transactionManager.go]: This will trigger a nil pointer error if `receipt` is nil which will happen if we encounter an error with the tx such that we get a nil receipt back. If the field on the struct here was a receipt pointer instead of a receipt value we could avoid this and then it would be the responsibility of the feed consumer to only rely on the receipt field if there is a non-nil error.

File: eth/transactionManager.go [hunk 29]
```diff
@@ -0,0 +1,242 @@
...
+
+		tx := tm.queue.pop()
+		tm.cond.L.Unlock()
+
+		var (
+			receipt *types.Receipt
+			err     error
+		)
+
+		for i := 0; i <= tm.maxReplacements; i++ {
```
Comment (yondonfu) [inline eth/transactionManager.go]: Suggestion for a refactor here that I think flattens the code structure to improve readability:

```golang
receipt, err = tm.wait(tx)
// context.DeadlineExceeded indicates that we hit the txTimeout
// If we hit the txTimeout, replace the tx up to maxReplacements times
for i := 0; err == context.DeadlineExceeded && i < tm.maxReplacements; i++ {
	tx, err = tm.replace(tx)
	// Do not attempt additional replacements if there was an error submitting this
	// replacement tx
	if err != nil {
		break
	}
	receipt, err = tm.wait(tx)
}
```

File: pm/sendermonitor.go [hunk 30]
```diff
@@ -25,6 +25,8 @@ var unixNow = func() int64 {
 	return time.Now().Unix()
 }
 
+type checkTxError error
```
Comment (yondonfu) [inline pm/sendermonitor.go]:
```suggestion
type errCheckTx error
```

To match the error naming convention used elsewhere in this package.

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: eth/transactionManager.go (hunk 28 above)
Comment (kyriediculous) [reply eth/transactionManager.go]: Yeah probably better to use a pointer here but copying the actual values felt much cleaner and it does feel like we sometimes might overuse pointers a bit which might lead to memory safety issues that can be hard to debug (started thinking about this after the discussing about golang vs rust in discord). However that's unlikely to be much of an issue here so yeah; pointer.

File: eth/transactionManager.go (hunk 29 above)
Comment (kyriediculous) [reply eth/transactionManager.go]: I understand that it's a little bit cleaner and shorter but what I generally dislike is having the same function call before the loop (to 'initialize') as inside of it. 

However this suggestion made me realise a small error in the conditional of the loop in my code which also shortens that up.

Comment (kyriediculous) [reply eth/transactionManager.go]: Ended up going with the suggestion because otherwise we don't wait for the last iteration of the replacement loop and thus the last replacement tx

File: cmd/livepeer/livepeer.go [hunk 31]
```diff
@@ -134,6 +135,7 @@ func main() {
 	ethKeystorePath := flag.String("ethKeystorePath", "", "Path for the Eth Key")
 	ethOrchAddr := flag.String("ethOrchAddr", "", "ETH address of an on-chain registered orchestrator")
 	ethUrl := flag.String("ethUrl", "", "Ethereum node JSON-RPC URL")
+	maxTxReplacements := flag.Int("maxTransactionReplacements", 0, "Number of times to automatically replace pending Ethereum transactions")
```
Comment (yondonfu) [inline cmd/livepeer/livepeer.go]: What do you think about setting the default value for this flag to 2? This would enable tx replacements by default which helps address scenarios like super low gas price txs without requiring manual intervention from the node operator. A node operator could always disable the feature by manually passing `-maxTransactionReplacements 0` on startup. The suggestion of 2 is fairly arbitrary although it feels like a reasonable number of times to replace a tx.

File: eth/transactionManager.go (hunk 13 above)
Comment (yondonfu) [reply eth/transactionManager.go:52]: Bump.

File: eth/transactionManager.go [hunk 32]
```diff
@@ -0,0 +1,259 @@
...
+func (tm *TransactionManager) Stop() {
+	tm.scope.Close()
+	close(tm.quit)
+}
+
+func (tm *TransactionManager) wait(tx *types.Transaction) (*types.Receipt, error) {
+	ctx, cancel := context.WithTimeout(context.Background(), tm.txTimeout)
+	defer cancel()
+
+	receipt, err := bind.WaitMined(ctx, tm.eth, tx)
```
Comment (yondonfu) [inline eth/transactionManager.go]: Can shorten this to just:

```golang
return bind.WaitMined(ctx, tm.eth, tx)
```

File: eth/transactionManager.go [hunk 33]
```diff
@@ -0,0 +1,259 @@
...
+	if err != nil && err != ethereum.NotFound {
+		return nil, err
+	}
+	// If tx was found
+	// If `pending` is false, the tx was mined and included in a block
+	if err == nil && !pending {
+		return nil, ErrReplacingMinedTx
+	}
+
+	// Updated gas price must be at least 10% greater than the gas price used for the original transaction in order
```
Comment (yondonfu) [inline eth/transactionManager.go]: Let's move this comment into `calcReplacementGasPrice()`

File: eth/transactionManager.go [hunk 34]
```diff
@@ -0,0 +1,259 @@
...
+	// since the time of the original tx submission we cannot use the lower suggested gas price and we still need to use
+	// the bumped gas price in order to properly replace a still pending tx
+	if suggestedGasPrice.Cmp(gasPrice) == 1 {
+		gasPrice = suggestedGasPrice
+	}
+
+	// Bump gas price exceeds max gas price, return early
+	max := tm.gpm.MaxGasPrice()
+	if gasPrice.Cmp(max) > 0 {
+		return nil, fmt.Errorf("Replacement gas price exceeds max gas price suggested=%v max=%v", gasPrice, max)
```
Comment (yondonfu) [inline eth/transactionManager.go]:
```suggestion
		return nil, fmt.Errorf("replacement gas price exceeds max gas price suggested=%v max=%v", gasPrice, max)
```

To follow convention of error messages in lowercase (except if its extra annotation text in an error log statement)

File: eth/transactionManager_test.go [hunk 35]
```diff
@@ -0,0 +1,320 @@
...
+	assert.EqualError(err, expErr.Error())
+	eth.err["TransactionByHash"] = nil
+
+	// Test no error - ErrReplacingMinedTx
+	eth.pending = false
+	tx, err = tm.replace(stubTx)
+	assert.Nil(tx)
+	assert.EqualError(err, ErrReplacingMinedTx.Error())
+
+	// Test error is eth.TransactionNotFound - fail at next step
```
Comment (yondonfu) [inline eth/transactionManager_test.go]:
```suggestion
	// Test error is ethereum.NotFound - fail at next step
```

File: cmd/devtool/devtool.go (hunk 20 above)
Comment (kyriediculous) [reply cmd/devtool/devtool.go]: Sorry missed this one, fixed in the latest commit

File: eth/transactionManager_test.go [hunk 36]
```diff
@@ -0,0 +1,320 @@
...
+	tx, err = tm.replace(stubTx)
+	logsAfter = glog.Stats.Info.Lines()
+	assert.Nil(err)
+	expTx := types.NewTransaction(1, *stubTx.To(), stubTx.Value(), 100000, calcReplacementGasPrice(stubTx), stubTx.Data())
+	assert.Equal(tx, expTx)
+	assert.Equal(logsAfter-logsBefore, int64(1))
+
+	// Replacement gas price lower than suggest gas price
+	// Use market gas price
+	gpm.gasPrice = big.NewInt(999)
```
Comment (yondonfu) [inline eth/transactionManager_test.go:245]: Could be worthwhile to add an assertion here making sure that the GasPriceMonitor gas price is greater than the value returned by `calcReplacementGasPrice(stubTx)`.

File: eth/transactionManager_test.go [hunk 37]
```diff
@@ -0,0 +1,320 @@
...
+	sink := make(chan *transactionReceipt, 10)
+	sub := tm.Subscribe(sink)
+	defer sub.Unsubscribe()
+	tm.SendTransaction(context.Background(), stubTx)
+
+	event := <-sink
+	assert.NotNil(event)
+	assert.Nil(event.err)
+
+	// Wait error no replacements
```
Comment (yondonfu) [inline eth/transactionManager_test.go:302]: Isn't maxReplacement in the TransactionManager still set to 1 here? And in that case, we get a context.DeadlineExceeded error after 2 calls to wait() with the second being for a replacement tx.

File: eth/transactionManager_test.go [hunk 38]
```diff
@@ -0,0 +1,320 @@
...
+	eth.err["TransactionReceipt"] = nil
+
+	// Wait error, replacements
+	// Replace tx error
+	tm.maxReplacements = 1
+	eth.err["TransactionReceipt"] = context.DeadlineExceeded
+	eth.err["TransactionByHash"] = errors.New("TransactionByHash error")
+	sink = make(chan *transactionReceipt)
+	sub = tm.Subscribe(sink)
+	time.Sleep(5 * time.Millisecond)
```
Comment (yondonfu) [inline eth/transactionManager_test.go]: Why is there a sleep here after the Subscribe() call, but not after any of the other previous Subscribe() calls?

File: eth/transactionManager_test.go [hunk 39]
```diff
@@ -0,0 +1,320 @@
...
+	logsBefore = glog.Stats.Info.Lines()
+	tx, err = tm.replace(stubTx)
+	logsAfter = glog.Stats.Info.Lines()
+	assert.Nil(err)
+	expTx = types.NewTransaction(1, *stubTx.To(), stubTx.Value(), 100000, gpm.gasPrice, stubTx.Data())
+	assert.Equal(tx, expTx)
+	assert.Equal(logsAfter-logsBefore, int64(1))
+}
+
+func TestTransactionManager_CheckTxLoop(t *testing.T) {
```
Comment (yondonfu) [inline eth/transactionManager_test.go:256]: I think we should add a test to ensure that in the worst case we only submit maxReplacements number of replacement txs. This test would assert that maxReplacements number of replacement txs were submitted, but no more than that.

File: eth/transactionManager.go [hunk 40]
```diff
@@ -0,0 +1,259 @@
...
+
+		tm.feed.Send(&transactionReceipt{
+			Receipt: receipt,
+			err:     err,
+		})
+
+	}
+}
+
+func calcReplacementGasPrice(tx *types.Transaction) *big.Int {
```
Comment (yondonfu) [inline eth/transactionManager.go:243]: We don't need to address this in this PR, but just making a note that we will probably want to eventually make the gas price bump a parameter given that its a value that influences how soon a replacement tx will be mined and given that the gas price bump required by an ETH node technically doesn't have to be 10% (that just happens to be the default on geth, but there is an option to customize it).

File: eth/rewardservice.go [hunk 41]
```diff
@@ -91,30 +91,11 @@ func (s *RewardService) tryReward() error {
...
-		}
-
-		tp, err := s.client.GetTranscoderEarningsPoolForRound(s.client.Account().Address, currentRound)
-		if err != nil {
+		if err := s.client.CheckTx(tx); err != nil {
 			return err
 		}
 
-		glog.Infof("Called reward for round %v - %v rewards minted", currentRound, FormatUnits(tp.RewardPool, "LPTU"))
+		glog.Infof("Called reward for round %v", currentRound)
```
Comment (yondonfu) [inline eth/rewardservice.go:98]: Just noting that this is related to https://github.com/livepeer/go-livepeer/issues/1822

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: cmd/livepeer/livepeer.go (hunk 2 above)
Comment (yondonfu) [reply cmd/livepeer/livepeer.go]: Oops missed this comment in the first couple of reviews.

I think it makes sense to allow the timeout to be configurable. What about `-transactionTimeout`?

File: cmd/livepeer/livepeer.go (hunk 31 above)
Comment (kyriediculous) [reply cmd/livepeer/livepeer.go]: A feature that changes the existing behaviour should in my opinion not be enabled by default.

Comment (kyriediculous) [reply cmd/livepeer/livepeer.go]: But I'm open to discuss this, I feel like if replacements should be the default then I think the default should be one replacement, which at least for the reward calls retains the same behaviour.

File: eth/transactionManager.go (hunk 40 above)
Comment (kyriediculous) [reply eth/transactionManager.go:243]: Wouldn't that only be supportable by self-hosted geth nodes because if the configuration on the livepeer node is set to a lower replacement bump than i.e. infura you would still see `replacement tx underpriced` no ?

File: eth/rewardservice.go (hunk 41 above)
Comment (kyriediculous) [reply eth/rewardservice.go:98]: Yeah sorry for including it here, it doesn't fully address #1822 in that rather than fixing the value shown I decided to remove it for now to avoid confusion.

File: eth/transactionManager.go (hunk 13 above)
Comment (kyriediculous) [reply eth/transactionManager.go:52]: I went with `transactionReceipt` since the receipt values are embedded in this type (through albeit through a pointer) with the addition of an error (which can be the revert message in some cases).

File: eth/transactionManager_test.go (hunk 39 above)
Comment (kyriediculous) [reply eth/transactionManager_test.go:256]: Would something like this work 840c9f4 ?

File: eth/transactionManager_test.go [hunk 42]
```diff
@@ -296,6 +298,7 @@ func TestTransactionManager_CheckTxLoop(t *testing.T) {
 	event := <-sink
 	assert.NotNil(event)
 	assert.Nil(event.err)
+	sub.Unsubscribe()
```
Comment (yondonfu) [inline eth/transactionManager_test.go:300]: Should we remove the deferred Unsubscribe() call on L295 if we're calling Unsubscribe() for each new subscription at the end of each test case?

File: eth/transactionManager_test.go (hunk 39 above)
Comment (yondonfu) [reply eth/transactionManager_test.go:256]: Looks good.

File: eth/rewardservice.go (hunk 41 above)
Comment (yondonfu) [reply eth/rewardservice.go:98]: Yep that's fine I was just making this note for myself as a reminder.

File: eth/transactionManager.go (hunk 40 above)
Comment (yondonfu) [reply eth/transactionManager.go:243]: Yeah if your gas price bump is lower than the gas price bump required by the ETH provider you would receive a `replacement tx underpriced` error.

Aside from speeding up the confirmation of replacement txs, the motivation for supporting custom gas price bumps is to give the livepeer node operator to adjust the gas price bump (i.e. increase it) used if the ETH provider requires a gas price bump different (i.e. greater) than the current default of 10%. If the node operator does not control the ETH provider (i.e. self-hosted node(s)) and the ETH provider is configured to use a non-default gas price bump (or if the default ever changes) then the current hardcoded gas price bump in the livepeer node may not work.

Anyways this isn't that crucial at the moment, but just wanted to point this out for future reference.

File: cmd/livepeer/livepeer.go (hunk 31 above)
Comment (yondonfu) [reply cmd/livepeer/livepeer.go]: > A feature that changes the existing behaviour should in my opinion not be enabled by default.

Well that depends on whether the existing default behavior is a problem. Based on #1906, I think this is a case where the existing default behavior can actually be a problem. Also, if the default is 0, then we'd be changing existing behavior for reward calls except this is actually hampering the node's ability to deal with getting transactions confirmed in a timely manner for reward calls instead of improving it.

> I feel like if replacements should be the default then I think the default should be one replacement

I'd be onboard with a default of 1 to be a bit more conservative with the default.

**Review by yondonfu — COMMENTED** [review]
Just two comments to address:

- [Default flag values](https://github.com/livepeer/go-livepeer/pull/1923#discussion_r669943483)
- [Small test related comment](https://github.com/livepeer/go-livepeer/pull/1923#discussion_r669905869)

Let's also rebase on top of master to resolve the conflicts. Feel free to do this in conjunction with addressing the remaining comments.

**Comment by kyriediculous** [comment]
Rebased, resolved merge conflicts and addresses the remaining changes. 

Also moved min and max gas price completely into `GasPriceMonitor` as discussed previously.

File: eth/backend.go [hunk 43]
```diff
@@ -83,63 +75,43 @@ func (b *backend) PendingNonceAt(ctx context.Context, account common.Address) (u
...
-	if gp != nil && monitor.Enabled {
-		monitor.MaxGasPrice(gp)
-	}
-}
-
-func (b *backend) MaxGasPrice() *big.Int {
-	b.RLock()
-	defer b.RUnlock()
-	return b.maxGasPrice
+func (b *backend) GasPriceMonitor() *GasPriceMonitor {
```
Comment (yondonfu) [inline eth/backend.go:113]: Since we're removing the max gas price setters/getters from backend should we also remove the min gas price setters/getters with the expectation that the appropriate setters/getters can be called on the GasPriceMonitor returned here?

File: eth/gaspricemonitor.go [hunk 44]
```diff
@@ -148,6 +151,18 @@ func (gpm *GasPriceMonitor) Stop() error {
 	return nil
 }
 
+func (gpm *GasPriceMonitor) SetMaxGasPrice(gp *big.Int) {
```
Comment (yondonfu) [inline eth/gaspricemonitor.go:158]: This is currently missing the metrics recording call via the monitor package that was included in the [method definition](https://github.com/livepeer/go-livepeer/blob/0a72c0ac52b97b37bd2fb51c865ac3f2a3592bc3/eth/backend.go#L134) in backend.

File: eth/gaspricemonitor.go [hunk 45]
```diff
@@ -54,6 +56,7 @@ func NewGasPriceMonitor(gpo GasPriceOracle, pollingInterval time.Duration, minGa
 		pollingInterval: pollingInterval,
 		gasPrice:        big.NewInt(0),
 		minGasPrice:     minGasP,
+		maxGasPrice:     maxGasPrice,
```
Comment (yondonfu) [inline eth/gaspricemonitor.go:63]: Let's add a metrics recording call for maxGasPrice similar to the one we have for minGasPrice on L52 (will probably need a nil check as well in case maxGasPrice is nil).

**Review by yondonfu — CHANGES_REQUESTED** [review]

File: eth/backend.go (hunk 43 above)
Comment (kyriediculous) [reply eth/backend.go:113]: Oh yeah forgot to remove these, the calls were already updated to call them on the GPM instead

File: eth/gaspricemonitor.go (hunk 45 above)
Comment (kyriediculous) [reply eth/gaspricemonitor.go:63]: fixed in 91ceac9

File: eth/gaspricemonitor.go (hunk 44 above)
Comment (kyriediculous) [reply eth/gaspricemonitor.go:158]: fixed in 91ceac9

File: eth/backend.go (hunk 43 above)
Comment (kyriediculous) [reply eth/backend.go:113]: fixed in 91ceac9

**Review by yondonfu — APPROVED** [review]
LGTM after squashing 🚢
