### PR TITLE
test_args: Update Rinkeby URL in test

### LINKED ISSUE #1372: ci: every build is failing
Seems bad. I can investigate but at a quick glance it looks like a test is failing?

### PR DESCRIPTION
**Pull request by yondonfu**
**What does this pull request do? Explain your changes. (required)**

This PR updates the Rinkeby Infura URL used in `test_args.sh` to include a missing project ID. I think this should fix the current failing CI builds.

**Specific updates (required)**

- Update Rinkeby Infura URL in `test_args.sh`

**How did you test each of these updates (required)**

Let's see if CI passes...

I also tried running a node with `-ethUrl` set to a Rinkeby Infura URL without a project ID and encountered:

```
I0211 22:00:25.969886   18326 livepeer.go:203] ***Livepeer is running on the rinkeby network: 0xA268AEa9D048F8d3A592dD7f1821297972D4C8Ea***
I0211 22:00:25.970886   18326 db.go:316] Initialized DB node
E0211 22:00:26.072863   18326 livepeer.go:325] Failed to connect to Ethereum client: websocket: bad handshake (HTTP status 403 Forbidden)
I0211 22:00:26.072892   18326 db.go:321] Closing DB
```

I also tried running a node with `-ethUrl` set to a Rinkeby Infura URL with a project ID and did not encounter any errors.

**Does this pull request close any open issues?**

Fixes #1372 

**Checklist:**

- [ ] README and other documentation updated
- [x] Node runs in OSX and devenv
- [x] All tests in `./test.sh` pass

### CODE REVIEW

**Review by mk-livepeer — APPROVED** [review]
👍 approved conditionally on the tests passing CI

File: test_args.sh [hunk 1]
```diff
@@ -55,7 +55,7 @@ run_lp -broadcaster -network mainnet $ETH_ARGS
 [ -d "$DEFAULT_DATADIR"/mainnet ]
 kill $pid
 
-run_lp -broadcaster -network anyNetwork $ETH_ARGS -ethUrl "wss://rinkeby.infura.io/ws" -v 99
+run_lp -broadcaster -network anyNetwork $ETH_ARGS -ethUrl "https://rinkeby.infura.io/v3/09642b98164d43eb890939eb9a7ec500" -v 99
```
Comment (darkdarkdragon) [inline test_args.sh:58]: Is this (https://rinkeby.infura.io/v3/09642b98164d43eb890939eb9a7ec500) a public information? Or it is some private access token?

Comment (yondonfu) [reply test_args.sh:58]: It's a project ID that Livepeer Inc created that is basically public information since it needs to be included in the URL. Access to the endpoint really *should* be secured using a secret, but that only makes sense in a secure environment. I think we should probably discontinue shipping the node with a default Infura URL at some point and users should specify their own URL. This addition doesn't change the current status quo though - we already include the project ID [here](https://github.com/livepeer/go-livepeer/blob/10873651d9b4a73cc68153fb163fb63750de9543/cmd/livepeer/livepeer.go#L168).

Comment (darkdarkdragon) [reply test_args.sh:58]: Thanks for the explanation!

**Review by darkdarkdragon — APPROVED** [review]
LGTM 🚢

**Review by iameli — APPROVED** [review]
sweet
